In [1]:
from pyhctsa.utils import get_dataset
from pyhctsa.calculator import FeatureCalculator

# ✨ Getting Started

This tutorial covers the basics of getting started with `pyhctsa` including:

- Getting up and running with feature extraction on a single time series
- Extracting features from datasets of many instances
- Specifying custom labels for results tables
- Calling individual feature functions
- Parallel computing

# 📘 (1) Simple Feature Extraction

Simple feature extraction

In [7]:
data = get_dataset() # load the empirical1000 dataset from the pyhctsa utils
print(type(data), type(data[0]))
print(data[0])

Loading empirical1000 dataset...
Loaded dataset of 1000 time series.
<class 'list'> <class 'numpy.ndarray'>
[0.094578 0.66317  0.09869  ... 0.3235   0.14131  0.07839 ]

Instantiate a calculator with the full hctsa feature set

In [8]:
calc = FeatureCalculator()

Loaded 765 master operations.

Extract features from a single time-series instance

In [9]:
res = calc.extract(data[0])

Evaluating 765 partialed functions. Strap in!...
Training set size reduced from 5000 to 1000.
Time series (10000 > 5000) is too long for visibility graph. Analyzing the first 5000 samples.
Time series (10000 > 5000) is too long for visibility graph. Analyzing the first 5000 samples.
Feature extraction completed in 25.481 seconds.

`pyhctsa` will return a pandas DataFrame corresponding to the feature matrix:

In [10]:
res

,hrv_classic.pnn5,hrv_classic.pnn10,hrv_classic.pnn20,hrv_classic.pnn30,hrv_classic.pnn40,hrv_classic.lfhf,hrv_classic.vlf,hrv_classic.lf,hrv_classic.hf,hrv_classic.tri,...,surrogate_test_RP_99_o3.o3_p,surrogate_test_RP_99_o3.o3_zscore,surrogate_test_RP_99_o3.o3_f,surrogate_test_RP_99_o3.o3_mediqr,surrogate_test_RP_99_o3.o3_prank,surrogate_test_RP_99_tc3.tc3_p,surrogate_test_RP_99_tc3.tc3_zscore,surrogate_test_RP_99_tc3.tc3_f,surrogate_test_RP_99_tc3.tc3_mediqr,surrogate_test_RP_99_tc3.tc3_prank
instance,,,,,,,,,,,,,,,,,,,,,
ts_1,0.9959,0.992199,0.985699,0.978498,0.971897,0.472375,1.309191,3.884112,8.222524,3.941663,...,0.310222,1.014756,0.24434,0.803088,0.38,0.504674,0.667154,0.311034,0.52071,0.5

Here, each row corresponds to a time-series instance (in this case, a single row since features were extracted for a single time-series instance), and each column corresponds to a time-series feature.

### 📕 Multiple Time-Series Instances

Lets now extract features for the first 10 time-series instances in the `empirical1000` dataset. Since the input can be inhomogeneous (i.e., each time-series instance may differ in length), we must pass a list of numpy arrays (each array corresponding to a time-series instance):

In [ ]:
data10 = data[:10] # take the first 10 time-series instances from empirical1000
print(type(data10), type(data10[0]))

<class 'list'> <class 'numpy.ndarray'>

In [17]:
res10 = calc.extract(data10)

Evaluating 765 partialed functions. Strap in!...
Training set size reduced from 5000 to 1000.
Time series (10000 > 5000) is too long for visibility graph. Analyzing the first 5000 samples.
Time series (10000 > 5000) is too long for visibility graph. Analyzing the first 5000 samples.
Training set size reduced from 5000 to 1000.
Time series (10000 > 5000) is too long for visibility graph. Analyzing the first 5000 samples.
Time series (10000 > 5000) is too long for visibility graph. Analyzing the first 5000 samples.
Training set size reduced from 5000 to 1000.
Time series (10000 > 5000) is too long for visibility graph. Analyzing the first 5000 samples.
Time series (10000 > 5000) is too long for visibility graph. Analyzing the first 5000 samples.
This time series (N = 1000) is too short for StatAv(len,'500')
This time series (N = 1000) is too short for StatAv(len,'1000')
This time series (N = 1000) is too short for StatAv(len,'500')
This time series (N = 1000) is too short for StatAv(len,'1000')
This time series (N = 1000) is too short for StatAv(len,'500')
This time series (N = 1000) is too short for StatAv(len,'1000')
Training set size reduced from 2500 to 1000.
Training set size reduced from 2500 to 1000.
Training set size reduced from 2500 to 1000.
This time series (N = 1000) is too short for StatAv(len,'500')
This time series (N = 1000) is too short for StatAv(len,'1000')
Feature extraction completed in 110.717 seconds.

In [18]:
res10

,hrv_classic.pnn5,hrv_classic.pnn10,hrv_classic.pnn20,hrv_classic.pnn30,hrv_classic.pnn40,hrv_classic.lfhf,hrv_classic.vlf,hrv_classic.lf,hrv_classic.hf,hrv_classic.tri,...,surrogate_test_RP_99_o3.o3_p,surrogate_test_RP_99_o3.o3_zscore,surrogate_test_RP_99_o3.o3_f,surrogate_test_RP_99_o3.o3_mediqr,surrogate_test_RP_99_o3.o3_prank,surrogate_test_RP_99_tc3.tc3_p,surrogate_test_RP_99_tc3.tc3_zscore,surrogate_test_RP_99_tc3.tc3_f,surrogate_test_RP_99_tc3.tc3_mediqr,surrogate_test_RP_99_tc3.tc3_prank
instance,,,,,,,,,,,,,,,,,,,,,
ts_1,0.995900,0.992199,0.985699,0.978498,0.971897,0.472375,1.309191,3.884112,8.222524,3.941663,...,0.310222,1.014756,0.244340,0.803088,0.38,0.504674,0.667154,0.311034,0.520710,0.50
ts_2,0.997700,0.995100,0.989999,0.985299,0.978898,0.511508,1.318258,3.811640,7.451773,4.081633,...,0.266405,1.111380,0.205103,0.846807,0.26,0.110429,1.596268,0.126444,1.404623,0.16
ts_3,0.998100,0.995700,0.990399,0.985099,0.980798,0.447787,1.080018,3.619673,8.083463,4.697041,...,0.283312,1.072909,0.273922,0.699314,0.32,0.918023,-0.102924,0.988875,0.438207,0.52
ts_4,0.997998,0.995996,0.989990,0.984985,0.978979,0.290204,1.081005,3.087794,10.640085,5.494505,...,0.390920,-0.857951,0.302332,0.625428,0.42,0.928037,-0.090315,0.345178,0.066369,0.96
ts_5,0.995996,0.991992,0.988989,0.982983,0.978979,0.367925,0.759282,3.130879,8.509555,4.444444,...,0.719686,0.358879,0.339027,0.334623,0.74,0.151963,-1.432631,0.189344,0.953667,0.20
ts_6,0.994995,0.992993,0.986987,0.981982,0.979980,0.263391,1.283629,2.458678,9.334699,4.651163,...,0.113850,-1.581122,0.128105,1.119646,0.12,0.446594,-0.761105,0.284930,0.569959,0.50
ts_7,0.986797,0.974795,0.951990,0.932386,0.917383,0.392634,1.163540,2.901433,7.389659,1.456452,...,0.045830,-1.996957,0.081870,1.574702,0.08,0.004907,2.813081,0.000000,2.123994,0.04
ts_8,0.991198,0.980596,0.966993,0.954191,0.937588,0.438296,1.557289,3.013317,6.875065,2.024291,...,0.963951,-0.045195,0.387876,0.051869,0.92,0.017501,-2.376016,0.023726,1.666752,0.04
ts_9,0.996199,0.991798,0.982997,0.975395,0.967994,0.503558,1.227345,3.860633,7.666709,2.979738,...,0.956811,-0.054155,0.373726,0.043089,1.00,0.927223,0.091340,0.434251,0.177907,0.84
ts_10,0.708709,0.708709,0.708709,0.708709,0.708709,0.806538,1.113861,5.079354,6.297723,2.680965,...,0.856396,0.180964,0.332826,0.042178,1.00,0.053352,1.932065,0.065021,1.407653,0.10

By default, `pyhctsa` will assign a generic label to index each time-series instance (row) in the results table. For example, `ts_1` corresponds to the first time-series instance passed into the calculator, `ts_2` to the second, etc. To inspect the results for a specific instance (a feature vector), we can use the pandas method `.loc`:

In [19]:
# inspect the results for ts_1
res10.loc['ts_1']

hrv_classic.pnn5                       0.995900
hrv_classic.pnn10                      0.992199
hrv_classic.pnn20                      0.985699
hrv_classic.pnn30                      0.978498
hrv_classic.pnn40                      0.971897
                                         ...
surrogate_test_RP_99_tc3.tc3_p         0.504674
surrogate_test_RP_99_tc3.tc3_zscore    0.667154
surrogate_test_RP_99_tc3.tc3_f         0.311034
surrogate_test_RP_99_tc3.tc3_mediqr    0.520710
surrogate_test_RP_99_tc3.tc3_prank     0.500000
Name: ts_1, Length: 4580, dtype: float64

### 🏷 Custom time-series labels

If you would like to assign custom labels to each time-series instance, you can pass a list of strings along with the data when extracting features:

In [22]:
labels = [f'e1000_{x}' for x in range(1, 11)]
res10_labelled = calc.extract(data10[:10], labels=labels)

Evaluating 765 partialed functions. Strap in!...
Training set size reduced from 5000 to 1000.
Time series (10000 > 5000) is too long for visibility graph. Analyzing the first 5000 samples.
Time series (10000 > 5000) is too long for visibility graph. Analyzing the first 5000 samples.
Training set size reduced from 5000 to 1000.
Time series (10000 > 5000) is too long for visibility graph. Analyzing the first 5000 samples.
Time series (10000 > 5000) is too long for visibility graph. Analyzing the first 5000 samples.
Training set size reduced from 5000 to 1000.
Time series (10000 > 5000) is too long for visibility graph. Analyzing the first 5000 samples.
Time series (10000 > 5000) is too long for visibility graph. Analyzing the first 5000 samples.
This time series (N = 1000) is too short for StatAv(len,'500')
This time series (N = 1000) is too short for StatAv(len,'1000')
This time series (N = 1000) is too short for StatAv(len,'500')
This time series (N = 1000) is too short for StatAv(len,'1000')
This time series (N = 1000) is too short for StatAv(len,'500')
This time series (N = 1000) is too short for StatAv(len,'1000')
Training set size reduced from 2500 to 1000.
Training set size reduced from 2500 to 1000.
Training set size reduced from 2500 to 1000.
This time series (N = 1000) is too short for StatAv(len,'500')
This time series (N = 1000) is too short for StatAv(len,'1000')
Feature extraction completed in 105.509 seconds.

In [23]:
res10_labelled

,hrv_classic.pnn5,hrv_classic.pnn10,hrv_classic.pnn20,hrv_classic.pnn30,hrv_classic.pnn40,hrv_classic.lfhf,hrv_classic.vlf,hrv_classic.lf,hrv_classic.hf,hrv_classic.tri,...,surrogate_test_RP_99_o3.o3_p,surrogate_test_RP_99_o3.o3_zscore,surrogate_test_RP_99_o3.o3_f,surrogate_test_RP_99_o3.o3_mediqr,surrogate_test_RP_99_o3.o3_prank,surrogate_test_RP_99_tc3.tc3_p,surrogate_test_RP_99_tc3.tc3_zscore,surrogate_test_RP_99_tc3.tc3_f,surrogate_test_RP_99_tc3.tc3_mediqr,surrogate_test_RP_99_tc3.tc3_prank
instance,,,,,,,,,,,,,,,,,,,,,
e1000_1,0.995900,0.992199,0.985699,0.978498,0.971897,0.472375,1.309191,3.884112,8.222524,3.941663,...,0.310222,1.014756,0.244340,0.803088,0.38,0.504674,0.667154,0.311034,0.520710,0.50
e1000_2,0.997700,0.995100,0.989999,0.985299,0.978898,0.511508,1.318258,3.811640,7.451773,4.081633,...,0.266405,1.111380,0.205103,0.846807,0.26,0.110429,1.596268,0.126444,1.404623,0.16
e1000_3,0.998100,0.995700,0.990399,0.985099,0.980798,0.447787,1.080018,3.619673,8.083463,4.697041,...,0.283312,1.072909,0.273922,0.699314,0.32,0.918023,-0.102924,0.988875,0.438207,0.52
e1000_4,0.997998,0.995996,0.989990,0.984985,0.978979,0.290204,1.081005,3.087794,10.640085,5.494505,...,0.390920,-0.857951,0.302332,0.625428,0.42,0.928037,-0.090315,0.345178,0.066369,0.96
e1000_5,0.995996,0.991992,0.988989,0.982983,0.978979,0.367925,0.759282,3.130879,8.509555,4.444444,...,0.719686,0.358879,0.339027,0.334623,0.74,0.151963,-1.432631,0.189344,0.953667,0.20
e1000_6,0.994995,0.992993,0.986987,0.981982,0.979980,0.263391,1.283629,2.458678,9.334699,4.651163,...,0.113850,-1.581122,0.128105,1.119646,0.12,0.446594,-0.761105,0.284930,0.569959,0.50
e1000_7,0.986797,0.974795,0.951990,0.932386,0.917383,0.392634,1.163540,2.901433,7.389659,1.456452,...,0.045830,-1.996957,0.081870,1.574702,0.08,0.004907,2.813081,0.000000,2.123994,0.04
e1000_8,0.991198,0.980596,0.966993,0.954191,0.937588,0.438296,1.557289,3.013317,6.875065,2.024291,...,0.963951,-0.045195,0.387876,0.051869,0.92,0.017501,-2.376016,0.023726,1.666752,0.04
e1000_9,0.996199,0.991798,0.982997,0.975395,0.967994,0.503558,1.227345,3.860633,7.666709,2.979738,...,0.956811,-0.054155,0.373726,0.043089,1.00,0.927223,0.091340,0.434251,0.177907,0.84
e1000_10,0.708709,0.708709,0.708709,0.708709,0.708709,0.806538,1.113861,5.079354,6.297723,2.680965,...,0.856396,0.180964,0.332826,0.042178,1.00,0.053352,1.932065,0.065021,1.407653,0.10

Here, we can see that each time-series instance is now indexed by its custom label e.g., `e1000_1`, `e1000_2`, which we can now use to inspect results:

In [24]:
res10_labelled.loc['e1000_9']

hrv_classic.pnn5                       0.996199
hrv_classic.pnn10                      0.991798
hrv_classic.pnn20                      0.982997
hrv_classic.pnn30                      0.975395
hrv_classic.pnn40                      0.967994
                                         ...
surrogate_test_RP_99_tc3.tc3_p         0.927223
surrogate_test_RP_99_tc3.tc3_zscore    0.091340
surrogate_test_RP_99_tc3.tc3_f         0.434251
surrogate_test_RP_99_tc3.tc3_mediqr    0.177907
surrogate_test_RP_99_tc3.tc3_prank     0.840000
Name: e1000_9, Length: 4580, dtype: float64

----

# 🤖 (2) Additional Functionality

## ⚙️ Calling individual feature functions

While the `FeatureCalculator` massively simplifies the extraction of thousands of featues with a single line of code, `pyhctsa` also allows users to call individual feature functions from their respective modules, located in `pyhctsa.operations.<modlue_name>`.

In [34]:
import pkgutil
import pyhctsa.operations as ops
import inspect
mods = [m.name for m in pkgutil.iter_modules(ops.__path__, ops.__name__ + ".")]
print("\n".join(mods))

pyhctsa.operations.correlation
pyhctsa.operations.criticality
pyhctsa.operations.distribution
pyhctsa.operations.entropy
pyhctsa.operations.extreme_events
pyhctsa.operations.graph
pyhctsa.operations.hypothesis_tests
pyhctsa.operations.information
pyhctsa.operations.medical
pyhctsa.operations.model_fit
pyhctsa.operations.physics
pyhctsa.operations.pre_process
pyhctsa.operations.scaling
pyhctsa.operations.spectral
pyhctsa.operations.stationarity
pyhctsa.operations.surrogates
pyhctsa.operations.symbolic
pyhctsa.operations.wavelet

For example, we can call the rescaled auto-density (RAD) function by importing it from the `pychtsa.operations.criticality` module:

In [ ]:
from pyhctsa.operations.criticality import rad # import rad from the criticality module...

We can then call `rad` directly on our data, choosing whatever parameters we need. For details on what the function computes and how to configure it, refer to its docstring.

*NOTE:* Generic feature functions expect a 1D array-like input (a single time series). Also be careful when calling functions manually: make sure the data you pass in __matches the preprocessing assumptions for your use case__. In particular, decide explicitly whether you want to supply raw data or z-scored/standardized data as this choice can substantially influence the resulting feature values.

In [35]:
print(inspect.getdoc(rad))

Compute the Rescaled Auto-Density (RAD) feature of a time series.

The RAD is a metric for inferring the distance to criticality in a system,
designed to be robust to uncertainty in noise strength. It is calibrated using
experiments on the Hopf bifurcation with variable and unknown measurement noise.

This method was devised and implemented by Brendan Harris (@brendanjohnharris, GitHub, 2023).

References
----------
.. [1] Harris et al., "Tracking the Distance to Criticality in Systems with
    Unknown Noise", Phys. Rev. X 14, 031021 (2024)

Parameters
----------
x : array-like
    The input time series (1D array).
tau : int or str, optional
    The embedding and differencing delay, in units of the time step (default: 1).
    If a string, must be "tau", in which case the delay is set to the first
    crossing of the autocorrelation function.
centre : bool, optional
    Whether to center the time series at zero and take absolute values before analysis (default: True).

Returns
-------
float
    The RAD feature value, quantifying proximity to criticality.

In [55]:
rad_result = rad(data[0], tau=1, centre=True) # pass in the raw data (not z-scored)
print(rad_result)

-3.222181765905979

For feature functions which expect/assume a z-scored input, you can first pre-process the data using the `z_score` function:

In [51]:
from pyhctsa.utils import z_score

In [ ]:
z_score(data[0]) # z-score normalise the data along the time axis

array([-0.79396411,  2.16578483, -0.7725595 , ...,  0.39766653,
       -0.55070534, -0.87822913], shape=(10000,))

## 🏗️ Parallel Computing

Computing large feature sets across many time series can be computationally expensive. Since feature extraction is independent across individual time series, the task is naturally suited to parallelisation. `pyhctsa` supports parallel execution using the pathos library, distributing batches of time series across multiple worker processes to reduce overall runtime.

#### Setting up a local parallel distributor

In [ ]:
# import the LocalDistributor
from pyhctsa.distribute import LocalDistributor
dist = LocalDistributor(n_workers=8) # use up to the number of physical CPU cores available on the machine

To distribute feature computation, pass the distributor instance to the extract method:

In [50]:
calc = FeatureCalculator()
res_distributed = calc.extract(data10, distributor=dist)

Output()

Loaded 765 master operations.
Evaluating 765 partialed functions. Strap in!...

This time series (N = 1000) is too short for StatAv(len,'500')
This time series (N = 1000) is too short for StatAv(len,'1000')
This time series (N = 1000) is too short for StatAv(len,'500')
This time series (N = 1000) is too short for StatAv(len,'1000')

This time series (N = 1000) is too short for StatAv(len,'500')
This time series (N = 1000) is too short for StatAv(len,'1000')

This time series (N = 1000) is too short for StatAv(len,'500')
This time series (N = 1000) is too short for StatAv(len,'1000')

Training set size reduced from 2500 to 1000.

Training set size reduced from 2500 to 1000.

Training set size reduced from 2500 to 1000.

Training set size reduced from 5000 to 1000.

Training set size reduced from 5000 to 1000.

Training set size reduced from 5000 to 1000.

Time series (10000 > 5000) is too long for visibility graph. Analyzing the first 5000 samples.
Time series (10000 > 5000) is too long for visibility graph. Analyzing the first 5000 samples.
Time series (10000 > 5000) is too long for visibility graph. Analyzing the first 5000 samples.

Time series (10000 > 5000) is too long for visibility graph. Analyzing the first 5000 samples.
Time series (10000 > 5000) is too long for visibility graph. Analyzing the first 5000 samples.
Time series (10000 > 5000) is too long for visibility graph. Analyzing the first 5000 samples.

Feature extraction completed in 36.863 seconds.

Parallelisation introduces some overhead from process creation and inter-process communication, so speedups may be modest for very small datasets. However, for larger collections of time series, distributing the workload can substantially reduce total computation time. Even in this small example (10 time series), parallel execution reduced runtime by roughly a factor of three compared to sequential feature extraction.