In [1]:
from matlab import engine
from pyhctsa.operations.medical import hrv_classic
from pyhctsa.utils import get_dataset, z_score
import yaml
import itertools
import matlab
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, mean_squared_error, mean_absolute_percentage_error, r2_score, max_error, median_absolute_error
import importlib
from pyhctsa.operations.correlation import add_noise
import os
import joblib
import numpy as np
from collections import defaultdict
from scipy.stats import pearsonr
import pandas as pd
from scipy.stats import ks_2samp

In [2]:
data = get_dataset()

Loading empirical1000 dataset...
Loaded dataset of 1000 time series.

In [3]:
from pyhctsa.calculator import FeatureCalculator

In [4]:
calc = FeatureCalculator()

Loaded 773 master operations.

In [7]:
res = calc.extract(data[1])

Evaluating 773 partialed functions. Strap in!...
Feature extraction completed in 12.371 seconds.

In [ ]:
pd.read_csv('/Users/jmoo2880/Documents/pyhctsa/tests/validation/validation_results_HCTSA.csv').drop(columns=['Unnamed: 0']).to_csv('./')

,python_func,params,feature,matlab_func,python_module,corr,mae,mape,nan_count_py,nan_count_ml
0,autocorr,tau1_zscoreTrue,tau1_zscoreTrue,CO_AutoCorr,correlation,1.000000,8.426342e-17,2.783181e-16,0,0
1,autocorr,tau2_zscoreTrue,tau2_zscoreTrue,CO_AutoCorr,correlation,1.000000,6.546616e-17,2.932692e-16,0,0
2,autocorr,tau3_zscoreTrue,tau3_zscoreTrue,CO_AutoCorr,correlation,1.000000,6.912613e-17,8.545523e-16,0,0
3,autocorr,tau4_zscoreTrue,tau4_zscoreTrue,CO_AutoCorr,correlation,1.000000,6.064069e-17,7.992631e-16,0,0
4,autocorr,tau5_zscoreTrue,tau5_zscoreTrue,CO_AutoCorr,correlation,1.000000,5.928398e-17,4.155699e-16,0,0
...,...,...,...,...,...,...,...,...,...,...
4554,add_noise,ami_methodkraskov1_extra_param4_tauac_zscoreTrue,meanch,CO_AddNoise,correlation,0.999999,1.845457e-05,3.593742e-03,0,0
4555,add_noise,ami_methodkraskov1_extra_param4_tauac_zscoreTrue,ami_at_10,CO_AddNoise,correlation,1.000000,7.228673e-15,2.892876e-12,0,0
4556,add_noise,ami_methodkraskov1_extra_param4_tauac_zscoreTrue,ami_at_15,CO_AddNoise,correlation,1.000000,7.079697e-15,5.025278e-12,0,0
4557,add_noise,ami_methodkraskov1_extra_param4_tauac_zscoreTrue,pcrossmean,CO_AddNoise,correlation,0.999885,6.122449e-05,5.250000e-04,0,0
4558,add_noise,ami_methodkraskov1_extra_param4_tauac_zscoreTrue,firstUnder75,CO_AddNoise,correlation,0.999702,6.122449e-05,2.000000e-04,0,0

In [6]:
actual_feats = list(res.keys())

In [114]:
eng = engine.start_matlab()

In [115]:
s = eng.genpath('/Users/jmoo2880/Documents/hctsa')
eng.addpath(s, nargout=0)
eng.javaaddpath('/Users/jmoo2880/Documents/hctsa/Toolboxes/infodynamics-dist/infodynamics.jar', nargout=0)

In [86]:
eng.MF_hmm_fit(z_score(data[0]).reshape(-1, 1), 0.7, 3)

{'Mu_1': -0.45685483927667203,
 'Mu_2': -0.40375304314238025,
 'Mu_3': 1.4770771329239367,
 'meanMu': 0.20548975016829482,
 'rangeMu': 1.9339319722006088,
 'maxMu': 1.4770771329239367,
 'minMu': -0.45685483927667203,
 'Cov': 0.40016486455361583,
 'Pmeandiag': 0.3817669621681817,
 'stdmeanP': 0.2495910796387519,
 'maxP': 0.7681724537593038,
 'meanP': 0.3333333333333333,
 'stdP': 0.2752859688295598,
 'LLtrainpersample': -1.3336264039847492,
 'nit': 27.0,
 'LLtestpersample': -1.3404775109417033,
 'LLdifference': -0.006851106956954123}

In [342]:
validate_deterministic = joblib.load('/Users/jmoo2880/Documents/pyhctsa/validation/validation_deterministic.pkl')
validate_stochastic = joblib.load('/Users/jmoo2880/Documents/pyhctsa/validation/validation_stochastic.pkl')

In [343]:
validate_final = pd.concat([validate_deterministic, validate_stochastic]).drop_duplicates()

In [ ]:
#1889

In [344]:
validate_final = validate_final.drop(columns=['n_stochastic_series', 'ks_pass_frac'])

In [ ]:
# validate_final[validate_final['corr'] < 0.9].to_csv('lessthan0p9.csv')

In [161]:
p1 = joblib.load('/Users/jmoo2880/Documents/pyhctsa/validation/validation.pkl')
p2 = joblib.load('/Users/jmoo2880/Documents/pyhctsa/validation/validation2.pkl')
p3 = joblib.load('/Users/jmoo2880/Documents/pyhctsa/validation/validation3.pkl')
p4 = joblib.load('/Users/jmoo2880/Documents/pyhctsa/validation/validation4.pkl')
p5 = joblib.load('/Users/jmoo2880/Documents/pyhctsa/validation/validation5.pkl')
p6 = joblib.load('/Users/jmoo2880/Documents/pyhctsa/validation/validation6.pkl')
p7 = joblib.load('/Users/jmoo2880/Documents/pyhctsa/validation/validation7.pkl')
p8 = joblib.load('/Users/jmoo2880/Documents/pyhctsa/validation/validation8.pkl')
p9 = joblib.load('/Users/jmoo2880/Documents/pyhctsa/validation/validation9.pkl')
p10 = joblib.load('/Users/jmoo2880/Documents/pyhctsa/validation/validation10.pkl')
p11 = joblib.load('/Users/jmoo2880/Documents/pyhctsa/validation/validation11.pkl')
p12 = joblib.load('/Users/jmoo2880/Documents/pyhctsa/validation/validation12.pkl')
p13 = joblib.load('/Users/jmoo2880/Documents/pyhctsa/validation/validation13.pkl')

In [164]:
df_combined = pd.concat([p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12]).drop_duplicates()
#df_combined[(df_combined['corr'] < 0.9) & (df_combined['python_module'] == 'correlation')]
df_combined.shape

(4569, 12)

In [314]:
len([f for f in actual_feats if f.startswith('embed_pca')])

65

In [315]:
len([f for f in actual_feats if f.startswith('embed_pca')])

65

In [151]:
pickles = [f for f in os.listdir('./') if ('.pkl') in f]
dfs = []
for p in pickles:
    l = joblib.load(os.path.join('.', p))
    dfs.append(l)

In [152]:
df_final = pd.concat(dfs)
df_final

,python_func,params,feature,matlab_func,python_module,corr,mae,mape,ks_pass_frac,n_stochastic_series,nan_count_py,nan_count_ml
0,automutual_info_stats,est_methodgaussian_max_tau40.0_zscoreTrue,ami13,IN_AutoMutualInfoStats,information,1.0,3.518984e-14,8.972151e-11,NaN,0,0,0
1,automutual_info_stats,est_methodgaussian_max_tau40.0_zscoreTrue,ami19,IN_AutoMutualInfoStats,information,1.0,2.026502e-14,3.131826e-07,NaN,0,0,0
2,automutual_info_stats,est_methodgaussian_max_tau40.0_zscoreTrue,mami,IN_AutoMutualInfoStats,information,1.0,9.093015e-14,1.173891e-12,NaN,0,7,6
3,automutual_info_stats,est_methodgaussian_max_tau40.0_zscoreTrue,amiac1,IN_AutoMutualInfoStats,information,1.0,6.787132e-13,3.211759e-12,NaN,0,7,6
4,automutual_info_stats,est_methodgaussian_max_tau40.0_zscoreTrue,ami6,IN_AutoMutualInfoStats,information,1.0,1.655500e-13,5.143352e-10,NaN,0,7,2
...,...,...,...,...,...,...,...,...,...,...,...,...
523,motif_two,binarize_howmedian_zscoreTrue,hhh,SB_MotifTwo,symbolic,1.0,7.926992e-17,4.572691e-17,NaN,0,0,0
524,motif_two,binarize_howmedian_zscoreTrue,dddd,SB_MotifTwo,symbolic,1.0,0.000000e+00,0.000000e+00,NaN,0,0,0
525,motif_two,binarize_howmedian_zscoreTrue,u,SB_MotifTwo,symbolic,1.0,0.000000e+00,0.000000e+00,NaN,0,0,0
526,binary_stretch,stretch_whatlseq1_zscoreTrue,stretch_whatlseq1_zscoreTrue,SB_BinaryStretch,symbolic,1.0,0.000000e+00,0.000000e+00,NaN,0,0,0
527,binary_stretch,stretch_whatlseq0_zscoreTrue,stretch_whatlseq0_zscoreTrue,SB_BinaryStretch,symbolic,1.0,0.000000e+00,0.000000e+00,NaN,0,0,0

In [ ]:
dfs

In [146]:
in_df1_not_df2 = df_final[~df_final['python_func'].isin(df_combined['python_func'])]
in_df1_not_df2

Empty DataFrame
Columns: [python_func, params, feature, matlab_func, python_module, corr, mae, mape, ks_pass_frac, n_stochastic_series, nan_count_py, nan_count_ml]
Index: []

In [51]:
eng.BF_ResetSeed('default', nargout=0)
noise = np.asarray(eng.randn(1, float(len(data[0])))).reshape(-1)
matlab_res = eng.CO_AddNoise(z_score(data[0]), 1, 'quantiles', 10, 'default', nargout=1)
python_res = add_noise(z_score(data[0]), 1, 'quantiles', 10, 0, noise)

In [52]:
python_res

{'pdec': np.float64(0.5510204081632653),
 'meanch': np.float64(7.476384702512112e-06),
 'ac1': np.float64(0.5136329535076094),
 'ac2': np.float64(0.1621494207939138),
 'firstUnder75': np.float64(0.12244897959183673),
 'firstUnder50': np.float64(3.0),
 'firstUnder25': np.float64(3.0),
 'ami_at_5': np.float64(0.004604890932556121),
 'ami_at_10': np.float64(0.0037202645432859176),
 'ami_at_15': np.float64(0.0048520942896682975),
 'ami_at_20': np.float64(0.004410009566490332),
 'pcrossmean': np.float64(0.2857142857142857),
 'fitexpa': np.float64(0.004158783607033425),
 'fitexpb': np.float64(0.04360403313370635),
 'fitexpr2': np.float64(0.13156782337008577),
 'fitexpadjr2': np.float64(0.09461326266242986),
 'fitexprmse': np.float64(0.00044081544926519926),
 'fitlina': np.float64(0.0001946843623694318),
 'fitlinb': np.float64(0.004151138318733727),
 'linfit_mse': np.float64(1.941707887036103e-07)}

In [89]:
df_combined[df_combined['python_module'] == 'medical']

,python_func,params,feature,matlab_func,python_module,corr,mae,mape,ks_pass_frac,n_stochastic_series,nan_count_py,nan_count_ml
1508,hrv_classic,zscoreTrue,pnn20,MD_hrv_classic,medical,1.000000,0.000000e+00,0.000000e+00,NaN,0,0,0
1509,hrv_classic,zscoreTrue,lfhf,MD_hrv_classic,medical,1.000000,1.754341e-07,1.281112e-11,NaN,0,0,0
1510,hrv_classic,zscoreTrue,pnn10,MD_hrv_classic,medical,1.000000,0.000000e+00,0.000000e+00,NaN,0,0,0
1511,hrv_classic,zscoreTrue,vlf,MD_hrv_classic,medical,1.000000,1.107822e-14,4.286283e-14,NaN,0,0,0
1512,hrv_classic,zscoreTrue,SD1,MD_hrv_classic,medical,1.000000,2.448330e-13,5.061622e-16,NaN,0,0,0
1513,hrv_classic,zscoreTrue,lf,MD_hrv_classic,medical,1.000000,6.903742e-15,5.714110e-13,NaN,0,0,0
1514,hrv_classic,zscoreTrue,hf,MD_hrv_classic,medical,1.000000,7.982915e-15,2.776206e-12,NaN,0,0,0
1515,hrv_classic,zscoreTrue,pnn30,MD_hrv_classic,medical,1.000000,0.000000e+00,0.000000e+00,NaN,0,0,0
1516,hrv_classic,zscoreTrue,SD2,MD_hrv_classic,medical,1.000000,7.289032e-13,6.724326e-16,NaN,0,0,0
1517,hrv_classic,zscoreTrue,pnn5,MD_hrv_classic,medical,1.000000,0.000000e+00,0.000000e+00,NaN,0,0,0
1518,hrv_classic,zscoreTrue,tri,MD_hrv_classic,medical,1.000000,0.000000e+00,0.000000e+00,NaN,0,0,0
1519,hrv_classic,zscoreTrue,pnn40,MD_hrv_classic,medical,1.000000,0.000000e+00,0.000000e+00,NaN,0,0,0
1520,pnn,zscoreFalse,pnn20,MD_pNN,medical,1.000000,0.000000e+00,0.000000e+00,NaN,0,0,0
1521,pnn,zscoreFalse,pnn10,MD_pNN,medical,1.000000,0.000000e+00,0.000000e+00,NaN,0,0,0
1522,pnn,zscoreFalse,pnn80,MD_pNN,medical,1.000000,0.000000e+00,0.000000e+00,NaN,0,0,0
1523,pnn,zscoreFalse,pnn70,MD_pNN,medical,1.000000,0.000000e+00,0.000000e+00,NaN,0,0,0
1524,pnn,zscoreFalse,pnn30,MD_pNN,medical,1.000000,0.000000e+00,0.000000e+00,NaN,0,0,0
1525,pnn,zscoreFalse,pnn50,MD_pNN,medical,1.000000,0.000000e+00,0.000000e+00,NaN,0,0,0
1526,pnn,zscoreFalse,pnn100,MD_pNN,medical,1.000000,0.000000e+00,0.000000e+00,NaN,0,0,0
1527,pnn,zscoreFalse,pnn5,MD_pNN,medical,1.000000,0.000000e+00,0.000000e+00,NaN,0,0,0
1528,pnn,zscoreFalse,pnn60,MD_pNN,medical,1.000000,0.000000e+00,0.000000e+00,NaN,0,0,0
1529,pnn,zscoreFalse,pnn90,MD_pNN,medical,1.000000,0.000000e+00,0.000000e+00,NaN,0,0,0
1530,pnn,zscoreFalse,pnn40,MD_pNN,medical,1.000000,0.000000e+00,0.000000e+00,NaN,0,0,0
1531,raw_hrv_meas,zscoreFalse,SD2,MD_rawHRVmeas,medical,1.000000,8.558551e-08,7.877031e-16,NaN,0,0,0
1532,raw_hrv_meas,zscoreFalse,tri20,MD_rawHRVmeas,medical,0.999999,3.799486e-04,4.185281e-05,NaN,0,0,0
1533,raw_hrv_meas,zscoreFalse,SD1,MD_rawHRVmeas,medical,1.000000,7.940121e-09,4.976863e-16,NaN,0,0,0
1534,raw_hrv_meas,zscoreFalse,tri10,MD_rawHRVmeas,medical,0.999999,1.270772e-04,2.165939e-05,NaN,0,0,0
1535,raw_hrv_meas,zscoreFalse,trisqrt,MD_rawHRVmeas,medical,0.968009,2.493893e+00,1.535680e-01,NaN,0,0,0
0,pol_var,D3_d1.0_zscoreTrue,D3_d1.0_zscoreTrue,MD_polvar,medical,0.999976,1.899111e-04,7.857069e-04,NaN,0,0,0
1,pol_var,D4_d1.0_zscoreTrue,D4_d1.0_zscoreTrue,MD_polvar,medical,0.999984,8.107314e-05,5.551159e-04,NaN,0,0,0
2,pol_var,D5_d1.0_zscoreTrue,D5_d1.0_zscoreTrue,MD_polvar,medical,0.999982,8.382929e-05,8.851465e-04,NaN,0,0,0
3,pol_var,D6_d1.0_zscoreTrue,D6_d1.0_zscoreTrue,MD_polvar,medical,0.999981,6.166041e-05,7.523238e-04,NaN,0,0,0
4,pol_var,D3_d0.5_zscoreTrue,D3_d0.5_zscoreTrue,MD_polvar,medical,0.999976,1.582245e-04,7.877171e-04,NaN,0,0,0
5,pol_var,D4_d0.5_zscoreTrue,D4_d0.5_zscoreTrue,MD_polvar,medical,0.999982,8.645043e-05,5.795814e-04,NaN,0,0,0
6,pol_var,D5_d0.5_zscoreTrue,D5_d0.5_zscoreTrue,MD_polvar,medical,0.999980,6.981477e-05,7.506379e-04,NaN,0,0,0
7,pol_var,D6_d0.5_zscoreTrue,D6_d0.5_zscoreTrue,MD_polvar,medical,0.999992,3.554418e-05,4.913717e-04,NaN,0,0,0
8,pol_var,D3_d0.1_zscoreTrue,D3_d0.1_zscoreTrue,MD_polvar,medical,0.999880,2.224218e-04,7.924130e-04,NaN,0,0,0
9,pol_var,D4_d0.1_zscoreTrue,D4_d0.1_zscoreTrue,MD_polvar,medical,0.999941,1.119116e-04,5.469643e-04,NaN,0,0,0
10,pol_var,D5_d0.1_zscoreTrue,D5_d0.1_zscoreTrue,MD_polvar,medical,0.999929,9.015520e-05,5.624372e-04,NaN,0,0,0
11,pol_var,D6_d0.1_zscoreTrue,D6_d0.1_zscoreTrue,MD_polvar,medical,0.999933,8.589151e-05,7.106708e-04,NaN,0,0,0

In [73]:
in_df1_not_df2

,python_func,params,feature,matlab_func,python_module,corr,mae,mape,ks_pass_frac,n_stochastic_series,nan_count_py,nan_count_ml
0,surprise,coarse_grain_methodquantile_memory5.0_num_grou...,mean,FC_Surprise,symbolic,0.998456,0.011543,0.064793,0.006000,1000,0,0
1,surprise,coarse_grain_methodquantile_memory5.0_num_grou...,uq,FC_Surprise,symbolic,0.983773,0.022118,0.067218,0.922000,1000,0,0
2,surprise,coarse_grain_methodquantile_memory5.0_num_grou...,min,FC_Surprise,symbolic,0.869718,0.004775,0.013498,0.985972,998,0,2
3,surprise,coarse_grain_methodquantile_memory5.0_num_grou...,median,FC_Surprise,symbolic,0.986593,0.018076,0.055342,0.939000,1000,0,0
4,surprise,coarse_grain_methodquantile_memory5.0_num_grou...,std,FC_Surprise,symbolic,0.990970,0.012364,0.056141,0.005000,1000,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
35,pol_var,D6_d0.5_zscoreTrue,D6_d0.5_zscoreTrue,MD_polvar,medical,0.999992,0.000036,0.000491,NaN,0,0,0
36,pol_var,D3_d0.1_zscoreTrue,D3_d0.1_zscoreTrue,MD_polvar,medical,0.999880,0.000222,0.000792,NaN,0,0,0
37,pol_var,D4_d0.1_zscoreTrue,D4_d0.1_zscoreTrue,MD_polvar,medical,0.999941,0.000112,0.000547,NaN,0,0,0
38,pol_var,D5_d0.1_zscoreTrue,D5_d0.1_zscoreTrue,MD_polvar,medical,0.999929,0.000090,0.000562,NaN,0,0,0
39,pol_var,D6_d0.1_zscoreTrue,D6_d0.1_zscoreTrue,MD_polvar,medical,0.999933,0.000086,0.000711,NaN,0,0,0

In [256]:
l = joblib.load('/Users/jmoo2880/Documents/pyhctsa/validation/symbolic_validation.pkl')
#l2 = np.load('/Users/jmoo2880/Documents/pyhctsa/validation/correlation_raw_outputs.npz', allow_pickle=True)['arr_0'].tolist()

In [257]:
l

,python_func,params,feature,matlab_func,python_module,corr,mae,mape,ks_pass_frac,n_stochastic_series,nan_count_py,nan_count_ml
0,transition_matrix,how_to_cgquantile_num_groups2_tau1_zscoreTrue,T2,SB_TransitionMatrix,symbolic,1.0,0.000000e+00,0.000000e+00,NaN,0,0,0
1,transition_matrix,how_to_cgquantile_num_groups2_tau1_zscoreTrue,maxeig,SB_TransitionMatrix,symbolic,1.0,1.282308e-17,2.551514e-17,NaN,0,0,0
2,transition_matrix,how_to_cgquantile_num_groups2_tau1_zscoreTrue,sumdiagcov,SB_TransitionMatrix,symbolic,1.0,1.317689e-18,1.660158e-17,NaN,0,0,0
3,transition_matrix,how_to_cgquantile_num_groups2_tau1_zscoreTrue,maxeigcov,SB_TransitionMatrix,symbolic,1.0,5.389822e-18,5.551096e-17,NaN,0,0,0
4,transition_matrix,how_to_cgquantile_num_groups2_tau1_zscoreTrue,T1,SB_TransitionMatrix,symbolic,1.0,0.000000e+00,0.000000e+00,NaN,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
523,motif_two,binarize_howmedian_zscoreTrue,hhh,SB_MotifTwo,symbolic,1.0,7.926992e-17,4.572691e-17,NaN,0,0,0
524,motif_two,binarize_howmedian_zscoreTrue,dddd,SB_MotifTwo,symbolic,1.0,0.000000e+00,0.000000e+00,NaN,0,0,0
525,motif_two,binarize_howmedian_zscoreTrue,u,SB_MotifTwo,symbolic,1.0,0.000000e+00,0.000000e+00,NaN,0,0,0
526,binary_stretch,stretch_whatlseq1_zscoreTrue,stretch_whatlseq1_zscoreTrue,SB_BinaryStretch,symbolic,1.0,0.000000e+00,0.000000e+00,NaN,0,0,0
527,binary_stretch,stretch_whatlseq0_zscoreTrue,stretch_whatlseq0_zscoreTrue,SB_BinaryStretch,symbolic,1.0,0.000000e+00,0.000000e+00,NaN,0,0,0

In [253]:
l[l['corr'] < 0.9]['params'].iloc[0]

'num_surrs99_surr_methRP_the_test_statfmmi_zscoreTrue'

In [247]:
l#l[l['corr'] < 0.9]

,python_func,params,feature,matlab_func,python_module,corr,mae,mape,ks_pass_frac,n_stochastic_series,nan_count_py,nan_count_ml
0,surrogate_test,num_surrs99_surr_methRP_the_test_statami1_zsco...,ami_prank,SD_SurrogateTest,surrogates,0.992897,0.023085,8.727912e-02,0.553,1000,0,0
1,surrogate_test,num_surrs99_surr_methRP_the_test_statami1_zsco...,ami_f,SD_SurrogateTest,surrogates,0.946939,0.052531,2.311096e+11,0.392,1000,0,0
2,surrogate_test,num_surrs99_surr_methRP_the_test_statami1_zsco...,ami_zscore,SD_SurrogateTest,surrogates,0.993439,33.317074,1.926721e+00,0.250,1000,0,0
3,surrogate_test,num_surrs99_surr_methRP_the_test_statami1_zsco...,ami_p,SD_SurrogateTest,surrogates,0.992157,0.023060,2.016216e+00,0.357,1000,0,0
4,surrogate_test,num_surrs99_surr_methRP_the_test_statami1_zsco...,ami_mediqr,SD_SurrogateTest,surrogates,0.986975,47.033138,2.750174e-01,0.283,1000,0,0

In [150]:
l2['max_tau20_what_methodols_zscoreTrue::pac_10']

{'py': array([-2.69430917e-02, -5.66765521e-03, -5.15847848e-03, -1.39283737e-02,
         1.97851960e-02,  2.38720624e-02, -1.49505295e-02,  1.61674860e-02,
        -2.30512475e-02,  8.43559017e-03, -2.81388830e-02,  5.49566166e-03,
        -1.94824140e-02,  7.39812593e-03,  7.37962048e-03, -6.84136127e-04,
         2.69888287e-02,  6.64441261e-03,  1.19450909e-02,  8.49886830e-03,
        -2.89891147e-02, -1.16183845e-02,  4.50600387e-02, -2.03856653e-02,
         9.25440813e-02, -9.79557142e-03, -1.13929482e-02, -1.30267009e-02,
         2.13650171e-02, -1.70168423e-02, -3.25701962e-02, -3.01873271e-03,
        -3.14565609e-02, -3.35699669e-04,  8.50598944e-03,  2.61889102e-02,
         7.28531930e-03,  2.15480554e-02,  1.30942477e-02,  6.33840327e-02,
         8.44544653e-03, -2.73122250e-02,  4.98039622e-01, -3.29204184e-02,
        -1.18209509e-03, -2.76355743e-02,  1.90284144e-05, -2.52516455e-02,
        -7.00251573e-02, -7.27830187e-03,  7.01859910e-03, -1.85110325e-02,
        -9.71183046e-03, -3.83022684e-03, -8.95792002e-03, -3.34112682e-03,
         6.94130500e-03,  6.79176815e-03, -7.86660853e-03, -1.47763370e-02,
        -7.55819756e-02, -2.75098076e-02, -4.24124457e-03, -5.70302417e-02,
         7.00011669e-03,  1.65078992e-02, -2.69539680e-03, -2.49954103e-01,
         8.71956691e-03, -9.81478714e-03, -1.93901577e-02,  1.54610031e-01,
        -1.42900389e-01, -1.67063267e-01, -4.07037318e-01,  7.15021599e-02,
        -2.41538858e-01, -6.04164788e-02,  3.92066112e-02, -4.75258697e-02,
        -2.52653963e-01, -1.48900441e-01, -4.44744591e-01, -4.06659349e-01,
         2.01482865e-02, -4.47966904e-02, -1.36814126e-01, -5.08355841e-01,
        -5.26045206e-01, -1.62743591e-01,  2.10208759e-01,  3.78755091e-01,
        -6.62756584e-02,  5.05923400e-02, -3.83745783e-02,  2.77470451e-02,
        -1.42674003e-03, -1.40574478e-01,  2.41241311e-01, -1.86004693e-01,
        -2.91504942e-01, -3.14030696e-01,  2.60824987e-02, -7.59912485e-03,
        -1.37554297e-02, -1.30483445e-01, -1.79660720e-02, -2.54385876e-01,
        -3.72564104e-02, -8.20473835e-03, -5.40353546e-01,  1.91480868e-02,
        -3.05483551e-01,  2.13042040e-01, -4.80253684e-03,  1.36194087e-01,
         1.96578836e-02,  3.03844115e-02, -2.59469509e-02, -2.53850167e-01,
        -2.60840983e-01, -2.42865472e-01,  1.59542054e-01, -1.96940660e-01,
         3.29580784e-01, -1.23402083e-02, -1.12940826e-01, -4.16772445e-01,
         1.10799144e-01, -3.01333283e-01, -1.42607798e-01,  2.74699334e-01,
         2.39831445e-01, -2.38900877e-01,  3.89265672e-02, -7.04112284e-02,
         5.16812018e-02,  1.19754670e-04, -9.43283175e-03,  1.18279883e-03,
        -7.69821273e-02, -7.83860515e-03, -1.33570795e-02, -8.50236814e-03,
        -1.77762300e-02,  3.85256152e-03, -1.02158033e-03,  1.37963436e-02,
        -1.37456835e-02, -6.61529274e-03, -1.58505403e-03,  2.93838097e-03,
        -1.41562083e-01, -1.44876079e-01,  1.86740664e-03,  1.73149669e-03,
        -1.47830408e-01, -9.16007875e-02, -2.07120290e-01, -1.47359343e-01,
         9.01962515e-02, -1.45882841e-01, -1.67789107e-02,  1.40802059e-03,
         2.85793708e-01,  2.72185931e-01,  2.41962875e-01,  5.90920600e-02,
        -2.25009653e-01,  2.79486514e-02,  8.15684532e-02,  1.03619648e-02,
         1.76668955e-01,  5.42816534e-02, -5.28360657e-02, -7.49979780e-02,
         3.55412561e-03,  1.41426045e-02, -1.54899005e-01,  1.42857143e-01,
         6.97648768e-02,  1.22010777e-16, -3.97789968e-02, -2.54611828e-02,
        -1.10452172e-02,  4.93885051e-02,  1.42857143e-01, -3.88852125e-02,
        -2.62444034e-02, -4.15331989e-02,  1.96707940e-02,  3.31514513e-03,
         3.16660061e-02, -9.16535775e-03, -5.04381358e-02,  3.03115517e-03,
        -2.11098931e-02,  9.90659642e-04, -2.93292224e-01, -1.33649484e-02,
        -4.17981840e-01, -2.94092656e-01, -3.14387090e-01, -2.86142211e-01,
        -1.02994748e-02, -2.69036446e-01, -2.84199532e-01, -3.25514962e-02,
         3.87847314e-02,  5.25769287e-03, -3.01459927e-01, -2.73359166e-01,
        -7.81281556e-01,  1.03368180e-02, -8.01578904e-01, -7.86619454e-01,
        -8.03729944e-01, -2.54920072e-02, -5.36168559e-02, -6.81517981e-03,
        -7.85787707e-01, -1.23758930e-01, -2.12346192e-02, -1.26342662e-01,
        -6.51291126e-02, -2.51283204e-02, -1.57630090e-02, -2.46242324e-02,
        -9.23954180e-03, -1.22277210e-02, -1.97455412e-03, -1.05106889e-02,
         2.24637629e-02,  6.44221036e-03, -2.98932349e-02,  1.79237710e-02,
         2.16789820e-02,  2.17068503e-02, -1.22873398e-01,  6.37851395e-03,
         6.15938609e-03, -7.52309906e-02,  2.03624239e-02, -2.13694231e-02,
         7.44191031e-02,  2.49899156e-02,  8.57040292e-02,  5.69878993e-03,
        -1.46792997e-01, -3.10939381e-02, -1.37627315e-02,  5.35728857e-03,
        -6.84445136e-03,  1.00297037e-02,  1.04764467e-01,  8.88346934e-03,
         1.91490716e-02, -1.10688416e-02,  2.74508097e-02,  4.85519404e-01,
        -3.51428692e-02,  2.36596678e-01, -5.39888547e-02, -4.33293602e-04,
         3.20745824e-02,  8.02435599e-03, -4.91969229e-03,  4.05236468e-02,
        -1.65874075e-02,  4.30449075e-03, -5.71165909e-03, -6.24710387e-03,
        -1.67634118e-02, -4.30877590e-03,  9.33063999e-03, -1.60770714e-02,
         3.85564817e-03, -9.62614686e-03,  8.78780583e-02,  5.05712680e-02,
        -5.18854110e-02, -2.37186338e-02,  1.81268960e-14, -2.76801527e-02,
        -1.85399747e-02, -1.25000000e-01,  8.54040152e-03, -2.01522899e-02,
         7.61730937e-02, -3.39254733e-14, -4.87825581e-02, -1.17228222e-01,
        -7.03337138e-02,  9.40741318e-03,  1.00111897e-02, -9.89691724e-03,
         4.43275049e-04, -3.74091178e-02, -8.24358480e-03,  1.11989378e-02,
        -3.47542000e-02, -1.35631458e-02,  1.24279270e-02,  6.28183897e-02,
         1.44787744e-02,  7.40938496e-02, -4.07078924e-02,  7.56542903e-02,
        -6.18920751e-02, -7.80037968e-02, -2.61631893e-02, -3.83783819e-02,
         1.25456381e-04, -2.34145913e-02,  5.83594640e-02, -2.07831623e-04,
        -1.37913215e-02, -4.34830454e-02,  2.43331257e-02, -9.20994080e-02,
        -3.76188104e-04, -5.92757223e-03, -3.48291053e-02, -3.32304172e-02,
        -3.01961376e-03,  1.06244636e-01,  6.24031504e-02,  8.81692396e-03,
         1.40872830e-02, -5.05025354e-02, -3.39564787e-02,  9.24459738e-02,
         8.16961919e-02,  2.17217441e-01, -3.95324987e-01, -6.52409979e-01,
        -2.49437300e-01, -4.11731763e-01, -4.35653700e-01,  6.09647602e-02,
        -3.80213329e-01, -3.88023144e-01, -2.95653566e-01,  2.43436322e-02,
        -8.10851746e-02,  5.17753189e-01, -6.16320716e-02, -2.32394692e-01,
        -4.62112166e-02, -4.50541397e-03, -5.44307973e-02, -2.22788944e-01,
         1.40584855e-02, -6.58430138e-02,  7.14447025e-03, -1.46344670e-01,
        -1.46123049e-01, -1.58163211e-01, -3.25584081e-02, -4.68080524e-02,
         9.18936066e-02, -1.44222697e-01, -9.44862530e-03, -6.30828289e-02,
        -5.80129081e-02, -6.40688386e-02, -8.59702225e-02, -1.89908894e-01,
        -1.01648933e-02,  4.72736853e-02, -9.81586814e-02, -4.28124343e-02,
        -1.47330695e-01,  9.36684494e-02, -6.44400539e-02, -2.94838053e-02,
         2.40822750e-02,  5.42176977e-03,  5.68107432e-03, -1.62588759e-01,
        -9.08538887e-02, -1.37830251e-01, -2.15412447e-01, -1.43850088e-01,
        -3.06299520e-01, -6.38725007e-04, -2.66336783e-01,  1.88250683e-01,
        -1.22531336e-01,  1.69929021e-01, -1.18844527e-01, -6.28271864e-02,
         3.38583791e-01, -3.65182885e-02, -2.15928478e-01, -2.36646255e-01,
        -3.39137529e-01, -3.36151794e-01, -5.18639964e-01, -4.21910864e-02,
        -7.57304302e-01, -6.55175842e-01, -3.87931994e-01, -1.34802668e-02,
         2.19003234e-01, -1.32714900e-02, -2.68300661e-01,  3.44166807e-02,
        -3.50916968e-01,  2.08897858e-02,  3.93832529e-02, -2.99202731e-02,
        -4.61522918e-02, -1.34595526e-01,  1.23037720e-01, -2.54188875e-02,
         4.26746513e-02,  1.25413768e-01,  3.04071093e-02, -6.08131165e-02,
         6.99134010e-02,  5.89006821e-02, -4.86196915e-03,  5.34791728e-02,
         8.05699394e-02, -2.90744050e-02, -5.21568856e-02, -2.76594568e-03,
         5.46939474e-02, -2.28480096e-02,  2.01222126e-02,  3.88454798e-01,
         6.44290710e-02, -4.37230948e-02,  8.22060826e-02,  6.61780303e-02,
         3.87545679e-02,  1.41086472e-01,  4.54550714e-02,  4.68716520e-03,
        -1.82688489e-02,  1.24888673e-03, -5.32636857e-02, -2.88128808e-02,
        -1.84835937e-01, -1.03902867e-03, -8.37055847e-02, -2.51762068e-02,
         3.50434625e-01, -6.69217380e-02,  3.57458263e-01,  3.28050753e-01,
         9.97016320e-02, -2.85356884e-01, -2.52403873e-01, -2.18453764e-02,
         1.00663161e-01,  2.66098282e-02, -8.16113426e-02,  3.85156388e-02,
        -8.35228872e-02, -6.74586965e-04,  2.62255647e-03,  1.12030835e-01,
        -4.37159485e-02, -1.85734174e-02,  5.68942041e-02,  1.85400704e-02,
         2.66841203e-03, -2.80790331e-01, -4.65727720e-03,  1.22679474e-02,
        -4.12961996e-02,  9.74867092e-02,  2.25500264e-03, -6.96849701e-02,
        -1.89859441e-02, -1.65699264e-02, -1.35982078e-02,  6.56151142e-02,
        -5.33903361e-02,  1.81983107e-01, -7.10225748e-02,  3.83681053e-01,
        -1.80937112e-02, -4.20307453e-01,  7.16299541e-02, -3.94927356e-01,
        -2.89598164e-02, -6.25630107e-03, -4.06351368e-01,  1.51379687e-01,
         4.38736856e-01,  2.78882130e-01,  7.71904371e-02,  2.94187292e-02,
        -2.80143589e-02, -1.00134657e-01, -4.34061369e-02, -1.49250829e-01,
        -1.17456988e-01, -6.01137133e-02, -7.31959896e-02, -2.04685437e-01,
        -2.82174633e-01,  1.10222354e-01,  3.35563362e-01,  3.97338601e-01,
         4.04663931e-01, -2.17717592e-01, -5.77443197e-01, -5.48884475e-01,
        -1.99078601e-01, -2.20913924e-01,  3.15440063e-02,  3.61176112e-02,
        -1.00091150e-01, -1.98659910e-01, -1.65420359e-01,  3.73051281e-01,
        -1.58897026e-01,  3.79351107e-01,  1.75099147e-01,  1.28120144e-01,
        -1.74843699e-01, -1.34742918e-01,  1.00931235e-01, -4.61518570e-02,
        -9.15777936e-02, -2.50315991e-01, -3.04193362e-01, -2.56729984e-01,
         5.36889674e-02,  3.18024315e-01, -2.52088489e-01, -3.42565157e-02,
         1.47208662e-01, -2.53676373e-01,  2.07578299e-01, -2.88313717e-02,
         2.19431986e-01, -1.23085422e-01, -2.02058059e-01,  1.31110053e-02,
        -2.85618721e-01, -3.49580601e-01, -2.90868530e-01, -9.67629682e-02,
        -3.45827230e-01, -1.46584283e-01, -2.87702160e-01, -2.93831611e-01,
         1.87647903e-01, -3.75124854e-01, -2.87933809e-01, -3.70316184e-01,
         8.54695822e-03,  8.95876146e-02, -3.61827817e-01,  1.07353897e-01,
         1.31723760e-01, -3.63121605e-01,  3.86137983e-01,  2.39562718e-01,
        -3.75424982e-01, -1.29645401e-01, -3.77239612e-02, -3.10430458e-02,
         3.72735817e-02, -5.05237705e-01, -2.97476504e-01, -6.65578694e-03,
        -7.10411322e-03,  4.13756840e-03, -1.25783403e-01, -2.32174768e-01,
        -1.61917196e-01,  3.26811178e-01,  4.23430923e-01, -4.57768899e-01,
         9.91176058e-03, -1.99532230e-01,  1.32230877e-01, -3.40912015e-01,
        -1.10937586e-01,  1.03528232e-01, -1.49823727e-01,  9.83201032e-02,
        -2.60961092e-01,  1.03503053e-01, -4.37278144e-02, -2.29975164e-01,
         3.26031457e-02, -1.74687440e-01, -1.48323052e-01, -3.70885622e-02,
         1.40451978e-01, -3.61842519e-02, -8.93732013e-03,  6.40254632e-04,
        -4.42906118e-02,  3.10818754e-01,  6.74654981e-02,  3.36807374e-01,
        -2.96224270e-01, -3.09260875e-02,  1.11617241e-01,  8.63953378e-02,
        -4.32246234e-02,  1.50023829e-01, -1.76207262e-01,  2.31416736e-02,
         4.08095415e-02,  1.60612409e-01,  8.18845672e-02,  2.17792620e-01,
         2.02893694e-01,  1.70480831e-02,  1.94350412e-02,  3.10787239e-01,
         2.00718989e-01,  4.14999396e-02,  7.75217146e-02, -1.59196356e-02,
         2.21736818e-02, -4.58618709e-04, -7.11087758e-02, -3.46160178e-02,
         4.69141689e-02,  1.49064878e-03,  2.53013613e-02,  3.69822987e-05,
        -2.58207898e-03,  9.08093424e-03, -1.81670436e-02,  9.63977794e-04,
         4.90604648e-02,  2.30534494e-03,  4.08321783e-02,  2.68238871e-02,
         1.06129125e-02, -2.93804325e-02, -4.60885302e-02, -4.35429124e-01,
         3.35627139e-02,  1.98755704e-03, -4.30779096e-02,  2.02881512e-02,
         1.70863932e-02,  2.23410236e-13, -4.52523547e-02, -8.65075708e-02,
         8.67532563e-02, -2.40574659e-01, -4.76331909e-02,  9.13989524e-02,
        -1.72796065e-02,  3.24857306e-01,  1.81052989e-01, -9.86964181e-02,
        -5.85683807e-02,  4.73643931e-01, -3.29760398e-02, -1.14832984e-01,
        -1.19944354e-02, -1.16742773e-02, -1.40050053e-02, -1.23639819e-03,
        -1.38071981e-02,  1.06664571e-02, -4.94762805e-02,  3.14345779e-03,
         2.65734626e-02,  5.38369896e-02, -2.84870486e-02, -3.49962696e-02,
         5.45931190e-02, -1.02671619e-01,  3.04384680e-02,  3.92662513e-03,
        -4.86035952e-01,  3.25717582e-02,  3.41636801e-02, -1.53981345e-01,
        -3.47286470e-01, -1.05543509e-01, -1.35168391e-01, -3.09371536e-02,
         6.81743604e-02, -2.21240056e-01, -3.31805996e-01,  5.36566494e-02,
         5.34299549e-02, -6.53955709e-02, -1.42659674e-01, -1.12391719e-01,
        -3.16752924e-02, -5.04317116e-02, -5.58804324e-02,  3.79806693e-02,
        -9.80236593e-02,  7.85988095e-02, -1.29037256e-01,  2.56626433e-02,
         3.27109877e-02,  1.02726511e-01,  8.99607502e-02,  8.71506121e-02,
         1.31420226e-01,  3.27482969e-02,  4.98779858e-03, -6.54922059e-02,
        -4.96918534e-02, -6.42523781e-02, -2.59217304e-02, -4.08751979e-02,
         3.27897667e-02, -8.07666875e-02, -6.02272407e-02,  1.42548324e-02,
         5.67428209e-02, -1.97996493e-02,  2.45510791e-02,  4.52551425e-02,
        -1.78657213e-02,  4.66811586e-02,  9.15553531e-03,  1.82477627e-01,
        -1.48008337e-03,  2.22961324e-03, -5.54114561e-02, -2.50379240e-02,
         4.94557797e-02, -2.97482392e-02,  3.17364637e-02,  1.79253927e-02,
        -5.29778265e-02,  8.89864866e-03,  7.25897424e-03, -3.68005474e-02,
         2.04270861e-02, -1.29976378e-01, -8.98670297e-02, -9.85413763e-02,
        -1.60799642e-01,  3.60802028e-02, -5.22266259e-02,  2.29224621e-02,
        -1.85239029e-01,  3.90181604e-02, -1.32123367e-01, -1.71291336e-01,
         5.20497061e-03, -8.90463725e-02, -7.46366705e-02, -7.65027251e-02,
        -1.46592037e-01, -8.39180314e-02,  1.70096970e-01,  6.42113557e-02,
        -2.95697791e-02,  1.27785940e-02, -1.22469202e-03, -3.39080205e-02,
        -1.80487013e-02,  3.08401530e-03, -1.50572839e-01, -5.58435668e-03,
         1.02751950e-01,  1.29400854e-02,  7.98690630e-03, -9.21475230e-02,
        -1.11612665e-01, -1.68699466e-01, -4.30983801e-02, -1.02102591e-01,
        -1.47391262e-01,  8.84843482e-02,  2.03511888e-02, -3.06397863e-02,
        -1.47810564e-02, -4.46446759e-02,  1.88841731e-02, -8.81964053e-03,
         1.78444563e-02,  3.58465748e-02,  5.16266946e-02,  1.65780846e-01,
         4.34989184e-02, -1.35167406e-01, -7.79996042e-02,  1.02944041e-02,
        -1.07329804e-01,  5.78317486e-03,  1.53218715e-02, -4.23163247e-02,
         2.15944437e-02, -7.70271981e-03, -1.14360397e-02, -8.73880789e-02,
        -7.86983166e-03, -2.56148086e-02,  3.33009200e-02,  2.28256505e-02,
         3.61133088e-02, -7.23817817e-02,  1.02748434e-01, -3.14694372e-02,
         2.24520470e-02, -1.03978120e-01, -4.01170902e-02, -3.80050858e-02,
        -7.18724852e-02, -1.23320784e-01, -1.09887714e-01, -4.41275207e-02,
        -7.10053229e-02,  2.90776748e-02,  4.18026939e-02,  9.87292120e-02,
         1.18046958e-01,  3.72393503e-02, -8.10236412e-02,  1.46146980e-01,
         5.07864365e-02,  3.29631656e-02, -1.52692726e-03, -3.41021813e-02,
         7.36881342e-02,  3.00553099e-02,  8.96291945e-03,  1.10207806e-01,
         4.57346038e-02,  8.03064232e-02,  2.70262927e-02, -2.90970965e-02,
        -9.27445296e-03, -1.57660920e-01,  2.57721222e-02, -4.91103491e-02,
        -6.77043933e-04, -4.12896005e-03,  5.45497648e-02,  1.28663020e-02,
         2.47253436e-02, -2.49125360e-02,  3.40841664e-02,  1.57990415e-02,
         5.27156219e-02, -2.66872932e-02,  5.27284628e-02, -7.26776080e-03,
         6.20950457e-02,  6.66821969e-02,  4.05703034e-02,  5.46950282e-02,
         3.69934993e-03,  1.13037182e-02,  1.66608671e-02,  3.47005979e-02,
         2.82286535e-02,  5.35590574e-02,  4.30615937e-02,  7.58676280e-02,
         5.85556017e-02,  1.73550067e-02,  2.34694989e-02,  1.18385124e-01,
         8.88209313e-03,  3.93184178e-02,  3.48857830e-03,  8.69844579e-02,
         9.93454031e-02,  1.70670499e-01,  2.58999257e-01,  2.96873047e-01,
         2.57848376e-01, -8.76479118e-02, -1.28808861e-01, -1.32884139e-01,
        -1.69301706e-01, -9.79305405e-02, -3.08903339e-02, -1.46236828e-02,
         1.00570489e-01,  7.59928185e-02, -3.59955611e-01,  3.62153237e-02,
         9.77751352e-02, -1.49348189e-01,  6.27640405e-04,  1.40840744e-02,
        -2.34315117e-02, -5.56349773e-02, -1.04771540e-02, -8.81633002e-02,
        -8.68415347e-03,  1.46703041e-02, -3.93719792e-02, -1.09064365e-01,
        -5.57767811e-03, -4.97128339e-02, -8.31292329e-02, -7.15622177e-03,
        -2.00154281e-02, -2.50353808e-01, -7.54026248e-02, -6.26039414e-05,
        -3.54835727e-01, -2.41771816e-02, -2.46937193e-01, -3.51735185e-01,
        -9.26638123e-02, -2.68943587e-01, -3.50214433e-01, -1.89625589e-01,
        -2.56342798e-01, -3.70849451e-01, -2.97116888e-01, -3.32404399e-01,
        -4.02816766e-01, -2.46305426e-01, -1.98669034e-01, -4.39921922e-03,
        -9.10326249e-03,  6.36721728e-02, -2.18583029e-01, -1.26079893e-02,
        -1.20154381e-02,  5.51325351e-02, -9.97795780e-03, -9.39136135e-02,
         2.76278391e-02,  6.06072510e-02, -7.78185837e-02, -4.11431227e-02,
         4.40556176e-02, -1.97067214e-02, -8.82165517e-02, -4.52054455e-02,
        -3.15769410e-02, -2.80865834e-02, -2.59950652e-02,  1.04609437e-02,
        -3.27710210e-02,  1.00713029e-01,  8.96244636e-02,  2.42257745e-02,
         2.93270689e-02, -3.96248713e-02,  1.52595974e-02,  1.15502182e-02,
         2.31238935e-02, -1.28191956e-01,  6.77047680e-02,  5.41247236e-02,
        -4.31641093e-02, -8.01801225e-02, -7.02513978e-02, -2.53574292e-02,
        -1.79262024e-02, -2.07970041e-01, -1.52509926e-01,  2.20498633e-03,
        -5.50085600e-02, -8.14937152e-03, -5.61596444e-03,  5.48728962e-02,
        -7.80240594e-02,  1.46150065e-02, -2.81129571e-02,  3.92114594e-02,
         5.19921029e-02, -3.29732292e-02,  3.68588776e-02, -1.41212836e-02,
         3.26348512e-02, -9.91493858e-04,  2.84867754e-02,  7.54891870e-02,
         8.66511368e-03, -6.75020923e-04, -6.35495345e-02,  6.31251770e-02,
         4.34411403e-02,  2.23873553e-02, -5.89721856e-02,  8.22045655e-02,
         2.90984557e-03,  6.83518302e-02,  6.11844959e-02,  2.89204996e-02,
         1.02773524e-01,  3.03351004e-01,  6.65276059e-02,  4.88496164e-02,
        -2.03727551e-01, -2.54956305e-02, -1.25229393e-01,  9.39505036e-02]),
 'mat': array([-3.30342867e-02, -6.02427602e-03, -5.48538838e-03, -1.44224171e-02,
         1.97509114e-02,  2.59734086e-02, -1.53683150e-02,  1.62252608e-02,
        -2.32757859e-02,  8.52945979e-03, -2.86246095e-02,  3.76461878e-03,
        -2.07364398e-02,  7.34689663e-03,  7.84930000e-03, -6.27690633e-03,
         2.83975434e-02,  6.36665019e-03,  1.18595724e-02,  8.50519348e-03,
        -2.65802850e-02, -2.01907753e-03,  4.62324651e-02, -2.03840139e-02,
         9.35634420e-02, -9.79053370e-03, -6.45471918e-03, -9.87554425e-03,
         2.44516147e-02, -6.83448496e-04, -3.25710909e-02, -3.01767519e-03,
        -2.62360674e-02, -2.69223854e-03,  8.63245953e-03,  2.61103565e-02,
         7.24350706e-03,  2.46811559e-02,  1.52176123e-02,  6.33127337e-02,
         8.87513011e-03, -2.76803575e-02, -4.59055685e-01, -2.70770555e-02,
        -1.14220159e-03, -3.07519815e-02, -2.05159711e-04, -2.55499462e-02,

In [145]:
l[l['corr'] < 0.9]

,python_func,params,feature,matlab_func,python_module,corr,mae,mape,ks_pass_frac,n_stochastic_series,nan_count_py,nan_count_ml
2,partial_autocorr,max_tau20_what_methodols_zscoreTrue,pac_9,CO_PartialAutoCorr,correlation,0.021606,2.856192e+21,8.568576e+21,NaN,0,0,0
3,partial_autocorr,max_tau20_what_methodols_zscoreTrue,pac_8,CO_PartialAutoCorr,correlation,0.005260,5.251405e+10,1.660211e+26,NaN,0,0,0
4,partial_autocorr,max_tau20_what_methodols_zscoreTrue,pac_5,CO_PartialAutoCorr,correlation,0.651409,1.448167e-02,8.351796e+11,NaN,0,0,0
6,partial_autocorr,max_tau20_what_methodols_zscoreTrue,pac_7,CO_PartialAutoCorr,correlation,-0.005056,2.876961e+10,6.783608e+25,NaN,0,0,0
7,partial_autocorr,max_tau20_what_methodols_zscoreTrue,pac_10,CO_PartialAutoCorr,correlation,-0.006737,1.724036e+27,7.764006e+42,NaN,0,0,0
8,partial_autocorr,max_tau20_what_methodols_zscoreTrue,pac_6,CO_PartialAutoCorr,correlation,0.086225,1.105796e+08,2.211592e+08,NaN,0,0,0

In [44]:
dataset = get_dataset(which='e1000')

Loading empirical1000 dataset...
Loaded dataset of 1000 time series.

In [194]:
from pyhctsa.operations.correlation import compare_min_ami

In [198]:
compare_min_ami(z_score(dataset[0]), 'std1', num_bins=[2, 3, 4])

{'min': np.float64(2.0),
 'max': np.float64(3.0),
 'range': np.float64(1.0),
 'median': np.float64(3.0),
 'mean': np.float64(2.6666666666666665),
 'std': np.float64(0.5773502691896258),
 'nunique': 2,
 'mode': np.float64(3.0),
 'modef': np.float64(0.6666666666666666),
 'conv4': np.float64(2.6666666666666665),
 'nlocmax': 0}

In [213]:
eng.CO_CompareMinAMI(z_score(dataset[0]).reshape(-1,1).tolist(), 'std1', matlab.double([2, 3, 4]))

Error using min
First input array is an invalid data type.

Error in CO_HistogramAMI (line 95)
        if min(y) < -1
           ^^^^^^
Error in CO_CompareMinAMI (line 78)
        amis(j) = CO_HistogramAMI(y,tauRange(j),binMethod,numBins(i));
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

MatlabExecutionError:
  File /Users/jmoo2880/Documents/hctsa/Operations/CO_HistogramAMI.m, line 95, in CO_HistogramAMI

  File /Users/jmoo2880/Documents/hctsa/Operations/CO_CompareMinAMI.m, line 78, in CO_CompareMinAMI
First input array is an invalid data type.

In [45]:
eng = engine.start_matlab()
s = eng.genpath('/Users/jmoo2880/Documents/hctsa')
eng.addpath(s, nargout=0)
eng.javaaddpath('/Users/jmoo2880/Documents/hctsa/Toolboxes/infodynamics-dist/infodynamics.jar', nargout=0)

In [46]:
def _flatten(d, prefix=""):
    """Nested struct -> {dotted_key: scalar}."""
    flat = {}
    for k, v in d.items():
        key = f"{prefix}.{k}" if prefix else k
        if isinstance(v, dict):
            flat.update(_flatten(v, key))
        else:
            flat[key] = v
    return flat


def _distribution_parity(py_dist, mat_dist):
    """Compare two per-series seed distributions for one feature."""
    py_dist = np.asarray(py_dist, float); py_dist = py_dist[np.isfinite(py_dist)]
    mat_dist = np.asarray(mat_dist, float); mat_dist = mat_dist[np.isfinite(mat_dist)]
    out = {
        "py":  np.mean(py_dist)  if py_dist.size  else np.nan,   # seed-averaged -> corr path
        "mat": np.mean(mat_dist) if mat_dist.size else np.nan,
        "std_py":  np.std(py_dist,  ddof=1) if py_dist.size  > 1 else np.nan,
        "std_mat": np.std(mat_dist, ddof=1) if mat_dist.size > 1 else np.nan,
    }
    if py_dist.size >= 2 and mat_dist.size >= 2:
        if np.ptp(py_dist) == 0 and np.ptp(mat_dist) == 0:
            out["ks_p"] = 1.0 if np.isclose(py_dist[0], mat_dist[0]) else 0.0
        else:
            out["ks_p"] = ks_2samp(py_dist, mat_dist).pvalue
    else:
        out["ks_p"] = np.nan
    return out

In [47]:
def generate_test_cases(yaml_file):
    """Expand a YAML config into a flat list of (suite_name, settings, param_set).

    Each test case may contain scalars, lists, or `!range [start, stop, step]`
    values; range/list values are expanded via Cartesian product so every
    parameter combination becomes its own case.
    """
    yaml.add_constructor("!range", lambda loader, node: range(*loader.construct_sequence(node)))

    with open(yaml_file, "r") as f:
        config = yaml.full_load(f)

    cases = []
    for suite_name, settings in config["functions"].items():
        for case in settings["test_cases"]:
            keys, values = zip(*case.items())

            # Wrap each value so itertools.product can iterate uniformly.
            expanded_values = [
                list(v) if isinstance(v, range) else [v]
                for v in values
            ]

            for combination in itertools.product(*expanded_values):
                param_set = dict(zip(keys, combination))
                cases.append((suite_name, settings, param_set))

    return cases


# ----------------------------------------------------------------------------
# Shared conversion / normalization helpers
# ----------------------------------------------------------------------------
def _to_matlab_column(arr):
    """Convert a 1-D array-like into an N×1 matlab.double.

    hctsa stores every time series as a column vector. matlab.double on a flat
    list produces a 1×N row, which silently broadcasts in any feature that
    combines `y` with an internally-built column (e.g. `q - y` in
    EX_MovingThreshold). Reshaping to (-1, 1) before tolist() yields
    [[v], [v], ...], which matlab reads as N×1.
    """
    col = np.asarray(arr, dtype=float).reshape(-1, 1)
    return matlab.double(col.tolist())


def _to_matlab_row(arr):
    """Convert a 1-D array-like into a 1×N matlab.double.

    For the rare function that explicitly wants a row vector. Opt in per-suite
    via `matlab_orientation: row` in the YAML; the default is column.
    """
    row = np.asarray(arr, dtype=float).reshape(1, -1)
    return matlab.double(row.tolist())


def _coerce_scalar(v):
    """Coerce Python scalars to MATLAB-friendly types.

    The MATLAB engine maps a Python int -> int64 and a Python float -> double.
    int64 is contagious in MATLAB arithmetic: any expression touching it returns
    int64 with integer rounding, so e.g. `1/int64(2)` -> 1 rather than 0.5. That
    silently corrupts things like `ones(numStates,1)/numStates` initializations.
    hctsa numeric args are effectively always doubles, so coerce ints to float.
    Leave bools (MATLAB logical) and everything non-numeric (strings) untouched.
    """
    if isinstance(v, bool):
        return v
    if isinstance(v, int):
        return float(v)
    return v


def _normalize(val):
    """Recursively convert MATLAB types / nested structs to plain Python types."""
    if isinstance(val, (matlab.double, matlab.single, matlab.int32, matlab.int64)):
        val = np.array(val).squeeze()
        return float(val) if val.ndim == 0 else val
    if isinstance(val, dict):
        return {k: _normalize(v) for k, v in val.items()}
    if isinstance(val, (np.ndarray, list)):
        val = np.array(val).squeeze()
        return float(val) if val.ndim == 0 else val
    return val


# ----------------------------------------------------------------------------
# Single parity test
# ----------------------------------------------------------------------------
def test_matlab_parity(matlab_engine, data, suite_name, settings, params):
    run_args = params.copy()
    should_zscore = run_args.pop("zscore", False)
    should_abs = run_args.pop("abs", False)

    test_data = z_score(data) if should_zscore else data.copy()
    if should_abs:
        test_data = np.abs(test_data)

    # Orientation of the time series handed to MATLAB. Default column (N×1),
    # which is what hctsa expects; opt into row (1×N) per-suite when needed.
    orientation = settings.get("matlab_orientation", "column")
    mat_data = (_to_matlab_row(test_data) if orientation == "row"
                else _to_matlab_column(test_data))

    arg_map = settings.get("arg_map", {})

    is_stochastic = settings.get("stochastic", False)
    seed_param = settings.get("seed_param", "random_seed")
    n_seeds = settings.get("n_seeds", 30) if is_stochastic else 1

    # A fixed seed in the YAML case shouldn't leak into the run or the case name.
    run_args.pop(seed_param, None)

    base_name_parts = []
    for k, v in sorted(params.items()):
        if k == seed_param:
            continue
        v_clean = str(v).translate(str.maketrans("", "", " []'"))
        base_name_parts.append(f"{k}{v_clean}")
    base_name = "_".join(base_name_parts)

    module = importlib.import_module(f"pyhctsa.operations.{settings['python_module']}")
    op_func = getattr(module, settings["python_func"])
    func_name = settings["matlab_func"]

    def _build_positional():
        mat_kwargs = {}
        for pk, pv in run_args.items():
            mat_name = arg_map.get(pk, pk)
            if isinstance(pv, list):
                mat_kwargs[mat_name] = matlab.double(pv)
            else:
                # Coerce int -> float so a Python int doesn't become MATLAB
                # int64 and poison downstream arithmetic.
                mat_kwargs[mat_name] = _coerce_scalar(pv)

        # MATLAB-only fixed args (e.g. extrap=[]) that the Python port doesn't
        # accept. Keyed by the MATLAB arg name; these never reach op_func, so
        # they don't pollute the Python call -- they only fill positional slots
        # so later args don't shift into the wrong place.
        for mat_name, val in settings.get("matlab_extra_args", {}).items():
            if isinstance(val, list):
                mat_kwargs[mat_name] = matlab.double(val)   # [] -> MATLAB empty
            else:
                mat_kwargs[mat_name] = _coerce_scalar(val)

        positional = [mat_data]
        for arg_name in settings.get("matlab_signature", []):
            if arg_name == "y" or arg_name == arg_map.get(seed_param, seed_param):
                continue  # seed handled via rng(), never positionally
            if arg_name in mat_kwargs:
                positional.append(mat_kwargs[arg_name])
        return positional

    def _run_once(seed):
        """One paired evaluation. Returns (py_res|None, mat_res|None, err|None)."""
        py_extra = {seed_param: seed} if seed is not None else {}
        py_res = _normalize(op_func(test_data, **run_args, **py_extra))

        if seed is not None:
            # Control randperm by seeding MATLAB's global stream. Relies on
            # BF_ResetSeed([]) being a no-op (default arg) -- verify for your hctsa.
            matlab_engine.eval(f"rng({int(seed)},'twister');", nargout=0)
        try:
            mat_res = _normalize(getattr(matlab_engine, func_name)(*_build_positional(), nargout=1))
        except matlab.engine.MatlabExecutionError as exc:
            msg = str(exc).strip()
            return py_res, None, (msg.splitlines()[-1] if msg else "MatlabExecutionError")
        return py_res, mat_res, None

    results = {}

    # ---- deterministic path (original behaviour) ----
    if not is_stochastic:
        py_res, mat_res, err = _run_once(None)
        if not isinstance(py_res, dict):
            py_res = {"output": py_res}

        def fill_nan(py_obj, key=""):
            if isinstance(py_obj, dict):
                for k, v in py_obj.items():
                    fill_nan(v, f"{key}.{k}" if key else k)
            else:
                results[f"{base_name}::{key}"] = {"py": py_obj, "mat": np.nan}

        if err is not None:
            print(f"MATLAB error for {base_name} (recording NaN): {err}")
            fill_nan(py_res)
            return results

        if not isinstance(mat_res, dict):
            mat_res = {"output": mat_res}

        def flatten_and_pair(py_obj, mat_obj, key=""):
            if isinstance(py_obj, dict) and isinstance(mat_obj, dict):
                for k in set(py_obj) | set(mat_obj):
                    nk = f"{key}.{k}" if key else k
                    if k not in py_obj:
                        results[f"{base_name}::{nk}"] = {"error": "Missing in Python"}
                    elif k not in mat_obj:
                        results[f"{base_name}::{nk}"] = {"error": "Missing in MATLAB"}
                    else:
                        flatten_and_pair(py_obj[k], mat_obj[k], nk)
            else:
                results[f"{base_name}::{key}"] = {"py": py_obj, "mat": mat_obj}

        flatten_and_pair(py_res, mat_res)
        return results

    # ---- stochastic path: many seeds, compare distributions ----
    seed_py, seed_mat, last_err = [], [], None
    for s in range(n_seeds):
        py_res, mat_res, err = _run_once(s)
        if err is not None:
            last_err = err
            continue
        if not isinstance(py_res, dict):
            py_res = {"output": py_res}
        if not isinstance(mat_res, dict):
            mat_res = {"output": mat_res}
        seed_py.append(_flatten(py_res))
        seed_mat.append(_flatten(mat_res))

    if not seed_py:  # every seed failed in MATLAB (e.g. series too short)
        print(f"MATLAB error for {base_name} (all seeds, NaN): {last_err}")
        py_once = op_func(test_data, **run_args)
        py_once = py_once if isinstance(py_once, dict) else {"output": py_once}
        for k in _flatten(_normalize(py_once)):
            results[f"{base_name}::{k}"] = {"py": np.nan, "mat": np.nan, "ks_p": np.nan}
        return results

    all_keys = set().union(*(set(d) for d in seed_py), *(set(d) for d in seed_mat))
    for k in all_keys:
        py_dist  = [d[k] for d in seed_py  if k in d]
        mat_dist = [d[k] for d in seed_mat if k in d]
        if not py_dist:
            results[f"{base_name}::{k}"] = {"error": "Missing in Python"}
        elif not mat_dist:
            results[f"{base_name}::{k}"] = {"error": "Missing in MATLAB"}
        else:
            results[f"{base_name}::{k}"] = _distribution_parity(py_dist, mat_dist)
    return results


# ----------------------------------------------------------------------------
# Correlation aggregation across the dataset
# ----------------------------------------------------------------------------
def _safe_correlation(py, mat, atol=1e-8):
    """Pearson r with fallbacks for the degenerate cases common in TS features."""
    if py.size < 2:
        return np.nan  # not enough finite points to correlate
    if np.allclose(py, mat, atol=atol):
        return 1.0  # identical constants: variance is zero but parity is perfect
    try:
        r, _ = pearsonr(py, mat)
    except ValueError:
        return np.nan  # fallback for remaining edge cases
    return r


def get_correlations(eng, data, params):
    records, raw_outputs = [], {}
    for suite_name, settings, param_dict in params:
        aggregator = defaultdict(lambda: {"py": [], "mat": [], "ks_p": []})
        for series in data:
            res = test_matlab_parity(eng, series, suite_name, settings, param_dict)
            for full_key, values in res.items():
                if "error" in values:
                    print(f"Skipping {full_key}: {values['error']}")
                    continue
                aggregator[full_key]["py"].append(values["py"])
                aggregator[full_key]["mat"].append(values["mat"])
                if "ks_p" in values and np.isfinite(values["ks_p"]):
                    aggregator[full_key]["ks_p"].append(values["ks_p"])

        for feature_name, lists in aggregator.items():
            py_vec  = np.asarray(lists["py"],  dtype=float)
            mat_vec = np.asarray(lists["mat"], dtype=float)
            raw_outputs[feature_name] = {"py": py_vec, "mat": mat_vec}

            mask = np.isfinite(py_vec) & np.isfinite(mat_vec)
            py_valid, mat_valid = py_vec[mask], mat_vec[mask]

            r = _safe_correlation(py_valid, mat_valid)
            if py_valid.size >= 1:
                mae = mean_absolute_error(py_valid, mat_valid)
                mape = mean_absolute_percentage_error(py_valid, mat_valid)
            else:
                mae = mape = np.nan

            ks = lists["ks_p"]
            ks_pass_frac = float(np.mean(np.asarray(ks) > 0.05)) if ks else np.nan

            fname = feature_name.split(":")[2]
            if fname == 'output':
                fname = feature_name.split(":")[0]
            records.append({
                "python_func": settings["python_func"],
                "params": feature_name.split(":")[0],
                "feature": fname,
                "matlab_func": settings["matlab_func"],
                "python_module": settings["python_module"],
                "corr": r, "mae": mae, "mape": mape,
                "ks_pass_frac": ks_pass_frac,
                "n_stochastic_series": len(ks) if ks else 0,
                "nan_count_py": int(np.sum(~np.isfinite(py_vec))),
                "nan_count_ml": int(np.sum(~np.isfinite(mat_vec))),
            })
            print(f"{settings['python_func']}-{feature_name}: corr={r:.4f} ks_pass={ks_pass_frac}")
    return pd.DataFrame(records), raw_outputs

In [6]:
# def generate_test_cases(yaml_file):
#     with open(yaml_file, "r") as f:
#         yaml.add_constructor('!range', lambda l, n: range(*l.construct_sequence(n)))
#         config = yaml.full_load(f)
#     cases = []
#     for suite_name, settings in config['functions'].items():
#         for case in settings['test_cases']:
#             keys, values = zip(*case.items())
#             expanded_values = []
#             for v in values:
#                 if isinstance(v, range):
#                     expanded_values.append(list(v))
#                 else:
#                     expanded_values.append([v]) # Wrap scalar/list in list for product
            
#             for combination in itertools.product(*expanded_values):
#                 param_set = dict(zip(keys, combination))
#                 cases.append((suite_name, settings, param_set))
#     return cases

In [7]:
# def _to_matlab_column(arr):
#     """Convert a 1-D array-like into an N×1 matlab.double.
 
#     hctsa stores every time series as a column vector. matlab.double on a flat
#     list produces a 1×N row, which silently broadcasts in any feature that
#     combines `y` with an internally-built column (e.g. `q - y`). Reshaping to
#     (-1, 1) before tolist() yields [[v], [v], ...], which matlab reads as N×1.
#     """
#     col = np.asarray(arr, dtype=float).reshape(-1, 1)
#     return matlab.double(col.tolist())
 
 
# def _normalize(val):
#     """Recursively convert MATLAB types / nested structs to plain Python types."""
#     if isinstance(val, (matlab.double, matlab.single, matlab.int32, matlab.int64)):
#         val = np.array(val).squeeze()
#         return float(val) if val.ndim == 0 else val
#     if isinstance(val, dict):
#         return {k: _normalize(v) for k, v in val.items()}
#     if isinstance(val, (np.ndarray, list)):
#         val = np.array(val).squeeze()
#         return float(val) if val.ndim == 0 else val
#     return val
 
 
# def test_matlab_parity(matlab_engine, data, suite_name, settings, params):
#     """Execute a single parity test between Python and MATLAB.
 
#     Returns:
#         results (dict): keys are feature names, values are dicts containing
#                         {'py': val, 'mat': val}, or {'error': reason}.
#     """
#     run_args = params.copy()
#     should_zscore = run_args.pop("zscore", False)
#     should_abs = run_args.pop("abs", False)
 
#     test_data = z_score(data) if should_zscore else data.copy()
#     if should_abs:
#         test_data = np.abs(test_data)
 
#     # MATLAB wants an N×1 column; Python keeps the native 1-D array.
#     mat_data = _to_matlab_column(test_data)
 
#     # Map Python param names to MATLAB param names.
#     arg_map = settings.get("arg_map", {})
#     mat_kwargs = {}
#     for param_key, param_val in run_args.items():
#         mat_name = arg_map.get(param_key, param_key)
#         if isinstance(param_val, list):
#             mat_kwargs[mat_name] = matlab.double(param_val)
#         else:
#             mat_kwargs[mat_name] = param_val
 
#     # Build positional args from the declared MATLAB signature (data is always 1st).
#     mat_positional_args = [mat_data]
#     for arg_name in settings.get("matlab_signature", []):
#         if arg_name == "y":
#             continue
#         if arg_name in mat_kwargs:
#             mat_positional_args.append(mat_kwargs[arg_name])
 
#     # Run both implementations.
#     module = importlib.import_module(f"pyhctsa.operations.{settings['python_module']}")
#     op_func = getattr(module, settings["python_func"])
#     py_res = _normalize(op_func(test_data, **run_args))
 
#     func_name = settings["matlab_func"]
#     mat_res = _normalize(getattr(matlab_engine, func_name)(*mat_positional_args, nargout=1))
 
#     # Build a stable base name from sorted params: "a0.1_b0.1".
#     base_name_parts = []
#     for k, v in sorted(params.items()):
#         v_clean = str(v).translate(str.maketrans("", "", " []'"))
#         base_name_parts.append(f"{k}{v_clean}")
#     base_name = "_".join(base_name_parts)
 
#     results = {}
 
#     def flatten_and_pair(py_obj, mat_obj, current_key=""):
#         """Drill into matching struct keys to produce scalar/array comparison pairs."""
#         if isinstance(py_obj, dict) and isinstance(mat_obj, dict):
#             for k in set(py_obj) | set(mat_obj):
#                 new_key = f"{current_key}.{k}" if current_key else k
#                 if k not in py_obj:
#                     results[f"{base_name}::{new_key}"] = {"error": "Missing in Python"}
#                 elif k not in mat_obj:
#                     results[f"{base_name}::{new_key}"] = {"error": "Missing in MATLAB"}
#                 else:
#                     flatten_and_pair(py_obj[k], mat_obj[k], new_key)
#         else:
#             results[f"{base_name}::{current_key}"] = {"py": py_obj, "mat": mat_obj}
 
#     # Wrap bare scalars so everything flows through the same struct-walking path.
#     if not isinstance(py_res, dict):
#         py_res = {"output": py_res}
#     if not isinstance(mat_res, dict):
#         mat_res = {"output": mat_res}
 
#     flatten_and_pair(py_res, mat_res)
#     return results

In [8]:
# def _safe_correlation(py, mat, atol=1e-8):
#     """Pearson r with fallbacks for the degenerate cases common in TS features."""
#     if py.size < 2:
#         return np.nan  # not enough finite points to correlate
#     if np.allclose(py, mat, atol=atol):
#         return 1.0  # identical constants: variance is zero but parity is perfect
#     try:
#         r, _ = pearsonr(py, mat)
#     except ValueError:
#         return np.nan  # fallback for remaining edge cases
#     return r
 
 
# def get_correlations(eng, data, params):
#     records = []
#     raw_outputs = {}
 
#     for suite_name, settings, param_dict in params:
#         aggregator = defaultdict(lambda: {"py": [], "mat": []})
 
#         for series in data:
#             res = test_matlab_parity(eng, series, suite_name, settings, param_dict)
#             for full_key, values in res.items():
#                 if "error" in values:
#                     print(f"Skipping {full_key}: {values['error']}")
#                     continue
#                 aggregator[full_key]["py"].append(values["py"])
#                 aggregator[full_key]["mat"].append(values["mat"])
 
#         for feature_name, lists in aggregator.items():
#             shapes = {np.shape(np.asarray(v, dtype=float)) for v in lists["mat"]}
#             if shapes != {()}:
#                 print(feature_name, "mat shapes:", shapes)
#             shapes_py = {np.shape(np.asarray(v, dtype=float)) for v in lists["py"]}
#             if shapes_py != {()}:
#                 print(feature_name, "py shapes:", shapes_py)
#             py_vec = np.asarray(lists["py"], dtype=float)
#             mat_vec = np.asarray(lists["mat"], dtype=float)
#             raw_outputs[feature_name] = {"py": py_vec, "mat": mat_vec}
 
#             mask = np.isfinite(py_vec) & np.isfinite(mat_vec)
#             py_valid, mat_valid = py_vec[mask], mat_vec[mask]
 
#             r = _safe_correlation(py_valid, mat_valid)
#             if py_valid.size >= 1:
#                 mae = mean_absolute_error(py_valid, mat_valid)
#                 mape = mean_absolute_percentage_error(py_valid, mat_valid)
#             else:
#                 mae = mape = np.nan
 
#             records.append({
#                 "python_func": settings["python_func"],
#                 "feature": feature_name.split(":")[2],
#                 "matlab_func": settings["matlab_func"],
#                 "python_module": settings["python_module"],
#                 "corr": r,
#                 "mae": mae,
#                 "mape": mape,
#                 "nan_count_py": int(np.sum(~np.isfinite(py_vec))),
#                 "nan_count_ml": int(np.sum(~np.isfinite(mat_vec))),
#             })
 
#             print(f"{settings['python_func']}-{feature_name}: {r:.4f}")
 
#     return pd.DataFrame(records), raw_outputs

In [80]:
params = generate_test_cases('surrogates_validation.yaml')
params

[('surrogate_test_check',
  {'python_func': 'surrogate_test',
   'python_module': 'surrogates',
   'matlab_func': 'SD_SurrogateTest',
   'arg_map': {'surr_meth': 'surrMeth',
    'num_surrs': 'numSurrs',
    'the_test_stat': 'theTestStat'},
   'matlab_extra_args': {'extrap': []},
   'matlab_signature': ['y', 'surrMeth', 'numSurrs', 'extrap', 'theTestStat'],
   'output_type': 'array',
   'stochastic': True,
   'n_seeds': 10,
   'test_cases': [{'surr_meth': 'RP',
     'num_surrs': 99,
     'the_test_stat': 'ami1',
     'zscore': True}]},
  {'surr_meth': 'RP',
   'num_surrs': 99,
   'the_test_stat': 'ami1',
   'zscore': True})]

In [83]:
df, outputs = get_correlations(eng, dataset, params)

Operation terminated by user during SD_SurrogateTest (line 137)

the MATLAB function has been cancelled
Skipping num_surrs99_surr_methRP_the_test_statami1_zscoreTrue::output: Missing in Python

Operation terminated by user during SD_MakeSurrogates (line 118)


In SD_SurrogateTest (line 115)
z = SD_MakeSurrogates(x,surrMeth,numSurrs,extrap,randomSeed);
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

the MATLAB function has been cancelled
Skipping num_surrs99_surr_methRP_the_test_statami1_zscoreTrue::output: Missing in Python
surrogate_test-num_surrs99_surr_methRP_the_test_statami1_zscoreTrue::ami_zscore: corr=0.9934 ks_pass=0.25
surrogate_test-num_surrs99_surr_methRP_the_test_statami1_zscoreTrue::ami_mediqr: corr=0.9870 ks_pass=0.282
surrogate_test-num_surrs99_surr_methRP_the_test_statami1_zscoreTrue::ami_p: corr=0.9922 ks_pass=0.357
surrogate_test-num_surrs99_surr_methRP_the_test_statami1_zscoreTrue::ami_prank: corr=0.9929 ks_pass=0.553
surrogate_test-num_surrs99_surr_methRP_the_test_statami1_zscoreTrue::ami_f: corr=0.9469 ks_pass=0.392

In [85]:
eng.quit()

In [38]:
from pyhctsa.operations.symbolic import surprise

In [57]:
surprise(z_score(dataset[0]), 'T1', 10, 'tau', 'embed2quadrants', 500, 1)

{'min': np.float64(0.13353139262452263),
 'max': np.float64(1.9459101490553135),
 'mean': np.float64(0.3509689360792236),
 'sum': np.float64(175.48446803961178),
 'median': np.float64(0.0),
 'lq': np.float64(-0.0),
 'uq': np.float64(0.6931471805599453),
 'std': np.float64(0.49887353583463456),
 'tstat': np.float64(29.091091713410375)}

In [84]:
df

,python_func,params,feature,matlab_func,python_module,corr,mae,mape,ks_pass_frac,n_stochastic_series,nan_count_py,nan_count_ml
0,surrogate_test,num_surrs99_surr_methRP_the_test_statami1_zsco...,ami_zscore,SD_SurrogateTest,surrogates,0.993439,33.317074,1.926721e+00,0.250,1000,0,0
1,surrogate_test,num_surrs99_surr_methRP_the_test_statami1_zsco...,ami_mediqr,SD_SurrogateTest,surrogates,0.986975,47.033138,2.750174e-01,0.282,1000,0,0
2,surrogate_test,num_surrs99_surr_methRP_the_test_statami1_zsco...,ami_p,SD_SurrogateTest,surrogates,0.992157,0.023060,2.016216e+00,0.357,1000,0,0
3,surrogate_test,num_surrs99_surr_methRP_the_test_statami1_zsco...,ami_prank,SD_SurrogateTest,surrogates,0.992897,0.023085,8.727912e-02,0.553,1000,0,0
4,surrogate_test,num_surrs99_surr_methRP_the_test_statami1_zsco...,ami_f,SD_SurrogateTest,surrogates,0.946939,0.052531,2.311096e+11,0.392,1000,0,0

In [61]:
eng.SD_SurrogateTest(z_score(dataset[0]).reshape(-1, 1), 'RP', 99, '', 'ami1')

{'ami_p': 0.8022420196447544,
 'ami_zscore': -0.849656732014462,
 'ami_f': 0.19536859205779447,
 'ami_mediqr': 1.2313134850636027,
 'ami_prank': 0.93}

In [29]:
from pyhctsa.operations.surrogates import surrogate_test

In [64]:
surrogate_test(z_score(dataset[0]), 'RP', 99, 'ami1', 0)

{'ami_p': np.float64(0.9022255015992962),
 'ami_zscore': np.float64(-1.2943371292006005),
 'ami_f': 0.1367868776057187,
 'ami_mediqr': np.float64(1.2723425308707155),
 'ami_prank': np.float64(0.95)}

In [23]:
df

,python_func,params,feature,matlab_func,python_module,corr,mae,mape,ks_pass_frac,n_stochastic_series,nan_count_py,nan_count_ml
0,surrogate_test,num_surrs99_surr_methRP_the_test_statami1_zsco...,ami_p,SD_SurrogateTest,surrogates,NaN,NaN,NaN,NaN,0,10,10
1,surrogate_test,num_surrs99_surr_methRP_the_test_statami1_zsco...,ami_zscore,SD_SurrogateTest,surrogates,NaN,NaN,NaN,NaN,0,10,10
2,surrogate_test,num_surrs99_surr_methRP_the_test_statami1_zsco...,ami_f,SD_SurrogateTest,surrogates,NaN,NaN,NaN,NaN,0,10,10
3,surrogate_test,num_surrs99_surr_methRP_the_test_statami1_zsco...,ami_mediqr,SD_SurrogateTest,surrogates,NaN,NaN,NaN,NaN,0,10,10
4,surrogate_test,num_surrs99_surr_methRP_the_test_statami1_zsco...,ami_prank,SD_SurrogateTest,surrogates,NaN,NaN,NaN,NaN,0,10,10

In [36]:
outputs['num_states2_train_p0.8_zscoreTrue::Cov']['py'][:10]

array([0.39818197, 0.55101531, 0.50195457, 0.47725359, 0.68166559,
       0.4503819 , 0.37493166, 0.35821545, 0.46266263, 0.33975424])

In [37]:
outputs['num_states2_train_p0.8_zscoreTrue::Cov']['mat'][:10]

array([0.99683194, 0.88438266, 0.99362557, 0.48448326, 0.96931802,
       0.98339609, 0.98474309, 0.98656583, 0.46041764, 0.34058164])

In [32]:
from pyhctsa.operations.model_fit import hmm_fit

In [39]:
hmm_fit(z_score(dataset[0]), 0.8, 2)

{'Mu_1': np.float64(-0.4109799904871097),
 'Mu_2': np.float64(1.4628780381758404),
 'meanMu': np.float64(0.5259490238443654),
 'rangeMu': np.float64(1.87385802866295),
 'maxMu': np.float64(1.4628780381758404),
 'minMu': np.float64(-0.4109799904871097),
 'Cov': np.float64(0.3981819697117933),
 'Pmeandiag': np.float64(0.5043771822685591),
 'std_mean_p': np.float64(0.3947121959526117),
 'max_p': np.float64(0.7834808526436842),
 'mean_p': np.float64(0.5),
 'std_p': np.float64(0.322320789569395),
 'LLtrainpersample': -1.3348291973323223,
 'LLtestpersample': -1.3388453150742894,
 'LLdifference': -0.004016117741967085}

In [84]:
eng.MF_hmm_fit(z_score(dataset[0]).reshape(-1, 1), 0.8, 2.0, 1)

{'Mu_1': -0.41217910086747506,
 'Mu_2': 1.4601404130561515,
 'meanMu': 0.5239806560943382,
 'rangeMu': 1.8723195139236266,
 'maxMu': 1.4601404130561515,
 'minMu': -0.41217910086747506,
 'Cov': 0.39754818118490165,
 'Pmeandiag': 0.5043456789169696,
 'stdmeanP': 0.3935876953507983,
 'maxP': 0.782654207291104,
 'meanP': 0.5,
 'stdP': 0.3214021818864454,
 'LLtrainpersample': -1.334834961658112,
 'nit': 19.0,
 'LLtestpersample': -1.3388204133511517,
 'LLdifference': -0.003985451693039543}

In [23]:
df

,python_func,params,feature,matlab_func,python_module,corr,mae,mape,ks_pass_frac,n_stochastic_series,nan_count_py,nan_count_ml
0,hmm_fit,num_states2_train_p0.8_zscoreTrue,Pmeandiag,MF_hmm_fit,model_fit,0.612884,0.132809,0.565876,NaN,0,0,1
1,hmm_fit,num_states2_train_p0.8_zscoreTrue,rangeMu,MF_hmm_fit,model_fit,0.108686,0.852592,0.929551,NaN,0,0,1
2,hmm_fit,num_states2_train_p0.8_zscoreTrue,Cov,MF_hmm_fit,model_fit,0.489680,0.195783,0.934714,NaN,0,0,1
3,hmm_fit,num_states2_train_p0.8_zscoreTrue,LLtrainpersample,MF_hmm_fit,model_fit,0.826102,0.100594,0.140006,NaN,0,0,1
4,hmm_fit,num_states2_train_p0.8_zscoreTrue,meanMu,MF_hmm_fit,model_fit,0.326099,0.324105,5.437048,NaN,0,0,1
5,hmm_fit,num_states2_train_p0.8_zscoreTrue,minMu,MF_hmm_fit,model_fit,0.436001,0.298391,0.533737,NaN,0,0,1
6,hmm_fit,num_states2_train_p0.8_zscoreTrue,Mu_2,MF_hmm_fit,model_fit,0.173158,0.635316,1.811480,NaN,0,0,1
7,hmm_fit,num_states2_train_p0.8_zscoreTrue,maxMu,MF_hmm_fit,model_fit,0.173158,0.635316,1.811480,NaN,0,0,1
8,hmm_fit,num_states2_train_p0.8_zscoreTrue,LLtestpersample,MF_hmm_fit,model_fit,0.422470,301.109171,0.182933,NaN,0,0,1
9,hmm_fit,num_states2_train_p0.8_zscoreTrue,Mu_1,MF_hmm_fit,model_fit,0.436001,0.298391,0.533737,NaN,0,0,1
10,hmm_fit,num_states2_train_p0.8_zscoreTrue,LLdifference,MF_hmm_fit,model_fit,0.426279,301.047848,589.243027,NaN,0,0,1

In [51]:
eng.CO_FirstMin(z_score(dataset[2]), 'ac', '', True)

3.0

In [43]:
from pyhctsa.operations.information import first_min

In [44]:
first_min(z_score(dataset[0]), 'ac')

2

In [39]:
df

,python_func,params,feature,matlab_func,python_module,corr,mae,mape,ks_pass_frac,n_stochastic_series,nan_count_py,nan_count_ml
0,first_min,min_whatac_zscoreTrue,min_whatac_zscoreTrue,CO_FirstMin,information,0.870538,57.741,0.551119,NaN,0,0,0

In [48]:
outputs['min_whatac_zscoreTrue::output']['py']

array([2.000e+00, 2.000e+00, 3.000e+00, 2.000e+00, 1.000e+00, 2.000e+00,
       2.000e+00, 1.000e+00, 1.000e+00, 2.000e+00, 1.000e+00, 3.000e+00,
       1.000e+00, 1.000e+00, 2.000e+00, 2.000e+00, 1.000e+00, 3.000e+00,
       2.000e+00, 1.000e+00, 2.700e+01, 1.670e+02, 6.770e+03, 1.702e+03,
       7.200e+02, 2.140e+03, 3.474e+03, 3.690e+02, 2.260e+02, 4.430e+02,
       6.210e+02, 3.150e+02, 6.070e+02, 6.580e+02, 5.440e+02, 1.600e+02,
       4.190e+02, 3.300e+02, 1.006e+03, 2.580e+03, 1.237e+03, 3.500e+01,
       1.895e+03, 3.100e+01, 1.500e+01, 1.500e+01, 1.000e+00, 1.688e+03,
       2.000e+00, 3.953e+03, 4.720e+02, 3.557e+03, 4.362e+03, 1.129e+03,
       5.510e+02, 9.700e+02, 4.519e+03, 8.380e+02, 1.000e+00, 5.000e+00,
       6.000e+00, 2.000e+00, 1.000e+00, 5.000e+00, 1.000e+00, 2.000e+00,
       1.000e+00, 2.000e+00, 1.000e+00, 3.000e+00, 2.094e+03, 2.986e+03,
       1.520e+02, 1.973e+03, 7.700e+01, 2.180e+02, 6.800e+01, 1.200e+01,
       2.500e+01, 4.700e+01, 4.000e+00, 2.300e+01, 1.900e+01, 2.300e+01,
       1.500e+01, 4.000e+00, 3.200e+01, 1.600e+01, 1.090e+02, 1.060e+02,
       1.100e+01, 1.100e+01, 3.000e+00, 1.000e+01, 5.900e+01, 7.000e+00,
       4.000e+00, 1.000e+00, 1.000e+00, 2.310e+02, 2.770e+02, 2.300e+01,
       1.380e+02, 1.400e+01, 7.000e+00, 2.800e+01, 3.000e+00, 3.000e+00,
       1.000e+00, 7.000e+00, 4.000e+00, 4.000e+00, 1.000e+01, 6.000e+01,
       6.000e+01, 1.000e+00, 1.000e+00, 4.000e+00, 5.800e+01, 4.000e+00,
       1.900e+01, 1.230e+02, 1.200e+01, 1.200e+01, 6.300e+01, 8.000e+00,
       4.000e+00, 3.300e+01, 1.200e+01, 1.700e+01, 6.000e+00, 1.120e+02,
       4.000e+01, 2.000e+00, 2.000e+00, 3.000e+00, 5.000e+00, 5.000e+00,
       5.000e+00, 5.000e+00, 5.000e+00, 5.000e+00, 6.000e+00, 2.000e+00,
       4.000e+00, 8.000e+00, 5.000e+00, 4.000e+00, 5.000e+00, 2.000e+00,
       3.000e+00, 2.000e+00, 1.100e+01, 1.100e+01, 1.100e+01, 1.100e+01,
       1.100e+01, 1.100e+01, 1.100e+01, 1.100e+01, 2.000e+00, 2.000e+00,
       2.000e+00, 2.000e+00, 2.000e+00, 5.000e+00, 3.000e+00, 2.000e+00,
       3.000e+00, 5.000e+00, 6.000e+00, 4.000e+00, 6.000e+00, 3.000e+00,
       1.000e+01, 3.000e+00, 2.000e+00, 7.000e+00, 3.000e+00, 1.000e+00,
       1.000e+01, 3.000e+00, 3.000e+00, 2.000e+00, 5.000e+00, 4.000e+00,
       2.000e+00, 7.000e+00, 3.000e+00, 2.000e+00, 6.000e+00, 7.000e+00,
       1.000e+00, 2.000e+00, 2.000e+00, 1.000e+00, 2.000e+00, 1.000e+00,
       2.000e+00, 1.000e+00, 2.000e+00, 2.000e+00, 2.000e+00, 3.000e+00,
       2.000e+00, 2.000e+00, 2.000e+00, 2.000e+00, 2.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 3.000e+00,
       3.000e+00, 3.000e+00, 3.000e+00, 3.000e+00, 3.000e+00, 3.000e+00,
       3.000e+00, 2.400e+01, 3.000e+00, 1.800e+01, 3.000e+00, 3.000e+00,
       2.000e+00, 2.000e+00, 2.000e+00, 2.000e+00, 4.000e+00, 2.000e+00,
       2.000e+00, 2.000e+00, 6.000e+00, 1.000e+00, 7.000e+00, 3.000e+00,
       1.000e+00, 6.000e+00, 1.000e+00, 1.000e+00, 2.000e+00, 1.000e+00,
       2.000e+00, 3.000e+00, 1.000e+00, 2.000e+00, 1.000e+00, 1.000e+00,
       2.000e+00, 3.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 3.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 2.000e+00, 2.000e+00, 2.000e+00, 2.000e+00, 2.000e+00,
       2.000e+00, 2.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       2.000e+00, 1.000e+00, 2.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       2.000e+00, 2.000e+00, 2.000e+00, 2.000e+00, 1.000e+00, 2.000e+00,
       1.000e+00, 2.000e+00, 2.000e+00, 2.000e+00, 2.000e+00, 2.000e+00,
       2.000e+00, 2.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 6.000e+00, 1.000e+00, 4.000e+00,
       6.000e+00, 1.000e+00, 6.000e+00, 6.000e+00, 1.400e+01, 7.000e+00,
       2.200e+01, 7.000e+00, 7.000e+00, 2.200e+01, 1.200e+01, 1.700e+01,
       2.200e+01, 7.000e+00, 1.200e+01, 2.000e+00, 9.000e+00, 2.859e+03,
       3.460e+02, 2.000e+00, 2.000e+00, 1.290e+02, 5.370e+02, 1.100e+01,
       1.100e+01, 1.100e+01, 1.100e+01, 1.100e+01, 3.800e+01, 4.000e+00,
       4.000e+00, 2.000e+00, 5.000e+00, 4.000e+00, 1.000e+01, 2.000e+00,
       1.000e+00, 2.000e+00, 3.000e+00, 2.000e+00, 2.000e+00, 3.000e+01,
       3.100e+01, 1.000e+00, 2.900e+01, 1.000e+00, 3.300e+01, 1.000e+00,
       4.000e+00, 1.000e+00, 2.700e+01, 3.000e+00, 1.400e+01, 1.500e+01,
       5.800e+01, 6.000e+00, 2.900e+01, 3.000e+01, 2.000e+00, 2.800e+01,
       1.860e+02, 3.000e+00, 3.000e+00, 4.200e+01, 4.400e+01, 5.000e+00,
       1.100e+01, 1.050e+02, 4.000e+00, 4.000e+00, 1.700e+01, 1.900e+01,
       2.000e+00, 1.100e+01, 3.300e+01, 3.800e+01, 1.800e+01, 1.000e+00,
       3.700e+01, 1.480e+02, 9.990e+02, 1.170e+03, 1.177e+03, 4.000e+00,
       3.000e+00, 3.000e+00, 3.000e+00, 2.000e+00, 2.000e+00, 2.000e+00,
       8.000e+00, 7.000e+00, 4.000e+00, 4.000e+00, 8.000e+00, 3.000e+00,
       3.040e+02, 1.191e+03, 3.235e+03, 2.370e+02, 4.740e+02, 3.640e+02,
       7.530e+02, 5.900e+01, 4.000e+00, 1.000e+00, 3.000e+00, 4.000e+00,
       5.000e+00, 8.000e+00, 2.000e+00, 3.000e+00, 2.000e+00, 2.000e+00,
       2.000e+00, 2.100e+02, 1.110e+02, 2.100e+01, 8.400e+01, 2.000e+00,
       4.000e+00, 1.000e+01, 9.000e+00, 2.000e+00, 5.000e+00, 5.000e+00,
       4.000e+00, 6.000e+00, 4.000e+00, 3.000e+01, 2.200e+01, 2.000e+00,
       1.500e+01, 2.000e+00, 2.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 3.000e+00, 2.000e+00, 1.700e+01, 1.600e+01,
       1.560e+02, 2.100e+01, 8.400e+01, 7.800e+01, 9.000e+00, 7.000e+00,
       8.000e+01, 8.300e+01, 4.100e+01, 1.230e+02, 3.300e+01, 3.000e+00,
       2.180e+03, 7.000e+00, 1.300e+01, 8.000e+00, 3.200e+01, 3.000e+00,
       3.000e+00, 1.600e+01, 2.000e+00, 2.000e+00, 2.000e+00, 8.000e+00,
       7.000e+00, 7.000e+00, 2.000e+00, 4.000e+00, 7.000e+00, 3.500e+01,
       3.500e+01, 1.400e+01, 1.400e+01, 3.000e+00, 6.900e+01, 7.100e+01,
       2.000e+00, 2.000e+00, 7.000e+01, 7.000e+00, 7.000e+00, 1.330e+03,
       4.288e+03, 5.500e+01, 4.580e+02, 2.929e+03, 5.520e+02, 3.880e+03,
       1.140e+02, 5.100e+01, 6.000e+00, 3.000e+01, 1.500e+01, 2.000e+01,
       6.000e+00, 2.000e+00, 1.000e+01, 1.490e+02, 1.500e+01, 8.000e+00,
       8.600e+01, 3.700e+01, 4.300e+01, 6.000e+00, 1.200e+01, 1.000e+00,
       6.000e+00, 1.300e+02, 1.300e+01, 5.000e+00, 2.500e+01, 7.000e+00,
       1.700e+01, 9.000e+00, 1.800e+02, 9.000e+00, 3.500e+01, 7.000e+00,
       3.300e+01, 8.000e+00, 1.900e+01, 3.820e+02, 3.800e+01, 1.900e+01,
       6.000e+00, 7.700e+01, 2.000e+00, 4.000e+00, 6.000e+00, 2.000e+00,
       3.500e+01, 3.000e+00, 1.600e+01, 2.000e+00, 1.580e+02, 1.510e+02,
       8.000e+00, 1.000e+00, 4.000e+00, 6.300e+01, 3.100e+01, 3.000e+01,
       1.600e+01, 3.000e+01, 2.000e+00, 1.500e+01, 3.000e+01, 1.600e+01,
       8.000e+00, 2.200e+01, 2.000e+00, 2.180e+02, 8.700e+01, 9.000e+00,
       9.000e+00, 4.000e+00, 1.600e+01, 2.000e+00, 1.000e+01, 2.120e+02,
       1.000e+00, 5.000e+00, 8.300e+01, 1.500e+01, 1.100e+01, 8.000e+00,
       6.000e+00, 7.000e+00, 1.400e+01, 1.200e+01, 8.000e+00, 1.000e+00,
       5.000e+00, 6.000e+00, 1.000e+00, 6.000e+00, 6.000e+00, 8.000e+00,
       6.000e+00, 3.000e+00, 7.000e+00, 6.000e+00, 7.000e+00, 6.000e+00,
       4.000e+00, 4.000e+00, 1.000e+00, 6.000e+00, 4.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 2.000e+00, 1.000e+00, 1.000e+00,
       3.000e+00, 1.000e+00, 2.000e+00, 3.500e+01, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 2.700e+01, 1.000e+00, 1.000e+00,
       2.000e+00, 2.000e+00, 1.000e+00, 2.000e+00, 1.300e+01, 6.100e+01,
       5.000e+00, 6.200e+01, 5.000e+00, 2.000e+00, 8.300e+01, 1.000e+00,
       1.900e+01, 1.000e+00, 5.000e+00, 3.000e+00, 8.000e+00, 3.000e+00,
       5.000e+00, 6.000e+00, 3.000e+00, 5.000e+00, 1.000e+01, 1.000e+01,
       2.500e+01, 2.500e+01, 5.000e+00, 1.000e+00, 2.470e+02, 6.020e+02,
       2.008e+03, 6.620e+02, 2.100e+01, 5.000e+00, 5.000e+00, 9.000e+00,
       5.000e+00, 1.500e+01, 1.000e+00, 1.000e+00, 8.000e+00, 2.000e+00,
       1.000e+00, 2.000e+00, 1.000e+00, 1.000e+00, 9.000e+00, 6.000e+00,
       5.000e+00, 2.000e+00, 7.000e+00, 1.000e+00, 1.000e+00, 5.000e+00,
       5.000e+00, 2.000e+00, 2.000e+00, 3.000e+00, 1.000e+01, 5.000e+00,
       3.000e+00, 3.000e+00, 4.000e+00, 6.000e+00, 4.000e+00, 3.000e+00,
       7.000e+00, 6.000e+00, 6.000e+00, 6.000e+00, 6.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 2.000e+00, 1.000e+00, 1.000e+00, 2.000e+00, 2.000e+00,
       2.000e+00, 2.000e+00, 3.000e+00, 2.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 6.000e+00, 6.000e+00, 6.000e+00,
       2.000e+00, 1.200e+01, 3.000e+00, 4.000e+00, 6.000e+00, 5.000e+00,
       7.000e+00, 7.000e+00, 9.000e+00, 1.200e+01, 1.000e+01, 3.000e+00,
       3.000e+00, 4.000e+00, 4.000e+00, 4.000e+00, 3.000e+00, 3.000e+00,
       4.000e+00, 4.000e+00, 9.000e+00, 1.000e+00, 2.000e+00, 4.000e+00,
       4.000e+00, 1.423e+03, 1.960e+02, 1.567e+03, 1.452e+03, 7.970e+02,
       2.152e+03, 2.600e+01, 2.300e+01, 2.500e+01, 6.000e+00, 2.500e+01,
       1.000e+00, 2.600e+01, 2.400e+01, 8.000e+00, 3.000e+00, 6.800e+01,
       2.400e+01, 4.100e+02, 2.000e+01, 2.300e+01, 2.100e+01, 2.800e+01,
       5.000e+00, 5.000e+00, 4.000e+00, 4.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 6.000e+00, 1.000e+00, 3.000e+00,
       1.000e+00, 3.000e+00, 1.000e+00, 2.000e+00, 1.000e+00, 2.000e+01,
       1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.900e+01, 7.050e+02, 1.900e+01, 2.400e+01, 2.300e+01, 4.900e+01,
       1.200e+01, 2.400e+01, 7.000e+00, 1.100e+01, 7.000e+00, 3.000e+00,
       1.100e+01, 9.000e+00, 1.490e+02, 2.195e+03, 4.300e+01, 2.500e+01,
       3.000e+00, 6.000e+00, 2.000e+02, 6.700e+01, 7.300e+01, 3.400e+01,
       2.000e+00, 2.100e+01, 4.000e+00, 7.500e+01, 8.900e+01, 2.880e+02,
       2.650e+02, 4.030e+02, 1.570e+02, 1.200e+02, 1.640e+02, 8.000e+00,
       5.000e+00, 4.000e+00, 5.000e+00, 9.000e+00, 4.000e+00, 4.000e+00,
       5.000e+00, 7.000e+00, 3.000e+00, 5.000e+00, 2.000e+00, 2.000e+00,
       3.000e+00, 1.000e+00, 4.000e+00, 1.000e+00, 8.000e+00, 5.000e+00,
       2.000e+00, 6.000e+00, 6.000e+00, 3.000e+00, 6.000e+00, 6.000e+00,
       6.000e+00, 6.000e+00, 6.000e+00, 6.000e+00, 6.000e+00, 6.000e+00,
       6.000e+00, 4.000e+00, 4.000e+00, 5.000e+00, 4.000e+00, 3.000e+00,
       7.000e+00, 3.000e+00, 5.000e+00, 3.000e+00, 2.000e+00, 1.100e+01,
       1.100e+01, 7.400e+01, 1.500e+01, 1.400e+01, 1.500e+01, 1.800e+01,
       1.600e+01, 1.800e+01, 1.100e+01, 1.200e+01, 1.200e+01, 1.200e+01,
       1.200e+01, 1.100e+01, 4.300e+01, 5.000e+00, 5.300e+01, 5.200e+01,
       5.900e+01, 5.400e+01, 4.900e+01, 8.480e+02, 2.280e+02, 3.150e+02,
       2.380e+02, 2.650e+02, 1.270e+02, 2.150e+02, 1.830e+02, 1.380e+02,
       1.830e+02, 1.040e+02, 1.340e+02, 1.120e+02, 9.000e+01, 9.000e+00,
       3.000e+00, 1.900e+01, 8.000e+00, 7.000e+00, 7.000e+00, 8.000e+00,
       6.000e+00, 9.000e+00, 7.000e+00, 1.000e+01, 7.000e+00, 1.000e+00,
       4.000e+00, 2.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 2.000e+00, 1.000e+00, 2.000e+00, 4.000e+00, 3.000e+00,
       3.000e+00, 3.000e+00, 1.000e+01, 2.100e+01, 1.500e+01, 5.000e+00,
       3.000e+00, 3.000e+00, 3.000e+00, 3.000e+00, 5.000e+00, 4.000e+00,
       4.000e+00, 5.000e+00, 4.000e+00, 4.000e+00, 4.000e+00, 4.000e+00,
       4.000e+00, 4.000e+00, 4.000e+00, 4.000e+00, 4.000e+00, 4.000e+00,
       1.400e+01, 2.000e+00, 1.000e+00, 9.200e+01, 1.900e+01, 2.400e+01,
       1.000e+00, 1.000e+00, 7.000e+00, 8.000e+00, 3.000e+00, 6.700e+01,
       4.000e+00, 8.000e+00, 9.000e+00, 4.000e+00, 2.000e+00, 1.900e+01,
       9.660e+02, 7.500e+01, 3.000e+00, 3.000e+00])

In [49]:
outputs['min_whatac_zscoreTrue::output']['mat']

array([1.000e+00, 1.000e+00, 1.000e+00, 2.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 2.000e+00, 5.000e+00, 2.000e+00, 2.000e+00, 1.000e+00,
       3.000e+00, 3.000e+00, 3.000e+00, 1.000e+00, 1.000e+00, 3.000e+00,
       1.000e+00, 3.000e+00, 2.700e+01, 1.360e+02, 2.002e+03, 1.281e+03,
       3.700e+01, 1.814e+03, 2.267e+03, 3.690e+02, 2.260e+02, 2.370e+02,
       8.100e+01, 1.850e+02, 2.690e+02, 2.770e+02, 2.830e+02, 2.900e+01,
       9.600e+01, 1.740e+02, 7.060e+02, 9.900e+01, 9.030e+02, 2.500e+01,
       1.117e+03, 1.600e+01, 8.000e+00, 8.000e+00, 2.000e+00, 1.215e+03,
       1.000e+00, 1.887e+03, 1.360e+02, 2.867e+03, 2.521e+03, 8.770e+02,
       1.740e+02, 5.660e+02, 8.990e+02, 7.950e+02, 3.000e+00, 3.000e+00,
       3.000e+00, 1.000e+00, 2.000e+00, 2.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 3.500e+01, 1.000e+00, 1.316e+03, 1.016e+03,
       9.600e+01, 1.019e+03, 5.200e+01, 2.140e+02, 4.900e+01, 1.200e+01,
       1.800e+01, 3.400e+01, 2.000e+00, 1.700e+01, 9.000e+00, 1.700e+01,
       1.100e+01, 2.000e+00, 1.600e+01, 8.000e+00, 5.700e+01, 5.400e+01,
       5.000e+00, 6.000e+00, 2.000e+00, 6.000e+00, 2.800e+01, 4.000e+00,
       2.000e+00, 3.000e+00, 3.000e+00, 1.050e+02, 1.370e+02, 1.000e+01,
       6.900e+01, 6.000e+00, 7.000e+00, 2.800e+01, 3.000e+00, 3.000e+00,
       1.000e+00, 7.000e+00, 2.000e+00, 2.000e+00, 6.000e+00, 3.400e+01,
       3.400e+01, 1.000e+00, 1.000e+00, 2.000e+00, 2.900e+01, 2.000e+00,
       1.000e+01, 6.200e+01, 6.000e+00, 6.000e+00, 3.200e+01, 3.000e+00,
       2.000e+00, 1.500e+01, 7.000e+00, 7.000e+00, 4.000e+00, 4.900e+01,
       2.300e+01, 1.000e+00, 1.000e+00, 2.000e+00, 3.000e+00, 3.000e+00,
       3.000e+00, 3.000e+00, 3.000e+00, 3.000e+00, 3.000e+00, 4.000e+00,
       3.000e+00, 6.000e+00, 3.000e+00, 3.000e+00, 3.000e+00, 3.000e+00,
       2.000e+00, 4.000e+00, 4.000e+00, 4.000e+00, 1.100e+01, 4.000e+00,
       1.100e+01, 5.000e+00, 4.000e+00, 1.100e+01, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 5.000e+00, 2.000e+00, 2.000e+00,
       2.000e+00, 6.000e+00, 6.000e+00, 2.000e+00, 3.000e+00, 2.000e+00,
       1.000e+01, 2.000e+00, 1.000e+00, 7.000e+00, 1.000e+00, 2.000e+00,
       1.000e+01, 1.000e+00, 2.000e+00, 1.000e+00, 3.000e+00, 3.000e+00,
       1.000e+00, 7.000e+00, 3.000e+00, 1.000e+00, 6.000e+00, 6.000e+00,
       2.000e+00, 8.000e+00, 1.000e+00, 3.000e+00, 3.000e+00, 2.000e+00,
       1.000e+00, 2.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 2.000e+00,
       2.000e+00, 2.000e+00, 2.000e+00, 2.000e+00, 2.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 3.000e+00, 3.000e+00,
       3.000e+00, 2.400e+01, 3.000e+00, 1.600e+01, 3.000e+00, 3.000e+00,
       2.000e+00, 2.000e+00, 1.000e+00, 1.000e+00, 4.000e+00, 1.000e+00,
       1.000e+00, 2.000e+00, 6.000e+00, 6.000e+00, 5.000e+00, 3.000e+00,
       3.000e+00, 7.000e+00, 3.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       3.000e+00, 4.000e+00, 3.000e+00, 2.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 2.000e+00, 2.000e+00, 2.000e+00, 2.000e+00, 2.000e+00,
       2.000e+00, 2.000e+00, 1.000e+00, 2.000e+00, 2.000e+00, 2.000e+00,
       2.000e+00, 2.000e+00, 2.000e+00, 2.000e+00, 2.000e+00, 2.000e+00,
       2.000e+00, 2.000e+00, 5.000e+00, 5.000e+00, 5.000e+00, 4.000e+00,
       5.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 3.000e+00, 3.000e+00, 2.000e+00, 3.000e+00,
       1.000e+00, 2.000e+00, 1.000e+00, 3.000e+00, 3.000e+00, 2.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 3.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 2.000e+00, 2.000e+00, 2.000e+00, 2.000e+00,
       2.000e+00, 2.000e+00, 2.000e+00, 2.000e+00, 2.000e+00, 4.000e+00,
       3.000e+00, 5.000e+00, 3.000e+00, 3.000e+00, 2.000e+00, 2.000e+00,
       3.000e+00, 3.000e+00, 1.000e+00, 3.000e+00, 1.000e+00, 3.000e+00,
       3.000e+00, 1.000e+00, 3.000e+00, 3.000e+00, 7.000e+00, 4.000e+00,
       1.100e+01, 4.000e+00, 4.000e+00, 1.000e+01, 6.000e+00, 9.000e+00,
       1.100e+01, 4.000e+00, 6.000e+00, 1.000e+00, 5.000e+00, 1.138e+03,
       2.400e+01, 1.000e+00, 1.000e+00, 1.280e+02, 2.050e+02, 6.000e+00,
       6.000e+00, 6.000e+00, 6.000e+00, 6.000e+00, 2.100e+01, 4.000e+00,
       2.000e+00, 1.000e+00, 3.000e+00, 5.000e+00, 5.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 2.000e+00, 1.000e+00, 1.000e+00, 1.600e+01,
       1.600e+01, 1.000e+00, 1.600e+01, 1.000e+00, 1.600e+01, 1.000e+00,
       4.000e+00, 6.000e+00, 9.000e+00, 1.000e+00, 5.000e+00, 8.000e+00,
       2.900e+01, 3.000e+00, 1.400e+01, 1.500e+01, 2.000e+00, 1.500e+01,
       9.800e+01, 2.000e+00, 2.000e+00, 2.200e+01, 2.500e+01, 3.000e+00,
       6.000e+00, 5.600e+01, 2.000e+00, 2.000e+00, 8.000e+00, 1.000e+01,
       1.000e+00, 6.000e+00, 1.700e+01, 1.900e+01, 1.100e+01, 3.000e+00,
       2.000e+01, 1.400e+02, 7.380e+02, 5.310e+02, 6.500e+02, 4.000e+00,
       3.000e+00, 3.000e+00, 3.000e+00, 2.000e+00, 2.000e+00, 2.000e+00,
       8.000e+00, 7.000e+00, 4.000e+00, 4.000e+00, 8.000e+00, 3.000e+00,
       1.170e+02, 1.049e+03, 4.560e+02, 5.100e+01, 2.820e+02, 1.980e+02,
       3.320e+02, 5.400e+01, 4.000e+00, 1.000e+00, 3.000e+00, 4.000e+00,
       5.000e+00, 8.000e+00, 4.000e+00, 3.000e+00, 2.000e+00, 1.000e+00,
       1.000e+00, 1.050e+02, 5.200e+01, 1.000e+01, 4.200e+01, 1.000e+00,
       2.000e+00, 5.000e+00, 5.000e+00, 1.000e+00, 3.000e+00, 3.000e+00,
       2.000e+00, 6.000e+00, 3.000e+00, 3.000e+01, 1.200e+01, 2.000e+00,
       1.500e+01, 1.000e+00, 2.000e+00, 3.000e+00, 1.000e+00, 3.000e+00,
       2.000e+00, 4.000e+00, 3.000e+00, 2.000e+00, 9.000e+00, 8.000e+00,
       8.000e+01, 2.100e+01, 4.600e+01, 4.000e+01, 7.000e+00, 4.000e+00,
       8.000e+01, 6.800e+01, 2.700e+01, 7.800e+01, 3.300e+01, 3.000e+00,
       7.350e+02, 7.000e+00, 1.300e+01, 4.000e+00, 1.600e+01, 2.000e+00,
       2.000e+00, 8.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 4.000e+00,
       3.000e+00, 4.000e+00, 1.000e+00, 2.000e+00, 3.000e+00, 1.700e+01,
       1.700e+01, 7.000e+00, 7.000e+00, 2.000e+00, 3.300e+01, 3.800e+01,
       1.000e+00, 1.000e+00, 3.700e+01, 3.000e+00, 3.000e+00, 7.940e+02,
       8.300e+01, 5.100e+01, 2.290e+02, 2.031e+03, 4.560e+02, 1.594e+03,
       1.060e+02, 1.800e+01, 3.000e+00, 1.700e+01, 9.000e+00, 1.100e+01,
       3.000e+00, 1.000e+00, 6.000e+00, 9.500e+01, 9.000e+00, 6.000e+00,
       4.100e+01, 2.400e+01, 2.000e+01, 3.000e+00, 7.000e+00, 2.000e+00,
       4.000e+00, 6.900e+01, 7.000e+00, 3.000e+00, 1.400e+01, 5.000e+00,
       1.100e+01, 5.000e+00, 9.800e+01, 5.000e+00, 1.900e+01, 4.000e+00,
       2.100e+01, 4.000e+00, 1.000e+01, 1.890e+02, 1.900e+01, 1.000e+01,
       5.000e+00, 3.900e+01, 1.000e+00, 2.000e+00, 3.000e+00, 1.000e+00,
       2.100e+01, 2.000e+00, 9.000e+00, 1.000e+00, 8.000e+01, 7.600e+01,
       4.000e+00, 2.000e+00, 2.000e+00, 3.200e+01, 1.700e+01, 1.500e+01,
       9.000e+00, 1.500e+01, 1.000e+00, 7.000e+00, 1.500e+01, 9.000e+00,
       4.000e+00, 1.400e+01, 1.000e+00, 1.290e+02, 5.200e+01, 5.000e+00,
       5.000e+00, 3.000e+00, 9.000e+00, 3.000e+00, 7.000e+00, 1.350e+02,
       2.000e+00, 3.000e+00, 5.400e+01, 1.500e+01, 1.100e+01, 8.000e+00,
       5.000e+00, 7.000e+00, 1.400e+01, 1.200e+01, 8.000e+00, 1.000e+00,
       5.000e+00, 3.000e+00, 1.000e+00, 6.000e+00, 3.000e+00, 3.000e+00,
       2.000e+00, 3.000e+00, 4.000e+00, 3.000e+00, 4.000e+00, 3.000e+00,
       4.000e+00, 4.000e+00, 1.000e+00, 3.000e+00, 2.000e+00, 2.000e+00,
       2.000e+00, 5.000e+00, 3.000e+00, 2.000e+00, 3.000e+00, 2.000e+00,
       2.000e+00, 4.000e+00, 2.000e+00, 3.500e+01, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 2.700e+01, 1.000e+00, 4.000e+00,
       1.000e+00, 1.000e+00, 2.000e+00, 1.000e+00, 7.000e+00, 3.700e+01,
       3.000e+00, 3.600e+01, 3.000e+00, 1.000e+00, 6.800e+01, 1.000e+00,
       1.000e+01, 4.000e+00, 3.000e+00, 2.000e+00, 8.000e+00, 3.000e+00,
       3.000e+00, 3.000e+00, 3.000e+00, 4.000e+00, 5.000e+00, 6.000e+00,
       1.300e+01, 1.400e+01, 3.000e+00, 2.000e+00, 2.290e+02, 5.380e+02,
       9.280e+02, 6.620e+02, 1.800e+01, 5.000e+00, 5.000e+00, 9.000e+00,
       4.000e+00, 1.500e+01, 1.000e+00, 3.000e+00, 4.000e+00, 1.000e+00,
       2.000e+00, 1.000e+00, 2.000e+00, 4.000e+00, 9.000e+00, 4.000e+00,
       3.000e+00, 1.000e+00, 4.000e+00, 5.000e+00, 1.000e+00, 5.000e+00,
       5.000e+00, 2.000e+00, 2.000e+00, 3.000e+00, 1.000e+01, 3.000e+00,
       2.000e+00, 2.000e+00, 3.000e+00, 3.000e+00, 3.000e+00, 3.000e+00,
       3.000e+00, 3.000e+00, 3.000e+00, 3.000e+00, 3.000e+00, 2.000e+00,
       3.000e+00, 2.000e+00, 5.000e+00, 2.000e+00, 3.000e+00, 2.000e+00,
       1.000e+00, 1.000e+00, 2.000e+00, 2.000e+00, 3.000e+00, 1.000e+00,
       2.000e+00, 2.000e+00, 1.000e+00, 2.000e+00, 4.000e+00, 4.000e+00,
       3.000e+00, 4.000e+00, 2.000e+00, 3.000e+00, 4.000e+00, 4.000e+00,
       2.000e+00, 8.000e+00, 2.000e+00, 2.000e+00, 4.000e+00, 3.000e+00,
       4.000e+00, 4.000e+00, 4.000e+00, 7.000e+00, 5.000e+00, 2.000e+00,
       2.000e+00, 2.000e+00, 2.000e+00, 2.000e+00, 2.000e+00, 2.000e+00,
       2.000e+00, 2.000e+00, 5.000e+00, 2.000e+00, 1.000e+00, 2.000e+00,
       2.000e+00, 6.390e+02, 1.960e+02, 1.061e+03, 1.042e+03, 4.340e+02,
       5.580e+02, 1.300e+01, 1.600e+01, 1.300e+01, 6.000e+00, 1.700e+01,
       1.000e+00, 1.400e+01, 1.400e+01, 5.000e+00, 3.000e+00, 3.200e+01,
       2.400e+01, 1.150e+02, 2.000e+01, 1.900e+01, 1.900e+01, 2.400e+01,
       5.000e+00, 5.000e+00, 4.000e+00, 4.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 6.000e+00, 1.000e+00, 3.000e+00,
       1.000e+00, 3.000e+00, 1.000e+00, 2.000e+00, 1.000e+00, 2.000e+01,
       1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.300e+01, 6.460e+02, 1.900e+01, 1.200e+01, 1.100e+01, 2.200e+01,
       6.000e+00, 1.200e+01, 7.000e+00, 6.000e+00, 4.000e+00, 3.000e+00,
       1.000e+01, 9.000e+00, 1.070e+02, 1.152e+03, 2.600e+01, 2.300e+01,
       3.000e+00, 6.000e+00, 6.700e+01, 3.000e+00, 1.500e+01, 2.600e+01,
       2.000e+00, 1.700e+01, 4.000e+00, 7.400e+01, 8.900e+01, 2.190e+02,
       1.660e+02, 4.030e+02, 1.460e+02, 1.200e+02, 1.630e+02, 4.000e+00,
       5.000e+00, 4.000e+00, 5.000e+00, 9.000e+00, 4.000e+00, 4.000e+00,
       5.000e+00, 7.000e+00, 3.000e+00, 4.000e+00, 2.000e+00, 2.000e+00,
       3.000e+00, 1.000e+00, 4.000e+00, 1.000e+00, 8.000e+00, 5.000e+00,
       2.000e+00, 3.000e+00, 3.000e+00, 3.000e+00, 3.000e+00, 3.000e+00,
       3.000e+00, 3.000e+00, 3.000e+00, 3.000e+00, 3.000e+00, 3.000e+00,
       3.000e+00, 2.000e+00, 3.000e+00, 2.000e+00, 2.000e+00, 2.000e+00,
       3.000e+00, 2.000e+00, 2.000e+00, 2.000e+00, 2.000e+00, 1.100e+01,
       1.100e+01, 5.400e+01, 1.500e+01, 1.400e+01, 1.000e+01, 1.800e+01,
       1.600e+01, 1.700e+01, 1.100e+01, 1.200e+01, 8.000e+00, 1.200e+01,
       1.200e+01, 9.000e+00, 1.900e+01, 5.000e+00, 2.700e+01, 2.600e+01,
       2.900e+01, 2.700e+01, 2.400e+01, 4.680e+02, 1.150e+02, 2.460e+02,
       2.320e+02, 2.620e+02, 1.270e+02, 1.160e+02, 1.670e+02, 1.330e+02,
       1.570e+02, 1.040e+02, 1.210e+02, 7.600e+01, 7.300e+01, 5.000e+00,
       2.000e+00, 1.300e+01, 4.000e+00, 4.000e+00, 3.000e+00, 4.000e+00,
       3.000e+00, 4.000e+00, 4.000e+00, 5.000e+00, 4.000e+00, 2.000e+00,
       4.000e+00, 2.000e+00, 3.000e+00, 3.000e+00, 3.000e+00, 2.000e+00,
       2.000e+00, 3.000e+00, 1.000e+01, 3.000e+00, 3.000e+00, 1.000e+00,
       4.000e+00, 1.000e+00, 1.100e+01, 1.000e+00, 2.000e+00, 2.000e+00,
       2.000e+00, 2.000e+00, 8.000e+00, 2.100e+01, 1.400e+01, 3.000e+00,
       2.000e+00, 4.000e+00, 2.000e+00, 2.000e+00, 3.000e+00, 4.000e+00,
       3.000e+00, 3.000e+00, 3.000e+00, 3.000e+00, 3.000e+00, 3.000e+00,
       3.000e+00, 3.000e+00, 3.000e+00, 3.000e+00, 3.000e+00, 3.000e+00,
       8.000e+00, 2.000e+00, 1.000e+00, 9.200e+01, 1.900e+01, 2.400e+01,
       1.000e+00, 1.000e+00, 7.000e+00, 8.000e+00, 3.000e+00, 6.700e+01,
       4.000e+00, 8.000e+00, 9.000e+00, 4.000e+00, 2.000e+00, 1.900e+01,
       8.510e+02, 4.100e+01, 3.000e+00, 3.000e+00])

In [9]:
df

,python_func,params,feature,matlab_func,python_module,corr,mae,mape,ks_pass_frac,n_stochastic_series,nan_count_py,nan_count_ml
0,preproc_compare,detrend_methmedianf3_zscoreFalse,swss10_2,PP_Compare,pre_process,-0.001661,3.740545e+09,3.740545e+09,NaN,0,0,1
1,preproc_compare,detrend_methmedianf3_zscoreFalse,statav8,PP_Compare,pre_process,1.000000,4.688218e-02,1.803152e-02,NaN,0,0,0
2,preproc_compare,detrend_methmedianf3_zscoreFalse,statav10,PP_Compare,pre_process,0.999999,3.174368e-02,9.413917e-03,NaN,0,2,1
3,preproc_compare,detrend_methmedianf3_zscoreFalse,statav2,PP_Compare,pre_process,0.998950,7.718298e-01,2.014565e+12,NaN,0,2,2
4,preproc_compare,detrend_methmedianf3_zscoreFalse,statav4,PP_Compare,pre_process,0.999991,9.496158e-02,2.529813e-02,NaN,0,0,0
5,preproc_compare,detrend_methmedianf3_zscoreFalse,swss2_2,PP_Compare,pre_process,0.962030,4.439361e+00,3.762079e-02,NaN,0,2,2
6,preproc_compare,detrend_methmedianf3_zscoreFalse,swms10_1,PP_Compare,pre_process,0.185374,4.371099e+00,4.823064e-02,NaN,0,2,0
7,preproc_compare,detrend_methmedianf3_zscoreFalse,swss2_1,PP_Compare,pre_process,0.004001,3.256076e+01,4.512625e+12,NaN,0,2,2
8,preproc_compare,detrend_methmedianf3_zscoreFalse,statav6,PP_Compare,pre_process,0.998077,1.274938e+00,1.255397e-02,NaN,0,0,0
9,preproc_compare,detrend_methmedianf3_zscoreFalse,olbt_s2,PP_Compare,pre_process,0.466542,5.276231e-03,1.837395e-02,NaN,0,2,2
10,preproc_compare,detrend_methmedianf3_zscoreFalse,olbt_m5,PP_Compare,pre_process,0.908334,5.725122e-01,1.266274e-01,NaN,0,3,3
11,preproc_compare,detrend_methmedianf3_zscoreFalse,swms5_1,PP_Compare,pre_process,0.999997,5.722392e-02,1.479937e-02,NaN,0,2,2
12,preproc_compare,detrend_methmedianf3_zscoreFalse,swss5_1,PP_Compare,pre_process,0.991591,1.327184e+00,1.580348e-02,NaN,0,2,2
13,preproc_compare,detrend_methmedianf3_zscoreFalse,olbt_s5,PP_Compare,pre_process,0.315900,9.894826e-03,1.804451e+13,NaN,0,2,2
14,preproc_compare,detrend_methmedianf3_zscoreFalse,swss5_2,PP_Compare,pre_process,0.997936,5.968190e-01,1.014088e-02,NaN,0,2,1
15,preproc_compare,detrend_methmedianf3_zscoreFalse,swms2_2,PP_Compare,pre_process,0.999978,1.380522e-01,3.921657e-02,NaN,0,0,2
16,preproc_compare,detrend_methmedianf3_zscoreFalse,swss10_1,PP_Compare,pre_process,0.997603,4.579382e-01,1.013480e-02,NaN,0,2,1
17,preproc_compare,detrend_methmedianf3_zscoreFalse,swms5_2,PP_Compare,pre_process,0.999996,3.390210e-02,1.017599e-02,NaN,0,2,1
18,preproc_compare,detrend_methmedianf3_zscoreFalse,olbt_m2,PP_Compare,pre_process,0.941979,9.221183e-01,1.016304e+00,NaN,0,3,3

In [10]:
from pyhctsa.operations.symbolic import transition_matrix

In [11]:
transition_matrix(z_score(dataset[71]), 'quantile', 2, 2)

{'T1': np.float64(0.49819927971188477),
 'T2': np.float64(0.001600640256102441),
 'T3': np.float64(0.0020008003201280513),
 'T4': np.float64(0.49819927971188477),
 'ondiag': np.float64(0.9963985594237695),
 'stddiag': np.float64(0.0),
 'symdiff': np.float64(0.0008003201280512204),
 'symsumdiff': np.float64(-0.0004001600640256102),
 'stdeig': np.float64(0.00253083446191946),
 'maxeig': np.float64(0.4999888499219686),
 'mineig': np.float64(0.4964097095018009),
 'maximeig': np.float64(0.0),
 'sumdiagcov': np.float64(0.24641156983001283),
 'stdeigcov': np.float64(0.1742392919896246),
 'maxeigcov': np.float64(0.2464115698300129),
 'mineigcov': np.float64(2.1256795734068898e-17)}

In [90]:
eng.SB_TransitionMatrix(z_score(dataset[71]), 'quantile', 2, 2)

{'T1': 0.49819927971188477,
 'T2': 0.001600640256102441,
 'T3': 0.0020008003201280513,
 'T4': 0.49819927971188477,
 'ondiag': 0.9963985594237695,
 'stddiag': 0.0,
 'symdiff': 0.0008003201280512204,
 'symsumdiff': -0.0004001600640256102,
 'stdeig': 0.00253083446191946,
 'maxeig': 0.4999888499219686,
 'mineig': 0.4964097095018009,
 'maximeig': 0.0,
 'sumdiagcov': 0.24641156983001283,
 'stdeigcov': 0.17423929198962457,
 'maxeigcov': 0.24641156983001283,
 'mineigcov': -6.938893903907228e-18}

In [83]:
np.argsort(abs(outputs['how_to_cgquantile_num_groups2_tauac_zscoreTrue::T4']['py'] - outputs['how_to_cgquantile_num_groups2_tauac_zscoreTrue::T4']['mat']))[::-1]

array([ 71, 895, 980, 351, 886, 919,  29, 516, 426, 912, 911, 673, 832,
       843, 412,  49, 831, 411, 182, 178, 826, 181, 837,  21, 635, 988,
       828,  55, 671, 440, 829, 606, 438, 992, 699, 959, 471, 967, 976,
       844, 812, 821,  53, 169, 779, 966, 968, 165, 416, 811, 638, 977,
       802, 307, 915, 841, 898, 301, 603, 851, 974, 970, 437, 634, 773,
       225, 154, 174, 960, 969, 889, 772, 973, 999, 435, 963, 857, 760,
       962, 842, 921, 891, 852, 380, 922, 987, 679, 593, 620, 856, 707,
       964, 441, 955, 807, 900, 488, 867, 652, 223, 677, 956, 972, 965,
       752, 990,  74, 824, 171, 997, 227, 751, 882, 971, 574, 648, 226,
       961, 382, 305,  41, 846, 618, 619, 678, 975, 106, 978, 701, 774,
       528, 282, 896, 951, 847, 697, 698,  99, 245, 864, 600, 251, 853,
       280, 246, 194, 153, 748, 676, 238, 581, 232, 901, 858, 833, 484,
       747, 729, 892, 639, 576, 369, 591, 884, 586, 277, 799, 726, 592,
       735, 954, 140, 172, 152, 800, 776, 650, 791, 158, 885, 993, 647,
       897, 741, 294, 925, 249, 688, 198, 859, 861, 937, 936, 103, 675,
       862, 746, 630, 775, 632, 947, 175, 674, 750, 702, 105, 104,   6,
       550, 740, 660, 804, 595, 795, 101,  84, 447, 704, 616,  20, 739,
       445, 727, 879, 743, 706, 615, 188, 329, 247,  17,  77, 155, 361,
        15, 244, 367, 784, 725, 235, 754, 622, 872,  72, 738, 132, 229,
       137, 883, 928, 531, 523, 708, 783, 395, 816, 228, 742, 108, 139,
       243, 590, 485, 107, 902, 552, 930, 611, 533, 667, 798, 168, 474,
       477, 478, 524,  65, 803, 703, 138, 682, 569, 834, 869, 526, 144,
        93, 880, 690,   0, 659, 481, 136, 252, 504, 113, 663, 196, 796,
       183, 166, 820, 929, 878, 109,   3, 123, 368, 587,  14, 141, 758,
       755, 757,  88,  18, 130, 952, 736, 868, 881, 341, 300, 596, 446,
       365, 810, 850, 927, 932, 610,  76, 819, 654, 865, 455, 924, 393,
       953, 236, 167, 656, 737, 448, 370, 785, 536, 398, 809, 794, 514,
       513,  67, 385, 562,  95,  59,  80, 450, 563, 540, 582, 151, 822,
       749, 744, 931, 633, 487, 525, 473, 145, 241, 855,  81, 728, 575,
       377, 589,  60, 386, 458, 110, 452, 384, 689, 666, 128, 705, 558,
       710, 934, 363, 456, 454, 527, 530, 923, 709, 584, 133, 204, 444,
       449, 364, 547, 777, 756, 745, 753, 871, 870, 711, 451, 184, 185,
       866, 933, 721, 148,  85, 193, 877, 579, 583, 146,  63, 479, 460,
       664, 147,  16, 333, 926, 149, 499, 538, 505, 506, 360, 668, 692,
       549, 762, 150, 501, 332, 561, 572,  92, 327, 326, 657,  96, 189,
       649, 909, 646, 651, 187, 186, 908, 564, 190, 191, 192, 180, 645,
       907, 195, 644, 197, 906, 199, 200, 201, 202, 203, 910, 176, 179,
       670, 661, 157, 156, 662, 665, 669, 734, 160, 672, 733, 732, 731,
       730, 143, 159, 161, 913, 918, 177, 205, 914, 916, 173, 917, 170,
       162, 920, 653, 655, 658, 164, 163, 643, 211, 206, 250, 256, 255,
       254, 253, 759, 873, 874, 641, 248, 875, 876, 636, 637, 640, 257,
       258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270,
       271, 272, 273, 242, 240, 207, 215, 221, 220, 219, 218, 217, 216,
       214, 239, 213, 212, 724, 210, 209, 208, 222, 905, 224, 904, 903,
       899, 894, 893, 230, 231, 890, 233, 234, 888, 642, 237, 887, 142,
       680, 723,  43, 984,  48,  47,  46,  45,  44,  42,  34, 985,  40,
        39,  38,  37,  36,  50,  51,  52, 983,  54, 982,  56,  57,  58,
       716, 700,  61,  62, 717,  64, 981,  66,  35,  33, 935,   8, 713,
        13,  12,  11,  10,   9,   7,  32, 996,   5,   4, 712,   2,   1,
       995, 714, 994, 715,  19, 991, 989,  22,  23,  24,  25,  26,  27,
        28, 986,  30,  31, 718,  68,  69, 115, 121, 120, 119, 118, 117,
       116, 114,  70, 685, 112, 111, 686, 687, 941, 122, 684, 124, 125,
       126, 127, 683, 129, 722, 131, 940, 681, 134, 135, 275, 939, 938,
       942, 943, 944,  86, 979, 958,  73, 957,  75, 719, 696,  78,  79,
       695, 694,  82,  83, 693,  87, 945, 691,  89,  90,  91, 950,  94,
       720,  97,  98, 949, 100, 948, 102, 946, 274, 281, 276, 462, 468,
       467, 466, 465, 464, 463, 461, 580, 780, 459, 778, 457, 594, 597,
       469, 470, 817, 472, 781, 815, 475, 476, 814, 813, 782, 480, 588,
       482, 483, 585, 786, 598, 453, 599, 827, 421, 422, 423, 424, 425,
       830, 427, 428, 429, 430, 431, 432, 433, 434, 436, 771, 825, 823,
       439, 608, 607, 442, 443, 769, 605, 604, 818, 770, 602, 601, 486,
       808, 419, 535, 542, 541, 568, 539, 537, 789, 534, 489, 793, 532,
       570, 571, 529, 573, 543, 544, 545, 546, 567, 548, 792, 551, 790,
       553, 554, 555, 556, 557, 566, 559, 560, 797, 788, 801, 507, 490,
       491, 492, 493, 494, 495, 496, 497, 498, 998, 500, 502, 503, 578,
       508, 805, 509, 510, 511, 512, 577, 787, 515, 806, 517, 518, 519,
       520, 521, 522, 420, 418, 631, 319, 325, 324, 323, 322, 321, 320,
       318, 347, 317, 316, 315, 314, 313, 312, 328, 625, 330, 331, 624,
       334, 335, 336, 337, 338, 339, 340, 623, 342, 343, 344, 345, 311,
       310, 309, 292, 278, 279, 761, 565, 629, 283, 284, 285, 286, 287,
       288, 289, 290, 291, 293, 308, 628, 295, 296, 297, 298, 299, 627,
       626, 302, 303, 304, 863, 306, 860, 346, 348, 417, 768, 399, 609,
       397, 396, 839, 394, 392, 349, 391, 390, 389, 388, 387, 612, 400,
       401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 838, 836, 413,
       414, 415, 835, 613, 614, 383, 366, 350, 854, 352, 353, 355, 356,
       357, 358, 359, 621, 362, 763, 764, 765, 849, 840, 617, 848, 766,
       371, 372, 373, 374, 375, 376, 767, 378, 379, 845, 381, 354])

In [13]:
outputs['how_to_cgquantile_num_groups2_tauac_zscoreTrue::T4']['mat']

array([0.26245249, 0.25392539, 0.24662466, 0.24096386, 0.24224224,
       0.24924925, 0.2665066 , 0.24944989, 0.24724945, 0.25851703,
       0.20384077, 0.24284857, 0.22722272, 0.25345069, 0.24649299,
       0.250501  , 0.25525526, 0.27638191, 0.25945189, 0.25345069,
       0.26086957, 0.14285714, 0.        , 0.14285714, 0.2       ,
       0.4       , 0.25      , 0.        , 0.        , 0.33333333,
       0.        , 0.2       , 0.        , 0.        , 0.33333333,
       0.        , 0.2       , 0.33333333, 0.28571429, 0.        ,
       0.        , 0.26315789, 0.25      , 0.22789116, 0.24519231,
       0.24519231, 0.25252525, 0.25      , 0.25325325, 0.2       ,
       0.33333333, 0.33333333, 0.33333333, 0.27272727, 0.33333333,
       0.25      , 0.        , 0.25      , 0.17217217, 0.19678715,
       0.24324324, 0.2022022 , 0.16743349, 0.18127251, 0.25      ,
       0.14859438, 0.21442886, 0.20883534, 0.06640885, 0.24269903,
       0.        , 0.33333333, 0.23076923, 0.22222222, 0.23958333,
       0.25      , 0.27638191, 0.28140704, 0.27927928, 0.27891156,
       0.24048096, 0.28911565, 0.24448898, 0.27891156, 0.3       ,
       0.2364946 , 0.22278912, 0.20720721, 0.25581395, 0.23783784,
       0.20481928, 0.24698795, 0.23529412, 0.26530612, 0.25      ,
       0.26506024, 0.21584317, 0.17017017, 0.17517518, 0.30526316,
       0.22222222, 0.26666667, 0.22222222, 0.25840336, 0.26744186,
       0.26744186, 0.25301205, 0.24324324, 0.26126126, 0.23493976,
       0.1981982 , 0.1981982 , 0.19277108, 0.27891156, 0.28169014,
       0.12912913, 0.1991992 , 0.19627851, 0.24096386, 0.21643287,
       0.22645291, 0.23602484, 0.24698795, 0.24096386, 0.23076923,
       0.22569028, 0.22488996, 0.26126126, 0.28011204, 0.24519231,
       0.24419536, 0.26130653, 0.27163462, 0.1002004 , 0.2962963 ,
       0.18167267, 0.27512751, 0.25770308, 0.27452745, 0.26126126,
       0.26426426, 0.28228228, 0.22972973, 0.31543624, 0.25860689,
       0.24609844, 0.26230492, 0.26170468, 0.19935949, 0.2384954 ,
       0.23729492, 0.22368948, 0.27213607, 0.27313657, 0.2972973 ,
       0.27638191, 0.26315789, 0.25423729, 0.27427427, 0.2745098 ,
       0.24524525, 0.24924925, 0.24414716, 0.24749164, 0.24984997,
       0.30769231, 0.16323265, 0.47147147, 0.16863373, 0.43718593,
       0.33333333, 0.2042042 , 0.22822823, 0.18791946, 0.21052632,
       0.18647459, 0.24924925, 0.22413793, 0.00400802, 0.13043478,
       0.25      , 0.02013423, 0.00120048, 0.13405362, 0.24032403,
       0.23942394, 0.25425425, 0.28169014, 0.26262626, 0.26086957,
       0.21428571, 0.33333333, 0.20992099, 0.23684737, 0.24849699,
       0.21404682, 0.27516779, 0.21344269, 0.24329732, 0.21184237,
       0.10042008, 0.09541908, 0.10022004, 0.13627255, 0.10621242,
       0.11222445, 0.09395973, 0.1032413 , 0.09963986, 0.14561456,
       0.13313313, 0.14715719, 0.16053512, 0.14482897, 0.15663133,
       0.1002004 , 0.1002004 , 0.10067114, 0.10067114, 0.10004002,
       0.26714801, 0.22222222, 0.28571429, 0.25      , 0.21052632,
       0.33333333, 0.22222222, 0.26470588, 0.25770308, 0.23769508,
       0.1961962 , 0.2032032 , 0.27027027, 0.18060201, 0.20024005,
       0.25630252, 0.26576577, 0.26292629, 0.28313253, 0.2       ,
       0.2541806 , 0.26770708, 0.26165233, 0.24624625, 0.250501  ,
       0.26726727, 0.24832215, 0.26262626, 0.23745819, 0.26845638,
       0.27090301, 0.25252525, 0.25930372, 0.15543109, 0.24342434,
       0.23023023, 0.23323323, 0.19019019, 0.24024024, 0.23823824,
       0.24414716, 0.10702341, 0.16778523, 0.1638796 , 0.12541254,
       0.11611612, 0.13313313, 0.10367893, 0.11371237, 0.12842569,
       0.12091209, 0.12891289, 0.07707708, 0.06406406, 0.075015  ,
       0.08821764, 0.06281256, 0.21124225, 0.24124124, 0.25425425,
       0.2147651 , 0.23745819, 0.20528211, 0.24164833, 0.        ,
       0.11011011, 0.14114114, 0.        , 0.        , 0.14962993,
       0.24312431, 0.24542454, 0.23532353, 0.2470247 , 0.22147651,
       0.23411371, 0.23076923, 0.25083612, 0.24184837, 0.24044809,
       0.26846847, 0.19563913, 0.04980996, 0.04609218, 0.04026846,
       0.15436242, 0.04697987, 0.19767907, 0.11371137, 0.11111111,
       0.1110111 , 0.12012012, 0.10510511, 0.12512513, 0.10810811,
       0.11642328, 0.13813814, 0.18818819, 0.23823824, 0.2006689 ,
       0.20401338, 0.18729097, 0.23076923, 0.13382677, 0.17403481,
       0.18103621, 0.25022502, 0.25022502, 0.24924925, 0.25252525,
       0.25252525, 0.24909964, 0.16726691, 0.24872487, 0.19391026,
       0.22017614, 0.25330396, 0.22017614, 0.22017614, 0.27655311,
       0.232493  , 0.29009009, 0.23076923, 0.23298639, 0.232493  ,
       0.1740174 , 0.21848739, 0.        , 0.        , 0.16843369,
       0.21572157, 0.33333333, 0.        , 0.22268908, 0.22028812,
       0.21968788, 0.21968788, 0.21788715, 0.26890756, 0.26666667,
       0.23484697, 0.19038076, 0.27027027, 0.2746197 , 0.26426426,
       0.21568627, 0.21784357, 0.16246499, 0.22891566, 0.20883534,
       0.19418512, 0.24193548, 0.24358974, 0.22413793, 0.24358974,
       0.24193548, 0.24358974, 0.25525526, 0.26822917, 0.24264853,
       0.17217217, 0.15831663, 0.20910455, 0.22658127, 0.25      ,
       0.15662651, 0.24324324, 0.22435897, 0.27054108, 0.22522523,
       0.22772277, 0.21643287, 0.20848339, 0.21658986, 0.22613065,
       0.18967587, 0.22569028, 0.22285714, 0.12605042, 0.23847695,
       0.22882883, 0.23823824, 0.04809619, 0.22929172, 0.2414966 ,
       0.23694779, 0.23333333, 0.20095694, 0.27272727, 0.33333333,
       0.2       , 0.33333333, 0.2       , 0.16666667, 0.25      ,
       0.33333333, 0.28571429, 0.22222222, 0.        , 0.        ,
       0.2       , 0.        , 0.2       , 0.33333333, 0.33333333,
       0.25      , 0.33333333, 0.2       , 0.33333333, 0.        ,
       0.4       , 0.25      , 0.25      , 0.33333333, 0.26086957,
       0.30232558, 0.33333333, 0.30555556, 0.44444444, 0.33333333,
       0.24175824, 0.38461538, 0.25      , 0.18837675, 0.18436874,
       0.26315789, 0.28125   , 0.24444444, 0.25862069, 0.19839679,
       0.24048096, 0.23529412, 0.27163582, 0.2042042 , 0.23409364,
       0.23109244, 0.19847939, 0.27083333, 0.27327327, 0.26666667,
       0.23529412, 0.27777778, 0.26666667, 0.24442444, 0.26666667,
       0.23444689, 0.26666667, 0.13891389, 0.28405681, 0.23692369,
       0.25      , 0.26690676, 0.24248497, 0.21621622, 0.24193548,
       0.26666667, 0.26415094, 0.24193548, 0.2016129 , 0.24009604,
       0.27272727, 0.33333333, 0.30898876, 0.25396825, 0.36842105,
       0.32432432, 0.33333333, 0.31768953, 0.2962963 , 0.25090036,
       0.25      , 0.18837675, 0.18837675, 0.25140112, 0.17217217,
       0.18818819, 0.18818819, 0.18818819, 0.21888756, 0.2204882 ,
       0.23823824, 0.22008804, 0.2248996 , 0.23826715, 0.24829932,
       0.24789916, 0.24159664, 0.19803961, 0.24489796, 0.22900763,
       0.25625626, 0.25125125, 0.23954373, 0.21285141, 0.21285141,
       0.16666667, 0.33333333, 0.        , 0.33333333, 0.33333333,
       0.        , 0.        , 0.2       , 0.27376426, 0.26104418,
       0.27436823, 0.28108108, 0.27370948, 0.2444978 , 0.24624625,
       0.27490996, 0.2       , 0.2020202 , 0.17226891, 0.25514403,
       0.19095477, 0.24369748, 0.2310231 , 0.23039216, 0.12812813,
       0.1951952 , 0.24305556, 0.23943662, 0.21621622, 0.23529412,
       0.26726727, 0.28365385, 0.21821822, 0.21782178, 0.21710855,
       0.2338403 , 0.26633166, 0.28634361, 0.24497992, 0.24448898,
       0.25      , 0.25      , 0.24424424, 0.16758379, 0.25      ,
       0.25525526, 0.29411765, 0.26104418, 0.23847695, 0.31302521,
       0.19238477, 0.22342342, 0.19219219, 0.25203252, 0.25954198,
       0.25410164, 0.12512513, 0.25370148, 0.25320513, 0.25045045,
       0.23076923, 0.24504505, 0.23237179, 0.29229229, 0.26470588,
       0.24242424, 0.25225225, 0.20310155, 0.26330532, 0.16633267,
       0.25      , 0.26595745, 0.24096386, 0.24096386, 0.22822823,
       0.24864865, 0.23647295, 0.24509804, 0.28767123, 0.1991992 ,
       0.22818255, 0.25945946, 0.25      , 0.33333333, 0.        ,
       0.26530612, 0.22727273, 0.33333333, 0.1875    , 0.28571429,
       0.14480409, 0.27777778, 0.19090909, 0.22055675, 0.22222222,
       0.25628141, 0.25210084, 0.24615385, 0.25641026, 0.24369748,
       0.18367347, 0.2173913 , 0.16346154, 0.225     , 0.225     ,
       0.24489796, 0.24821974, 0.23300971, 0.12842569, 0.12751275,
       0.20312031, 0.22452245, 0.26370548, 0.19119119, 0.22044088,
       0.28313253, 0.20440882, 0.27309237, 0.28518519, 0.27777778,
       0.28571429, 0.27659574, 0.23684211, 0.14285714, 0.2892562 ,
       0.2       , 0.08050805, 0.        , 0.16661666, 0.15131513,
       0.20662066, 0.25882353, 0.21621622, 0.19444444, 0.22368421,
       0.1884058 , 0.20463158, 0.23913043, 0.1703125 , 0.23139159,
       0.01661779, 0.14258912, 0.19270833, 0.20733104, 0.22654691,
       0.18875   , 0.25079365, 0.25210084, 0.22818792, 0.2394958 ,
       0.2334934 , 0.23389356, 0.25630252, 0.20642064, 0.21344269,
       0.33333333, 0.125     , 0.2       , 0.25      , 0.25882353,
       0.26332288, 0.23076923, 0.20689655, 0.29268293, 0.20833333,
       0.23765432, 0.1153521 , 0.30701754, 0.26536496, 0.15930902,
       0.3401672 , 0.15764116, 0.16566225, 0.20333333, 0.29411765,
       0.2991453 , 0.25659293, 0.22765197, 0.1192832 , 0.21153237,
       0.25      , 0.25      , 0.2826087 , 0.26086957, 0.25      ,
       0.31818182, 0.24887556, 0.24513619, 0.25328084, 0.24      ,
       0.25      , 0.25620438, 0.25974026, 0.20496894, 0.1778291 ,
       0.17433414, 0.24319419, 0.17675545, 0.15964523, 0.17509452,
       0.17321867, 0.15742996, 0.16565481, 0.17505285, 0.18205238,
       0.15213358, 0.26061615, 0.23420074, 0.17552534, 0.25888325,
       0.26943005, 0.26863572, 0.27513812, 0.26373626, 0.27272727,
       0.21470671, 0.17365662, 0.18211488, 0.2132663 , 0.17682927,
       0.21615721, 0.16758242, 0.22052402, 0.20192308, 0.23655914,
       0.25952813, 0.25974499, 0.24169184, 0.19648094, 0.2074364 ,
       0.22309198, 0.2591687 , 0.2739726 , 0.23716381, 0.22504892,
       0.23460411, 0.19648094, 0.2228739 , 0.25244618, 0.20430108,
       0.19373777, 0.2739726 , 0.17302053, 0.23529412, 0.19766921,
       0.25115498, 0.23046092, 0.2316322 , 0.33333333, 0.25      ,
       0.33333333, 0.33333333, 0.28571429, 0.        , 0.22727273,
       0.27472527, 0.24324324, 0.25      , 0.25925926, 0.23809524,
       0.22891566, 0.25362319, 0.24144737, 0.27659574, 0.33333333,
       0.23636364, 0.33333333, 0.27777778, 0.25      , 0.26666667,
       0.25847458, 0.35714286, 0.35714286, 0.22222222, 0.22222222,
       0.17745098, 0.3115942 , 0.27393939, 0.18722222, 0.27016129,
       0.25555556, 0.31064516, 0.256     , 0.24074074, 0.28346457,
       0.27941176, 0.30188679, 0.32432432, 0.272     , 0.25842697,
       0.26075949, 0.23575758, 0.25806452, 0.17911663, 0.24489796,
       0.24226804, 0.07142857, 0.09090909, 0.24175824, 0.24175824,
       0.23728814, 0.22018349, 0.24175824, 0.36363636, 0.22167488,
       0.21019108, 0.27272727, 0.25148515, 0.16666667, 0.3030303 ,
       0.28571429, 0.30769231, 0.33333333, 0.33333333, 0.24242424,
       0.16666667, 0.16666667, 0.25      , 0.24561404, 0.25242718,
       0.26923077, 0.1875    , 0.14285714, 0.25925926, 0.2       ,
       0.25      , 0.2       , 0.24444444, 0.2       , 0.36363636,
       0.24630542, 0.23684211, 0.30291971, 0.27058824, 0.33333333,
       0.26804124, 0.1875    , 0.2826087 , 0.25252525, 0.30769231,
       0.26570916, 0.24      , 0.22727273, 0.28634361, 0.25862069,
       0.30232558, 0.28387097, 0.26666667, 0.25      , 0.3125    ,
       0.18401937, 0.25211506, 0.26283988, 0.25952813, 0.24697337,
       0.24806202, 0.24756335, 0.25060241, 0.25060241, 0.16713881,
       0.16666667, 0.16720257, 0.18743382, 0.28400955, 0.28761252,
       0.21404268, 0.25017651, 0.25360633, 0.24903041, 0.29017757,
       0.19699935, 0.33333333, 0.3       , 0.14285714, 0.275     ,
       0.17857143, 0.34782609, 0.34636872, 0.21428571, 0.25      ,
       0.33333333, 0.34090909, 0.35585586, 0.31325301, 0.44444444,
       0.28571429, 0.32743363, 0.26726058, 0.375     , 0.22580645,
       0.2507837 , 0.24603175, 0.25157233, 0.24561404, 0.33333333,
       0.2       , 0.14285714, 0.33333333, 0.33333333, 0.33333333,
       0.2       , 0.        , 0.33333333, 0.33333333, 0.33333333,
       0.        , 0.30434783, 0.25      , 0.24425059, 0.24595469,
       0.27069351, 0.18877136, 0.24489796, 0.24203822, 0.24479495,
       0.20786885, 0.23386484, 0.23189327, 0.20202874, 0.19101124,
       0.21836203, 0.26936937, 0.24914949, 0.18634908, 0.12502503,
       0.21552328, 0.23166216, 0.1531225 , 0.18269231, 0.18637957,
       0.16651656, 0.23354671, 0.22947537, 0.15086034, 0.18438438,
       0.19441944, 0.20024005, 0.27312094, 0.2328621 , 0.29273234,
       0.29196624, 0.36241611, 0.25      , 0.2       , 0.32753371,
       0.34598898, 0.34676145, 0.32082552, 0.35879945, 0.36151279,
       0.29032258, 0.34860453, 0.37490257, 0.37898687, 0.37274549,
       0.3738409 , 0.36870311, 0.37124913, 0.36853808, 0.34521576,
       0.35043504, 0.36489607, 0.36655949, 0.25301205, 0.16666667,
       0.33333333, 0.33333333, 0.        , 0.        , 0.33333333,
       0.4       , 0.21428571, 0.25      , 0.26666667, 0.21428571,
       0.25      , 0.16666667, 0.33333333, 0.24657534, 0.28571429,
       0.25      , 0.33333333, 0.26470588, 0.24427481, 0.26190476])

In [72]:
df[df['corr'] < 0.9]

,python_func,params,feature,matlab_func,python_module,corr,mae,mape,nan_count_py,nan_count_ml
71,transition_matrix,how_to_cgquantile_num_groups2_tauac_zscoreTrue,T4,SB_TransitionMatrix,symbolic,0.814943,0.014526,1.971056e+13,0,0
72,transition_matrix,how_to_cgquantile_num_groups2_tauac_zscoreTrue,T3,SB_TransitionMatrix,symbolic,0.746345,0.016230,5.670423e-02,0,0
73,transition_matrix,how_to_cgquantile_num_groups2_tauac_zscoreTrue,ondiag,SB_TransitionMatrix,symbolic,0.807464,0.030918,1.426140e+13,0,0
74,transition_matrix,how_to_cgquantile_num_groups2_tauac_zscoreTrue,stdeig,SB_TransitionMatrix,symbolic,0.752997,0.025304,1.801440e+12,0,0
75,transition_matrix,how_to_cgquantile_num_groups2_tauac_zscoreTrue,maxeig,SB_TransitionMatrix,symbolic,0.737719,0.003344,6.341292e-03,0,0
76,transition_matrix,how_to_cgquantile_num_groups2_tauac_zscoreTrue,symsumdiff,SB_TransitionMatrix,symbolic,0.719804,0.013864,4.380582e+13,0,0
77,transition_matrix,how_to_cgquantile_num_groups2_tauac_zscoreTrue,maxeigcov,SB_TransitionMatrix,symbolic,0.858094,0.005545,8.670828e+11,0,0
79,transition_matrix,how_to_cgquantile_num_groups2_tauac_zscoreTrue,symdiff,SB_TransitionMatrix,symbolic,0.750616,0.024247,8.761163e+13,0,0
80,transition_matrix,how_to_cgquantile_num_groups2_tauac_zscoreTrue,mineig,SB_TransitionMatrix,symbolic,0.777705,0.033351,6.114265e+12,0,0
81,transition_matrix,how_to_cgquantile_num_groups2_tauac_zscoreTrue,stdeigcov,SB_TransitionMatrix,symbolic,0.858094,0.003921,6.131201e+11,0,0
82,transition_matrix,how_to_cgquantile_num_groups2_tauac_zscoreTrue,stddiag,SB_TransitionMatrix,symbolic,0.732271,0.009973,1.767170e+13,0,0
83,transition_matrix,how_to_cgquantile_num_groups2_tauac_zscoreTrue,T1,SB_TransitionMatrix,symbolic,0.769375,0.017649,2.026620e+13,0,0
84,transition_matrix,how_to_cgquantile_num_groups2_tauac_zscoreTrue,sumdiagcov,SB_TransitionMatrix,symbolic,0.858094,0.005545,8.670828e+11,0,0
85,transition_matrix,how_to_cgquantile_num_groups2_tauac_zscoreTrue,T2,SB_TransitionMatrix,symbolic,0.815154,0.015156,2.927340e+12,0,0
86,transition_matrix,how_to_cgquantile_num_groups3_tauac_zscoreTrue,T3,SB_TransitionMatrix,symbolic,0.675937,0.018710,1.555568e+13,0,0
87,transition_matrix,how_to_cgquantile_num_groups3_tauac_zscoreTrue,ondiag,SB_TransitionMatrix,symbolic,0.849089,0.032584,6.761272e+12,0,0
91,transition_matrix,how_to_cgquantile_num_groups3_tauac_zscoreTrue,symdiff,SB_TransitionMatrix,symbolic,0.855866,0.102151,4.293803e+13,0,0
93,transition_matrix,how_to_cgquantile_num_groups3_tauac_zscoreTrue,stdeig,SB_TransitionMatrix,symbolic,0.839420,0.012856,5.983245e-02,0,0
94,transition_matrix,how_to_cgquantile_num_groups3_tauac_zscoreTrue,T6,SB_TransitionMatrix,symbolic,0.482579,0.022046,3.264216e+13,0,0
95,transition_matrix,how_to_cgquantile_num_groups3_tauac_zscoreTrue,maximeig,SB_TransitionMatrix,symbolic,0.627271,0.010707,2.487014e+13,0,0
96,transition_matrix,how_to_cgquantile_num_groups3_tauac_zscoreTrue,T4,SB_TransitionMatrix,symbolic,0.509842,0.022991,3.117849e+13,0,0
97,transition_matrix,how_to_cgquantile_num_groups3_tauac_zscoreTrue,T9,SB_TransitionMatrix,symbolic,0.887560,0.009347,8.897234e+12,0,0
98,transition_matrix,how_to_cgquantile_num_groups3_tauac_zscoreTrue,T7,SB_TransitionMatrix,symbolic,0.651889,0.020055,2.192670e+13,0,0
99,transition_matrix,how_to_cgquantile_num_groups3_tauac_zscoreTrue,T8,SB_TransitionMatrix,symbolic,0.554487,0.025511,2.714670e+13,0,0
100,transition_matrix,how_to_cgquantile_num_groups3_tauac_zscoreTrue,symsumdiff,SB_TransitionMatrix,symbolic,0.415123,0.043079,6.100660e+13,0,0
101,transition_matrix,how_to_cgquantile_num_groups3_tauac_zscoreTrue,T5,SB_TransitionMatrix,symbolic,0.706331,0.019039,1.225625e+13,0,0
102,transition_matrix,how_to_cgquantile_num_groups3_tauac_zscoreTrue,mineig,SB_TransitionMatrix,symbolic,0.755427,0.026248,1.522116e+13,0,0
103,transition_matrix,how_to_cgquantile_num_groups3_tauac_zscoreTrue,stddiag,SB_TransitionMatrix,symbolic,0.775368,0.008539,4.413190e+12,0,0
106,transition_matrix,how_to_cgquantile_num_groups3_tauac_zscoreTrue,T2,SB_TransitionMatrix,symbolic,0.568646,0.024361,3.469064e+13,0,0
107,transition_matrix,how_to_cgquantile_num_groups4_tauac_zscoreTrue,TD4,SB_TransitionMatrix,symbolic,0.890304,0.006846,6.609947e+12,0,0
108,transition_matrix,how_to_cgquantile_num_groups4_tauac_zscoreTrue,maximeig,SB_TransitionMatrix,symbolic,0.783856,0.011578,1.491501e+13,0,0
109,transition_matrix,how_to_cgquantile_num_groups4_tauac_zscoreTrue,TD3,SB_TransitionMatrix,symbolic,0.786647,0.009965,5.570442e+12,0,0
110,transition_matrix,how_to_cgquantile_num_groups4_tauac_zscoreTrue,ondiag,SB_TransitionMatrix,symbolic,0.855341,0.028470,7.550430e+12,0,0
111,transition_matrix,how_to_cgquantile_num_groups4_tauac_zscoreTrue,TD2,SB_TransitionMatrix,symbolic,0.647128,0.013856,1.566383e+13,0,0
113,transition_matrix,how_to_cgquantile_num_groups4_tauac_zscoreTrue,symsumdiff,SB_TransitionMatrix,symbolic,0.399653,0.050445,4.733504e+13,0,0
117,transition_matrix,how_to_cgquantile_num_groups4_tauac_zscoreTrue,mineig,SB_TransitionMatrix,symbolic,0.759915,0.020062,5.753657e+12,0,0
119,transition_matrix,how_to_cgquantile_num_groups4_tauac_zscoreTrue,stddiag,SB_TransitionMatrix,symbolic,0.845370,0.005754,4.988872e+12,0,0
120,transition_matrix,how_to_cgquantile_num_groups4_tauac_zscoreTrue,TD1,SB_TransitionMatrix,symbolic,0.890662,0.008516,9.017576e+12,0,0
123,transition_matrix,how_to_cgquantile_num_groups5_tauac_zscoreTrue,TD4,SB_TransitionMatrix,symbolic,0.687176,0.008140,9.153410e+12,0,0
124,transition_matrix,how_to_cgquantile_num_groups5_tauac_zscoreTrue,maximeig,SB_TransitionMatrix,symbolic,0.788447,0.010389,1.105212e+13,0,0
125,transition_matrix,how_to_cgquantile_num_groups5_tauac_zscoreTrue,TD3,SB_TransitionMatrix,symbolic,0.688287,0.009584,1.012215e+13,0,0
126,transition_matrix,how_to_cgquantile_num_groups5_tauac_zscoreTrue,ondiag,SB_TransitionMatrix,symbolic,0.877065,0.024582,1.348874e+13,0,0
127,transition_matrix,how_to_cgquantile_num_groups5_tauac_zscoreTrue,TD2,SB_TransitionMatrix,symbolic,0.743197,0.007960,3.926735e+12,0,0
129,transition_matrix,how_to_cgquantile_num_groups5_tauac_zscoreTrue,symsumdiff,SB_TransitionMatrix,symbolic,0.421229,0.054454,5.852399e+13,0,0
133,transition_matrix,how_to_cgquantile_num_groups5_tauac_zscoreTrue,mineig,SB_TransitionMatrix,symbolic,0.800476,0.014282,4.291903e+12,0,0
136,transition_matrix,how_to_cgquantile_num_groups5_tauac_zscoreTrue,stddiag,SB_TransitionMatrix,symbolic,0.813375,0.004353,5.582092e+12,0,0

In [63]:
outputs['k1_log_incTrue_q2.0_tau_step50_wtfdfa_zscoreTrue::r1_alpha']['py'][:10]

KeyError: 'k1_log_incTrue_q2.0_tau_step50_wtfdfa_zscoreTrue::r1_alpha'

In [58]:
outputs['k1_log_incTrue_q2.0_tau_step50_wtfdfa_zscoreTrue::r1_alpha']['mat'][:10]

array([0.51264847,        nan, 0.48647857,        nan,        nan,
              nan,        nan, 0.51098075, 0.53713514, 0.61742681])

In [39]:
from pyhctsa.operations.scaling import fluctuation_analysis

In [59]:
fluctuation_analysis(z_score(dataset[0]), 2.0, 'dfa', 50, 0, None, True)['r2_alpha']

np.float64(0.46990976649653465)

In [38]:
eng.SC_FluctAnal(z_score(dataset[0]), 2.0, 'dfa', 50.0, 0.0, '', True)['r2_alpha']

0.4695307464587432

In [64]:
df

,python_func,params,feature,matlab_func,python_module,corr,mae,mape,nan_count_py,nan_count_ml
0,fluctuation_analysis,absTrue_k2_log_incTrue_q2.0_tau_step50_wtfdfa_...,r2_alpha,SC_FluctAnal,scaling,0.997571,0.004213,0.026334,0,35
1,fluctuation_analysis,absTrue_k2_log_incTrue_q2.0_tau_step50_wtfdfa_...,ssr,SC_FluctAnal,scaling,0.990224,0.022524,0.194640,0,0
2,fluctuation_analysis,absTrue_k2_log_incTrue_q2.0_tau_step50_wtfdfa_...,r2_linfitint,SC_FluctAnal,scaling,0.996922,0.024083,0.022186,0,35
3,fluctuation_analysis,absTrue_k2_log_incTrue_q2.0_tau_step50_wtfdfa_...,resac1,SC_FluctAnal,scaling,0.989663,0.020384,0.182698,0,0
4,fluctuation_analysis,absTrue_k2_log_incTrue_q2.0_tau_step50_wtfdfa_...,se1,SC_FluctAnal,scaling,0.987488,0.005835,0.284435,0,0
5,fluctuation_analysis,absTrue_k2_log_incTrue_q2.0_tau_step50_wtfdfa_...,prop_r1,SC_FluctAnal,scaling,0.958940,0.012386,0.043314,0,0
6,fluctuation_analysis,absTrue_k2_log_incTrue_q2.0_tau_step50_wtfdfa_...,r1_ssr,SC_FluctAnal,scaling,0.999587,0.000147,0.020679,0,245
7,fluctuation_analysis,absTrue_k2_log_incTrue_q2.0_tau_step50_wtfdfa_...,r1_alpha,SC_FluctAnal,scaling,0.999889,0.003309,0.004764,0,245
8,fluctuation_analysis,absTrue_k2_log_incTrue_q2.0_tau_step50_wtfdfa_...,meanssr,SC_FluctAnal,scaling,0.999895,0.009003,0.005674,0,0
9,fluctuation_analysis,absTrue_k2_log_incTrue_q2.0_tau_step50_wtfdfa_...,r2_se2,SC_FluctAnal,scaling,0.986089,0.001457,0.086933,0,35
10,fluctuation_analysis,absTrue_k2_log_incTrue_q2.0_tau_step50_wtfdfa_...,linfitint,SC_FluctAnal,scaling,0.998076,0.053505,0.027378,0,0
11,fluctuation_analysis,absTrue_k2_log_incTrue_q2.0_tau_step50_wtfdfa_...,r1_se2,SC_FluctAnal,scaling,0.994421,0.001230,0.065440,0,245
12,fluctuation_analysis,absTrue_k2_log_incTrue_q2.0_tau_step50_wtfdfa_...,alpha,SC_FluctAnal,scaling,0.998649,0.009989,0.025830,0,0
13,fluctuation_analysis,absTrue_k2_log_incTrue_q2.0_tau_step50_wtfdfa_...,stdssr,SC_FluctAnal,scaling,0.999685,0.006840,0.030877,0,0
14,fluctuation_analysis,absTrue_k2_log_incTrue_q2.0_tau_step50_wtfdfa_...,logtausplit,SC_FluctAnal,scaling,0.956857,0.068191,0.018131,0,0
15,fluctuation_analysis,absTrue_k2_log_incTrue_q2.0_tau_step50_wtfdfa_...,se2,SC_FluctAnal,scaling,0.986546,0.001221,0.288366,0,0
16,fluctuation_analysis,absTrue_k2_log_incTrue_q2.0_tau_step50_wtfdfa_...,r1_linfitint,SC_FluctAnal,scaling,0.999942,0.009149,0.002460,0,245
17,fluctuation_analysis,absTrue_k2_log_incTrue_q2.0_tau_step50_wtfdfa_...,r2_se1,SC_FluctAnal,scaling,0.984033,0.009180,0.088471,0,35
18,fluctuation_analysis,absTrue_k2_log_incTrue_q2.0_tau_step50_wtfdfa_...,ratsplitminerr,SC_FluctAnal,scaling,0.911385,7.600358,0.137440,0,0
19,fluctuation_analysis,absTrue_k2_log_incTrue_q2.0_tau_step50_wtfdfa_...,r2_resac1,SC_FluctAnal,scaling,0.970217,0.012030,0.073687,0,35
20,fluctuation_analysis,absTrue_k2_log_incTrue_q2.0_tau_step50_wtfdfa_...,r1_se1,SC_FluctAnal,scaling,0.994365,0.003231,0.065440,0,245
21,fluctuation_analysis,absTrue_k2_log_incTrue_q2.0_tau_step50_wtfdfa_...,r2_ssr,SC_FluctAnal,scaling,0.999917,0.000354,0.043296,0,35
22,fluctuation_analysis,absTrue_k2_log_incTrue_q2.0_tau_step50_wtfdfa_...,r1_resac1,SC_FluctAnal,scaling,0.999134,0.003599,0.062207,0,245

In [34]:
from pyhctsa.operations.distribution import compare_ks_fit

In [43]:
compare_ks_fit(dataset[12], 'logn')

The data are not positive, but Log-Normal is a positive-only distribution.

nan

In [49]:
df

,python_func,params,feature,matlab_func,python_module,corr,mae,mape,nan_count_py,nan_count_ml
0,fast_dfa,zscoreTrue,zscoreTrue,SC_fastdfa,scaling,1.0,5.557789e-11,3.116361e-11,0,0

In [18]:
np.argsort(abs(outputs['what_distnnorm_zscoreFalse::peaksepx']['py'] - outputs['what_distnnorm_zscoreFalse::peaksepx']['mat']))[::-1]

array([243, 249, 248, 247, 251, 250, 745, 246, 901, 432, 635,  71, 643,
       950, 641, 409, 509,  54, 615, 587, 491, 495, 496, 896, 205, 171,
       284, 174, 195, 173, 355, 287, 224, 593, 225, 622, 262, 191, 230,
       206, 470, 533, 242, 294, 299, 298, 238, 320, 506, 307, 325, 261,
       272, 181, 271, 270, 263, 211, 157, 281, 212, 190, 240, 179, 162,
       594, 280, 180, 330, 260, 329, 590, 252, 347, 736, 740, 431, 351,
       427, 463, 900, 899, 424, 689, 869, 513,  51, 164, 963, 886, 887,
       511, 957, 914, 690, 457, 903, 459, 688, 971, 348, 848, 597, 968,
       601, 704, 911, 812, 956, 608, 730, 969, 967,  56, 839, 893, 959,
       891, 989, 804, 841, 964, 821, 808, 840, 845, 843, 844, 514,  22,
       822, 860,  70, 606, 862, 642,  53, 660, 829, 784, 787, 793, 918,
       607,  28, 800, 735, 851, 124, 415, 521, 788, 442, 781, 705, 448,
       777, 776, 857, 849, 916, 858, 855, 853, 161, 627, 182, 439, 445,
       399, 837, 420, 449, 703, 540, 539, 585, 658, 447, 446,   9, 105,
       444, 920, 611, 923, 440, 806, 344, 360,  12, 927, 925, 854, 109,
       387, 779, 441,  40, 921,  94, 422, 384, 541, 581, 605, 405, 339,
       341, 421, 510,  19, 416, 498, 201, 826, 202, 486, 499, 493, 785,
       783, 200,  97, 197, 725, 208,  96,  21,  64, 604, 346, 413, 699,
       204, 832, 481, 567, 170, 620, 629, 210, 712,  15, 402, 334, 631,
       403,  16, 706, 121, 414, 630, 391, 554, 388, 221, 172, 578, 167,
       577, 153, 458, 655, 286, 289, 400, 580, 129, 772, 139, 614, 545,
       475, 572, 546,  83,  65, 796, 134, 135, 193,  72, 576, 568, 529,
       570, 136, 488, 555, 100, 623, 461, 464, 476,  86, 452, 468,  98,
       618,  43,  45,  74,  93,  25,  44, 834, 600, 518, 155, 158, 268,
       575, 558, 574, 178, 183, 259, 256, 255, 192, 199, 799, 565, 809,
       564, 232, 228, 226, 209, 223, 220, 552, 835, 830, 831, 152, 149,
       148, 354, 392, 214, 519, 119, 708, 709, 370, 367, 523, 357, 356,
        13, 349, 537, 345, 340, 624, 337, 335, 527, 528, 315, 314, 313,
       312, 309, 125, 556, 395,  63, 185, 375, 122, 123, 144, 145, 292,
       278, 264, 184, 625, 693, 547, 189, 802, 550, 803, 234, 218, 216,
       215, 188, 333, 668, 436, 673,  88,  85,  81,  30,  32, 619, 484,
       490, 113,  23, 398,  91, 369, 472,  90, 361, 393, 187, 176, 500,
       505, 293,  33, 273, 389, 295, 296, 303, 137, 535,   2,   4, 317,
       318, 323,  58, 390,   0, 768, 780, 975, 595, 765, 976, 591, 634,
       637, 669, 801, 465, 679, 926, 501, 156, 762, 877, 159, 557, 766,
       138, 733, 504, 290, 111, 277,   8,   7, 411,  59, 945, 453, 677,
       551, 684, 363, 653, 875, 503,   6, 720, 507, 112, 674, 687, 732,
       650, 662, 466, 154, 682, 718, 871, 722,  46, 721, 715, 686, 719,
       683,  48, 879, 680, 676, 675, 929, 681, 943, 938, 931, 937, 930,
       685, 936, 648, 932, 647, 665, 716, 664,  50, 892, 237, 894, 236,
       235, 813, 233, 814, 231, 863, 815, 229, 165, 166, 816, 227, 817,
       818, 819, 820, 222, 811, 163, 239, 797, 147, 908, 907, 150, 151,
       794, 906, 905, 795, 904, 902, 810, 898, 798, 245, 160, 897, 244,
       895, 805, 807, 241, 823, 219, 824, 846, 207, 876, 850, 852, 186,
       874, 856, 203, 859, 873, 909, 872, 861, 870, 868, 867, 194, 866,
       196, 865, 198, 847, 878, 864, 842, 168, 169, 890, 889, 888, 885,
       825, 884, 175, 883, 217, 827, 828, 177, 833, 882, 213, 881, 880,
       836, 838, 146, 559, 910, 962,  37,  38,  39, 973,  41,  42, 972,
       970, 966,  47,  49, 965,  52, 961, 143,  55, 960,  57, 958,  60,
        61,  62, 955, 954, 953,  66,  67,  68,  36,  35,  34, 974,   1,
       990,   3, 988,   5, 987,  10,  11, 986, 985,  14, 984, 983,  17,
        18, 982,  20, 981, 980, 979,  24, 978,  26,  27, 977,  29,  31,
        69, 952, 951, 107, 933, 110, 114, 115, 116, 117, 118, 120, 791,
       928, 924, 126, 127, 128, 922, 130, 131, 132, 133, 919, 917, 915,
       913, 912, 140, 141, 142, 108, 106, 949, 934,  73, 948,  75,  76,
        77,  78,  79,  80, 947,  82, 946,  84, 944,  87,  89, 942, 941,
        92, 940, 939,  95,  99, 935, 101, 102, 103, 104, 792, 279, 253,
       646, 450, 451, 654, 454, 455, 456, 652, 651, 460, 462, 649, 467,
       469, 471, 657, 645, 473, 474, 644, 640, 477, 478, 479, 480, 639,
       482, 483, 638, 656, 659, 691, 672, 404, 406, 407, 408, 410, 412,
       678, 417, 418, 419, 423, 425, 426, 428, 661, 429, 430, 671, 670,
       433, 434, 435, 437, 438, 667, 666, 443, 663, 485, 487, 636, 579,
       592, 589, 530, 531, 532, 588, 534, 586, 536, 584, 538, 583, 582,
       542, 489, 543, 544, 573, 571, 569, 548, 549, 566, 563, 553, 562,
       561, 560, 526, 525, 524, 522, 633, 492, 632, 494, 628, 991, 497,
       626, 621, 617, 502, 616, 613, 508, 612, 610, 609, 512, 603, 602,
       515, 516, 517, 599, 598, 520, 596, 401, 397, 254, 308, 757, 756,
       297, 755, 754, 300, 301, 302, 753, 304, 305, 306, 752, 751, 759,
       310, 311, 750, 749, 748, 747, 316, 746, 744, 319, 743, 321, 322,
       758, 760, 396, 269, 790, 789, 257, 258, 786, 782, 778, 775, 774,
       265, 266, 267, 773, 771, 291, 770, 769, 274, 275, 276, 767, 282,
       283, 764, 285, 763, 288, 761, 742, 324, 741, 381, 368, 711, 710,
       371, 372, 373, 374, 707, 376, 377, 378, 379, 380, 382, 326, 383,
       702, 385, 386, 701, 700, 698, 697, 696, 695, 694, 394, 692, 713,
       366, 365, 364, 327, 328, 739, 738, 331, 332, 737, 734, 336, 338,
       731, 729, 728, 342, 343, 727, 726, 724, 723, 350, 352, 353, 717,
       358, 359, 714, 362, 992])

In [19]:
outputs['what_distnnorm_zscoreFalse::output']

{'py': array([nan, nan, nan, nan, nan, nan, nan]),
 'mat': array([nan, nan, nan, nan, nan, nan, nan])}

In [14]:
outputs['what_distnnorm_zscoreFalse::peaksepx']['mat'][:10]

array([ 0.18698449,  0.04104104, -0.02526315,  0.0734693 ,  0.03723724,
       -0.07567568,  0.04249737,  0.12882247,  0.06974504, -0.94661656])

In [10]:
df

,python_func,params,feature,matlab_func,python_module,corr,mae,mape,nan_count_py,nan_count_ml
0,compare_ks_fit,what_distnnorm_zscoreFalse,adiff,DN_CompareKSFit,distribution,1.000000,0.000139,7.650381e-04,0,0
1,compare_ks_fit,what_distnnorm_zscoreFalse,peaksepx,DN_CompareKSFit,distribution,0.999999,1.491429,6.969351e+09,0,0
2,compare_ks_fit,what_distnnorm_zscoreFalse,relent,DN_CompareKSFit,distribution,1.000000,0.000083,3.626460e-03,74,89
3,compare_ks_fit,what_distnnorm_zscoreFalse,peaksepy,DN_CompareKSFit,distribution,1.000000,0.001685,4.842727e-03,0,0
4,compare_ks_fit,what_distnnorm_zscoreFalse,olapint,DN_CompareKSFit,distribution,0.999998,0.000062,2.159658e-04,0,0
5,compare_ks_fit,what_distnnorm_zscoreFalse,what_distnnorm_zscoreFalse,DN_CompareKSFit,distribution,NaN,NaN,NaN,7,7

In [21]:
outputs['the_mom11.0_zscoreFalse::output']['py'][:5]

array([ 2.38988253e-04,  1.45820203e-06, -9.05482659e-06,  1.16227920e-05,
        2.07540822e-06])

In [42]:
from pyhctsa.operations.distribution import cv

In [48]:
eng.DN_cv((dataset[0]), 2.0)

0.6044058498772076

In [47]:
cv((dataset[0]), 2)

np.float64(0.6044058498772082)

In [52]:
outputs['k2.0_zscoreFalse::output']['py'][:3]

array([0.60440585, 0.16731818, 0.09386446])

In [54]:
outputs['k2.0_zscoreFalse::output']['mat'][:3]

array([0.60440585, 0.16731818, 0.09386446])

In [53]:
df

,python_func,params,feature,matlab_func,python_module,corr,mae,mape,nan_count_py,nan_count_ml
0,cv,k1.0_zscoreFalse,k1.0_zscoreFalse,DN_cv,distribution,1.0,3.029521e-05,1.010460e-12,0,1
1,cv,k2.0_zscoreFalse,k2.0_zscoreFalse,DN_cv,distribution,1.0,1.857106e+03,2.020911e-12,0,1
2,custom_skewness,what_skewpearson_zscoreFalse,what_skewpearson_zscoreFalse,DN_CustomSkewness,distribution,1.0,2.895674e-13,1.072860e-05,0,0
3,custom_skewness,what_skewbowley_zscoreTrue,what_skewbowley_zscoreTrue,DN_CustomSkewness,distribution,1.0,2.433815e-18,1.944746e-16,1,1

In [31]:
eng.SY_KPSStest(z_score(dataset[-1]), 1.0)

{'stat': 0.1773687230303343, 'pValue': 0.024486728863624636}

In [28]:
outputs['lags1_zscoreTrue::pValue']['py']

array([0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.03892881,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.01      , 0.1       , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.01      ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.1       , 0.01      ,
       0.1       , 0.01      , 0.1       , 0.01      , 0.01      ,
       0.1       , 0.1       , 0.1       , 0.01      , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.01      , 0.1       , 0.01      ,
       0.01      , 0.1       , 0.01      , 0.1       , 0.1       ,
       0.01      , 0.1       , 0.01323037, 0.1       , 0.09781003,
       0.1       , 0.1       , 0.1       , 0.01      , 0.01      ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.01      , 0.1       , 0.1       , 0.01      ,
       0.1       , 0.1       , 0.01      , 0.1       , 0.01      ,
       0.1       , 0.01      , 0.1       , 0.1       , 0.1       ,
       0.01      , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.06122603,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.01      ,
       0.1       , 0.08231286, 0.1       , 0.1       , 0.0463338 ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.01      , 0.1       , 0.01      , 0.1       , 0.01      ,
       0.01      , 0.1       , 0.1       , 0.1       , 0.01      ,
       0.1       , 0.1       , 0.0643252 , 0.1       , 0.1       ,
       0.01      , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.02173655, 0.01      , 0.1       ,
       0.05051238, 0.01      , 0.1       , 0.1       , 0.1       ,
       0.05662062, 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.01      , 0.01      , 0.01      , 0.1       ,
       0.01      , 0.1       , 0.01      , 0.09440459, 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01276465,
       0.01      , 0.01      , 0.01      , 0.01      , 0.1       ,
       0.1       , 0.1       , 0.01      , 0.1       , 0.1       ,
       0.01      , 0.1       , 0.1       , 0.05457521, 0.01      ,
       0.1       , 0.09009041, 0.1       , 0.1       , 0.1       ,
       0.1       , 0.02675535, 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.01      , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.01      , 0.01      , 0.1       ,
       0.1       , 0.01      , 0.01      , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.01      , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.04031513, 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.01      , 0.1       , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.04462644, 0.01      , 0.07244645, 0.01      , 0.01      ,
       0.1       , 0.01      , 0.01      , 0.1       , 0.1       ,
       0.01      , 0.02273481, 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.01      , 0.1       , 0.01      ,
       0.1       , 0.01251919, 0.01      , 0.1       , 0.01      ,
       0.1       , 0.01      , 0.1       , 0.1       , 0.1       ,
       0.01      , 0.03219105, 0.1       , 0.1       , 0.02590377,
       0.01      , 0.01      , 0.1       , 0.1       , 0.1       ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.02614675, 0.01      ,
       0.1       , 0.1       , 0.01      , 0.1       , 0.01      ,
       0.1       , 0.1       , 0.01      , 0.1       , 0.1       ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.01      , 0.01      , 0.01      , 0.1       ,
       0.01      , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.06203818, 0.01      , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.01      , 0.1       , 0.01      , 0.1       ,
       0.1       , 0.1       , 0.01      , 0.1       , 0.1       ,
       0.01      , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.03441767, 0.02565957,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.01      , 0.01      , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.01      , 0.1       ,
       0.1       , 0.01      , 0.01      , 0.07654118, 0.01      ,
       0.01      , 0.0730857 , 0.01      , 0.01      , 0.09695361,
       0.01      , 0.03474337, 0.1       , 0.1       , 0.01      ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.02194024, 0.1       , 0.01      , 0.01      ,
       0.01      , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.01      , 0.04871137, 0.01      ,
       0.06949994, 0.1       , 0.01      , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.01      , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.080897  ,
       0.07942904, 0.1       , 0.03279559, 0.1       , 0.01      ,
       0.1       , 0.1       , 0.09642992, 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.01      , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.04337237, 0.1       , 0.1       , 0.1       , 0.04570964,
       0.1       , 0.07672432, 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.01445495, 0.1       , 0.1       , 0.1       ,
       0.1       , 0.04137519, 0.1       , 0.1       , 0.01      ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.04457298, 0.07053805,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.09541266,
       0.01      , 0.08913398, 0.01      , 0.01      , 0.03140362,
       0.01      , 0.03613612, 0.01      , 0.1       , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.1       , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.04060941, 0.01      , 0.1       , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.09941337, 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.1       , 0.1       ,
       0.1       , 0.01      , 0.1       , 0.01      , 0.09079272,
       0.1       , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.09429206,
       0.01      , 0.01      , 0.01      , 0.01      , 0.0229268 ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.1       , 0.01      , 0.04569039, 0.1       , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.09515625, 0.01049453,
       0.1       , 0.01      , 0.01      , 0.01      , 0.1       ,
       0.03195009, 0.01      , 0.01      , 0.01      , 0.01      ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.02097893,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.1       , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.1       , 0.01681872,
       0.01730526, 0.1       , 0.1       , 0.1       , 0.1       ,
       0.01      , 0.1       , 0.08674924, 0.1       , 0.01      ,
       0.1       , 0.0201137 , 0.01951747, 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.01      , 0.01      , 0.1       ,
       0.02461606, 0.1       , 0.1       , 0.1       , 0.01      ,
       0.01      , 0.1       , 0.1       , 0.1       , 0.08773485,
       0.1       , 0.0235844 , 0.01      , 0.1       , 0.03767316,
       0.1       , 0.1       , 0.1       , 0.1       , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01319978, 0.01      ,
       0.01      , 0.01      , 0.07361857, 0.01      , 0.02448673])

In [29]:
outputs['lags1_zscoreTrue::pValue']['mat']

array([0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.1 ,
       0.1 , 0.1 , 0.1 , 0.01, 0.1 , 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.01, 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01, 0.1 , 0.01, 0.1 , 0.01, 0.1 , 0.01, 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.01, 0.01, 0.1 , 0.01, 0.1 , 0.1 , 0.01, 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.01, 0.01, 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.01, 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.01, 0.1 , 0.1 , 0.1 , 0.01,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.01, 0.1 , 0.01, 0.1 , 0.01, 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.01, 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.01, 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.01, 0.01, 0.01, 0.1 , 0.1 , 0.1 , 0.01, 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.01, 0.01, 0.01, 0.01, 0.1 , 0.1 , 0.01, 0.01, 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.01, 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.01, 0.01, 0.1 , 0.1 , 0.01,
       0.01, 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.01, 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.01,
       0.1 , 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.1 , 0.01, 0.1 , 0.01, 0.01,
       0.1 , 0.1 , 0.01, 0.1 , 0.1 , 0.01, 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.01, 0.1 , 0.01, 0.1 , 0.1 ,
       0.01, 0.1 , 0.01, 0.1 , 0.01, 0.1 , 0.1 , 0.1 , 0.01, 0.1 , 0.1 ,
       0.1 , 0.1 , 0.01, 0.01, 0.1 , 0.1 , 0.1 , 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.01, 0.1 , 0.01, 0.1 , 0.1 , 0.01, 0.1 , 0.1 , 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.01, 0.01, 0.01, 0.1 , 0.01, 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.01, 0.1 , 0.1 , 0.1 , 0.1 , 0.01, 0.1 , 0.01, 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.01, 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.01, 0.01, 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.01,
       0.1 , 0.1 , 0.01, 0.1 , 0.01, 0.01, 0.1 , 0.1 , 0.01, 0.01, 0.1 ,
       0.01, 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.01, 0.01, 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.01, 0.1 ,
       0.01, 0.1 , 0.1 , 0.01, 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.01, 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.01,
       0.01, 0.01, 0.01, 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.01, 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.01, 0.01, 0.01, 0.01, 0.01, 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.1 ,
       0.01, 0.1 , 0.01, 0.01, 0.1 , 0.01, 0.1 , 0.01, 0.1 , 0.01, 0.01,
       0.01, 0.1 , 0.1 , 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.1 , 0.01,
       0.1 , 0.01, 0.01, 0.01, 0.1 , 0.01, 0.1 , 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.1 , 0.1 , 0.01, 0.1 , 0.1 , 0.1 , 0.01, 0.01, 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.01, 0.1 , 0.1 , 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.1 , 0.01, 0.01, 0.01, 0.01, 0.1 , 0.1 ,
       0.1 , 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.1 , 0.01,
       0.1 , 0.1 , 0.01, 0.1 , 0.01, 0.01, 0.1 , 0.1 , 0.1 , 0.01, 0.1 ,
       0.01, 0.1 , 0.1 , 0.1 , 0.01, 0.01, 0.01, 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.1 , 0.01, 0.01, 0.01,
       0.01, 0.01, 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.01,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.01, 0.01, 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.01, 0.01, 0.1 , 0.1 ,
       0.1 , 0.1 , 0.1 , 0.1 , 0.01, 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 ,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.1 , 0.01, 0.01, 0.01, 0.1 , 0.01, 0.1 ])

In [180]:
np.argwhere(np.isnan(outputs['l20_segment_howfix_zscoreTrue::max']['mat']))

array([[407],
       [410],
       [411],
       [412],
       [413],
       [414],
       [417],
       [420],
       [421],
       [422],
       [426],
       [428],
       [429],
       [431],
       [434],
       [435],
       [438],
       [440],
       [441],
       [597],
       [598],
       [599],
       [600],
       [601],
       [602],
       [603],
       [604],
       [606],
       [609],
       [613],
       [615],
       [616],
       [618],
       [621],
       [647],
       [649],
       [650],
       [651],
       [652],
       [655],
       [656],
       [658],
       [674],
       [678],
       [682],
       [683],
       [686],
       [692],
       [693],
       [694],
       [695],
       [696],
       [697],
       [698],
       [699],
       [702],
       [704],
       [705],
       [706],
       [707],
       [709],
       [710],
       [711],
       [712],
       [713],
       [714],
       [715],
       [717],
       [719],
       [720],
       [723],
       [724],
       [725],
       [727],
       [732],
       [735],
       [737],
       [740],
       [741],
       [742],
       [762],
       [769],
       [772],
       [773],
       [775],
       [778],
       [786],
       [787],
       [788],
       [789],
       [808],
       [812],
       [813],
       [817],
       [818],
       [822],
       [823],
       [835],
       [849],
       [856],
       [858],
       [865],
       [866],
       [867],
       [868],
       [869],
       [870],
       [874],
       [903],
       [924],
       [926],
       [927],
       [934],
       [936],
       [937],
       [938],
       [939],
       [941],
       [942],
       [945],
       [946],
       [948],
       [949]])

In [183]:
from pyhctsa.operations.stationarity import drifting_mean

In [9]:
df

,python_func,params,feature,matlab_func,python_module,corr,mae,mape,nan_count_py,nan_count_ml
0,drifting_mean,l20.0_segment_howfix_zscoreTrue,meanabsmaxmin,SY_DriftingMean,stationarity,1.0,1.735920e-14,1.513402e-16,0,0
1,drifting_mean,l20.0_segment_howfix_zscoreTrue,meanmaxmin,SY_DriftingMean,stationarity,1.0,8.010751e-15,4.268544e-15,0,0
2,drifting_mean,l20.0_segment_howfix_zscoreTrue,min,SY_DriftingMean,stationarity,1.0,8.743489e-15,1.754025e-16,0,0
3,drifting_mean,l20.0_segment_howfix_zscoreTrue,max,SY_DriftingMean,stationarity,1.0,1.920123e-14,1.699329e-16,0,0
4,drifting_mean,l20.0_segment_howfix_zscoreTrue,mean,SY_DriftingMean,stationarity,1.0,3.106709e-15,1.230867e+00,0,0
5,drifting_mean,l50.0_segment_howfix_zscoreTrue,meanabsmaxmin,SY_DriftingMean,stationarity,1.0,1.856846e-15,1.822449e-16,0,0
6,drifting_mean,l50.0_segment_howfix_zscoreTrue,meanmaxmin,SY_DriftingMean,stationarity,1.0,3.285533e-15,1.953057e-14,0,0
7,drifting_mean,l50.0_segment_howfix_zscoreTrue,min,SY_DriftingMean,stationarity,1.0,3.915129e-15,2.263634e-16,0,0
8,drifting_mean,l50.0_segment_howfix_zscoreTrue,max,SY_DriftingMean,stationarity,1.0,4.476155e-15,2.360243e-16,0,0
9,drifting_mean,l50.0_segment_howfix_zscoreTrue,mean,SY_DriftingMean,stationarity,1.0,1.149778e-15,2.914069e-01,0,0
10,drifting_mean,l100.0_segment_howfix_zscoreTrue,meanabsmaxmin,SY_DriftingMean,stationarity,1.0,4.771797e-15,2.786453e-16,0,0
11,drifting_mean,l100.0_segment_howfix_zscoreTrue,meanmaxmin,SY_DriftingMean,stationarity,1.0,5.963790e-16,2.825531e-14,0,0
12,drifting_mean,l100.0_segment_howfix_zscoreTrue,min,SY_DriftingMean,stationarity,1.0,3.950086e-15,4.614447e-16,0,0
13,drifting_mean,l100.0_segment_howfix_zscoreTrue,max,SY_DriftingMean,stationarity,1.0,4.108342e-15,5.405719e-16,0,0
14,drifting_mean,l100.0_segment_howfix_zscoreTrue,mean,SY_DriftingMean,stationarity,1.0,5.965076e-16,1.386817e-01,0,0
15,drifting_mean,l5.0_segment_hownum_zscoreTrue,meanabsmaxmin,SY_DriftingMean,stationarity,1.0,1.639635e-16,2.178790e-04,0,0
16,drifting_mean,l5.0_segment_hownum_zscoreTrue,meanmaxmin,SY_DriftingMean,stationarity,1.0,1.145428e-16,2.178790e-04,0,0
17,drifting_mean,l5.0_segment_hownum_zscoreTrue,min,SY_DriftingMean,stationarity,1.0,1.873974e-16,2.178790e-04,0,0
18,drifting_mean,l5.0_segment_hownum_zscoreTrue,max,SY_DriftingMean,stationarity,1.0,2.200105e-16,2.178790e-04,0,0
19,drifting_mean,l5.0_segment_hownum_zscoreTrue,mean,SY_DriftingMean,stationarity,1.0,4.960807e-17,1.520595e-01,0,0
20,drifting_mean,l10.0_segment_hownum_zscoreTrue,meanabsmaxmin,SY_DriftingMean,stationarity,1.0,3.023232e-16,6.128326e-16,0,0
21,drifting_mean,l10.0_segment_hownum_zscoreTrue,meanmaxmin,SY_DriftingMean,stationarity,1.0,2.105346e-16,1.820590e-14,0,0
22,drifting_mean,l10.0_segment_hownum_zscoreTrue,min,SY_DriftingMean,stationarity,1.0,3.987108e-16,7.522661e-16,0,0
23,drifting_mean,l10.0_segment_hownum_zscoreTrue,max,SY_DriftingMean,stationarity,1.0,2.606000e-16,9.240612e-16,0,0
24,drifting_mean,l10.0_segment_hownum_zscoreTrue,mean,SY_DriftingMean,stationarity,1.0,6.919160e-17,1.358274e-01,0,0

In [101]:
eng.SY_SlidingWindow(z_score(dataset[410]), 'mean', 'std', 2.0, 1.0)

0.8411313477028991

In [102]:
from pyhctsa.operations.stationarity import sliding_window

In [105]:
sliding_window(z_score(dataset[410]), 'mean', 'std', 2.0, 1.0)

np.float64(0.8411313477028985)

In [99]:
np.argwhere(np.isnan(outputs['across_win_statstd_inc_move1_num_seg2_window_statmean_zscoreTrue::output']['mat']))

array([[410],
       [411],
       [412],
       [414],
       [417],
       [418],
       [422],
       [424],
       [425],
       [426],
       [428],
       [429],
       [433],
       [437],
       [438],
       [441],
       [604],
       [606],
       [619],
       [647],
       [648],
       [649],
       [650],
       [651],
       [653],
       [657],
       [658],
       [660],
       [676],
       [677],
       [678],
       [679],
       [680],
       [685],
       [690],
       [692],
       [693],
       [699],
       [700],
       [704],
       [705],
       [706],
       [707],
       [708],
       [714],
       [715],
       [716],
       [717],
       [721],
       [723],
       [726],
       [730],
       [731],
       [732],
       [733],
       [734],
       [736],
       [738],
       [739],
       [740],
       [741],
       [759],
       [762],
       [769],
       [773],
       [774],
       [775],
       [777],
       [779],
       [781],
       [782],
       [783],
       [784],
       [785],
       [786],
       [787],
       [788],
       [789],
       [790],
       [791],
       [792],
       [793],
       [794],
       [795],
       [796],
       [797],
       [798],
       [799],
       [800],
       [801],
       [802],
       [803],
       [804],
       [805],
       [806],
       [807],
       [811],
       [815],
       [818],
       [821],
       [822],
       [824],
       [834],
       [836],
       [837],
       [838],
       [839],
       [840],
       [841],
       [842],
       [843],
       [844],
       [847],
       [849],
       [854],
       [855],
       [858],
       [861],
       [863],
       [873],
       [903],
       [935],
       [936],
       [938],
       [939],
       [942],
       [943],
       [946],
       [947],
       [948],
       [949]])

In [93]:
df

,python_func,params,feature,matlab_func,python_module,corr,mae,mape,nan_count_py,nan_count_ml
0,sliding_window,across_win_statstd_inc_move1_num_seg2_window_s...,across_win_statstd_inc_move1_num_seg2_window_s...,SY_SlidingWindow,stationarity,1.0,8.114073e-17,3.976159e-13,0,131

In [57]:
np.argwhere(np.isnan(outputs['extra_param25_what_typelen_zscoreTrue::output']['mat']))

array([[409],
       [414],
       [416],
       [418],
       [420],
       [422],
       [425],
       [426],
       [429],
       [430],
       [432],
       [435],
       [438],
       [439],
       [441],
       [442],
       [597],
       [598],
       [599],
       [600],
       [601],
       [602],
       [603],
       [605],
       [606],
       [607],
       [608],
       [612],
       [615],
       [616],
       [617],
       [619],
       [620],
       [647],
       [648],
       [652],
       [655],
       [656],
       [658],
       [659],
       [661],
       [662],
       [676],
       [677],
       [678],
       [679],
       [686],
       [687],
       [692],
       [693],
       [694],
       [700],
       [702],
       [703],
       [705],
       [707],
       [708],
       [715],
       [716],
       [717],
       [718],
       [720],
       [722],
       [723],
       [724],
       [726],
       [728],
       [729],
       [733],
       [736],
       [739],
       [741],
       [743],
       [744],
       [745],
       [746],
       [747],
       [748],
       [749],
       [750],
       [751],
       [752],
       [753],
       [754],
       [755],
       [756],
       [757],
       [758],
       [759],
       [762],
       [769],
       [770],
       [774],
       [775],
       [776],
       [782],
       [783],
       [788],
       [789],
       [808],
       [809],
       [813],
       [816],
       [817],
       [819],
       [824],
       [826],
       [827],
       [828],
       [829],
       [830],
       [831],
       [832],
       [835],
       [845],
       [847],
       [848],
       [849],
       [851],
       [854],
       [857],
       [858],
       [859],
       [860],
       [861],
       [862],
       [863],
       [871],
       [872],
       [873],
       [874],
       [875],
       [876],
       [924],
       [925],
       [929],
       [931],
       [935],
       [936],
       [937],
       [938],
       [939],
       [941],
       [942],
       [945],
       [946],
       [947],
       [948],
       [949]])

In [54]:
from pyhctsa.operations.stationarity import stat_av

In [59]:
stat_av(z_score(dataset[409]), 'len', 25)

0.982770146889103

In [169]:
df.to_csv('criticality_validation.csv')

In [170]:
np.savez_compressed('criticality_validation_raw_outputs.npz', **outputs)